### ISSUE TITLE
2024_06: BUG: No access to SimUI when selecting Play within MM module in _ind world

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3189] opened 2024-06-18 21:44 UTC
## What happens now:
- FYI: Lindsey was using VA DESKTOP, Chrome browser. 
- [ ] On 6/18/24, when working with a team data file in the DDD from the _ind group, Lindsey selected MM module > More > Play:
![image](https://github.com/lzim/teampsd/assets/124643236/9c6afcf6-8398-4bc6-9381-2739a7c6bee4)

- [ ] And received this error message, unable to get into the simulation module even though a session had started:
![image](https://github.com/lzim/teampsd/assets/124643236/26ec0156-24f4-404b-94a3-5d11a696db67)

## What should happen:
- When a user clicks on any module > More > Play, the simulation module should load as expected.

**Comment by jamesmrollins** [comment] 2024-06-19 02:41
For action: @tejaspesquare
FYI: @lijenn @ljmoody @lzim @dlkibbe @dlounsbu  

## Additional Observation from Testing

- This error only occurs from the **_ind** group.  _shared and _team groups work as designed.
- It does not matter which browser is being used. We were able to recreate this error in both Chrome and Edge.

## SME Impact

- When exploring and learning the DDD, use the _shared or _team group. 
- That will allow navigation to the "Play" mode and the system model diagram.
- When we resolve, all groups will be able to navigate to system model diagram.

## Estimated Resolved by:  Thursday, 20 June

**Comment by lzim** [comment] 2024-06-19 22:32
@lzim just tested this and it seems that I am now able to navigate via Play of the DDD to the MM module. 

UPDATE: 
@matomasz 
@tejaspesquare 
@lijenn 
@ljmoody 

However, @jamesmrollins note above about the _ind world is unclear. 
_**How can an admin user discern what world I am accessing from the Admin Dashboard?**_ 

#### User journey:

1. I cannot tell what world I'm in from within the module either. 
![image](https://github.com/lzim/teampsd/assets/7454688/7b6e0a66-66e9-4cb3-af39-1a787e4a75e1)

2.I tried navigating back from the MM module to the Admin Dashboard and got this message: 
![image](https://github.com/lzim/teampsd/assets/7454688/b6e25f9d-54d4-4469-9c51-0a1c29c9d417)

3. I get automatically booted back to Sim UI PROD login. I login via administrator_login during world selection.

4. I navigate to Team Setup dialogue from the Admin Dashboard
I check _ind, _shared and _team worlds and I am listed as Administrator in all 3. 
![image](https://github.com/lzim/teampsd/assets/7454688/752d26d8-522a-454c-b6d6-c17164f004d9)

**Comment by lzim** [comment] 2024-06-19 22:50
Cross-Ref: #3182

**Comment by tejaspesquare** [comment] 2024-06-20 09:50
Hello @lzim, 
 
> 3. I get automatically booted back to Sim UI PROD login. I login via administrator_login during world selection.

We tried to reproduce this scenario however it seems working fine.

After successfully login navigated to Dashboard.
![image](https://github.com/lzim/teampsd/assets/144898781/d44f1820-e67f-429e-9b92-4e34cf84f6bf)

Home Screen
![image](https://github.com/lzim/teampsd/assets/144898781/743ed7ca-77c6-48d4-95dc-e0b19c2dca1a)

Rune MM Model
![image](https://github.com/lzim/teampsd/assets/144898781/973b0975-5fa7-409b-bb16-28912704e586)

Navigate to Dashboard
![image](https://github.com/lzim/teampsd/assets/144898781/7d034f97-d40d-4d26-8362-f8ef62ee0d95)



Possible cause: When it came back to Dashboard, the 'Team' dropdown in the Dashboard failed to load due to temporary network problem.

**Comment by lzim** [comment] 2024-06-21 22:03
**FYI wk3 2024_06 - #systems_sme_workflow**
@dlkibbe 
@dlounsbu 

@lzim received text from @jamesmrollins indicating that we can follow our **#consult_workflow** procedures **to prep Site research/572** for **THIS Tue 06/24**  _**MTL 3.7 Blue Live Consult**_ in **_team world** as planned (tho _ind words may not be functioning properly until Monday).
- **Wed 06/26** or Wed 07/17 - Site research/595  

- **Thu 06/27** & Tue 07/16 - Site research/616

**Comment by jamesmrollins** [comment] 2024-07-03 20:16
Cross reference the _ind world aspects of this in #3188 and #3182

**Closed by jamesmrollins** 2024-07-03 20:16 UTC
Labels: sim_ui, sim ui dev, bug, Development
