### ISSUE TITLE
wk1 2024_mar_epic ANDON Bug: Sim UI PROD password reset issue for new and newly added users

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3062] opened 2024-01-24 20:56 UTC
**1. Laura cannot change her password in PROD login instance:** 

![image](https://github.com/lzim/teampsd/assets/124643236/b91e9846-cadc-49bd-b2dd-712a87cc314b))

1. Bug discovered January 24, 2024 while user testing with Jenn Li in support_workflow. FYI: Jenn tested functionality and she **is** able to submit a password request. 
2. Bug is not unique to L Moody; impacts new and newly added users. Affects ongoing site consult prep setup within PROD instance. Because, post-setup, users get/set their password by using the password reset dialog if 1) their user account was setup as part of site prep or 2) they don't remember their password.

**Comment by jamesmrollins** [comment] 2024-01-25 04:16
@ljmoody please attempt to reset your password again and see if you get the same error.  Thank you. James

**Comment by ljmoody** [comment] 2024-01-25 15:04
Hi @jamesmrollins - I just tried again and received the same error:
![image](https://github.com/lzim/teampsd/assets/124643236/07d3e8e8-e229-46f7-b84b-86edf5fdf40a)

**Comment by ljmoody** [comment] 2024-02-07 23:44
**2/7/2024:** FYI, I am also unable to reset password with my praxis login,

**Comment by lzim** [comment] 2024-02-27 17:57
@ljmoody - This may impact our #consult_workflow sites all of whom need to be set up with the Password Reset functionality.

- _Will you please take a screenshot of the Inspector Console for DEV to get to the bottom of this?_
- _What browser were you using?_ 
- _Do you see it in both Chrome & Edge?_
- _Is this on a non-VA machine/laptop?_

**Comment by ljmoody** [comment] 2024-02-27 23:50
@lzim,  answers to your questions are below. FYI: We had a call with dev and David from Forio last night that may lead to help resolving this issue.

#### A screenshot of the Inspector Console for DEV to get to the bottom of this:
![image](https://github.com/lzim/teampsd/assets/124643236/ddfb70aa-a103-4d13-87aa-e7e12040a269)

#### What browser were you using?
Microsoft Edge

#### Do you see it in both Chrome & Edge?
Yes, on both browsers.

#### Is this on a non-VA machine/laptop?
It is on my VA laptop.
It also occurs on my non-VA machine (Apple) laptop.

fyi: @tejaspesquare

**Comment by ljmoody** [comment] 2024-02-29 19:31
Hi @tejaspesquare a! Before the weekend begins, please give us an update on this issue (progress, level of effort, estimate to complete, etc.). We are receiving the email exchanges between you and David and would like this card to be updated with the current status as of the end of your Friday with the latest information, please. Thank you!

**Comment by tejaspesquare** [comment] 2024-03-01 13:52
@ljmoody - We are still continuing troubleshoot the issue. Looking for error message which David has mentioned in his response.

**Comment by ljmoody** [comment] 2024-03-01 17:06
**3/1/24 update from Tejas:**
> Due to sync up issue between Github & Epicenter changes are not reflected. Hence, can't perform internal testing & unable to move code for your testing too.

**Comment by tejaspesquare** [comment] 2024-03-04 06:58
FYI All - As discussed in standup meeting today, for time being we will do manual copy code to intended environment.

**Comment by tejaspesquare** [comment] 2024-03-04 07:10
@ljmoody - Code copied manually to TEST-Slow. Kindly verify at your end, it should work now.

**Comment by ljmoody** [comment] 2024-03-04 18:32
@tejaspesquare - yes, I tested (in TEST) both VA and Praxis email account password reset and both worked successfully.

**Comment by lzim** [comment] 2024-03-06 18:46
@ljmoody & @tejaspesquare 

**We were reviewing this ANDON today in #systems_sme_workflow and wanted to know whether this has been or will be fixed in PROD.**

**Comment by tejaspesquare** [comment] 2024-03-07 04:15
@lzim - This is working on lower instances now & hoping should work for all in Prod very soon. Will update once this is done. Password Reset notification are received on both instance breakfix & prod, as per confirmation from Laura Moody. @ljmoody if you would like to add something here.

**Comment by ljmoody** [comment] 2024-03-07 15:53
Confirming development is in process, @lzim. Here's what is known this week:
FYI: Laura is mainly testing since her account is new/newly created, and this seems to be an issue; not the same for existing accounts.

- 3/4/24: TEST-slow password reset is successful for user. 
- 3/4/24: Testing in break-fix resulted in change password emails being sent, but no success when trying to reset the password (green Submit button non-responsive to clicking). 
- 3/5/4: Jenn was able to reset her password in break-fix, but she used her existing user account (not newly signed up like Laura). So it does seem to effect primarily new and newly setup user accounts.
- 3/6/24: User unsuccessful at resetting password in break-fix; successful at resetting password in PROD environment. 
- 3/7/24: 
    - TEST-slow: change password email sent to user, password reset successful
    - break-fix: change password email sent to user, user changed password, unsuccessful at logging in
    - PROD: change password email sent to user, password reset successful

fyi: @lijenn @tejaspesquare @jamesmrollins

**Comment by jamesmrollins** [comment] 2024-03-11 03:53
3/10/24 Sim UI Stand Up:

1.  @tejaspesquare indicates that @ljmoody need to test breakfix again and determine if the problem persists. Password resets were sent to @ljmoody 's VA and Praxis accounts.
2.  If problem persists, @ljmoody will require screen capture of the logs in the browser under the developer mode should her password resets not work.

**Comment by ljmoody** [comment] 2024-03-11 15:15
Hello @tejaspesquare - I reset my password and then when I try logging in again with the new password, I am unable to. Here is a screen capture of the inspector console:
![image](https://github.com/lzim/teampsd/assets/124643236/4dcf519b-1f9e-4660-95e7-d0f4f41aec8f)
fyi @jamesmrollins

**Comment by lzim** [comment] 2024-03-11 15:31
**Discussed at 8am-workflow**
**wk2 2024_mar_epic**
- [ ] @ljmoody will test Sim UI PROD to see if password reset function is working.

**Comment by jamesmrollins** [comment] 2024-03-11 17:52
@lzim 

## Findings

@ljmoody and I validated that the PROD instance does reset passwords.  The problem was that Laura's praxis email end user account was not registered for any PROD groups.  Therefore, the password reset didn't work for that account. 

## Recommendations

- Remove the ANDON alert and resume normal operations.
- Investigate the possibility to put in an error message "Username not found." This way the user knows why the request is not processed.

**Comment by lzim** [comment] 2024-03-12 16:46
This sounds like it's closed and not a bug. Thanks!

**Closed by lzim** 2024-03-12 16:46 UTC
Labels: sim_ui, sim ui dev, bug, Systems_science_technology_development

**Comment by hnorthcraft** [comment] 2026-02-26 19:17
#adjudicarte_memo
updating value streams.
updating to 5sp based on above documentation of efforts.
