### ISSUE TITLE
wk3 may_epic: story_6  Review/Discuss D365 Entities & Attributes (and attribute values)

### ISSUE THREAD

**Issue by hsnyder2** [lzim/teampsd#2013] opened 2021-05-21 19:13 UTC
Per [this diagram](https://dvagov.sharepoint.com/:b:/r/sites/teampsd_vha/Shared%20Documents/msd365_workgroup/Requirements%20Elaboration/MTL%20High%20Level%20ERD.pdf?csf=1&web=1&e=NOJZ4O), need discussion around the following topics:

1. How to incorporate Versions to work with Programs, possibly collapsing them into Session Type.
2. Discuss how this supports multiple teams associated w a facility or clinic over time.
3. Discuss pros/cons of having D365 dynamically generate CPG and Team names (remaining editable?).
4. Discuss bulk uploads vs all done in D365.  Can demo the later in Wednesday’s call(s).
5. Discuss putting Phase Type on tasks, email and invites (aka meetings).

**Comment by lijenn** [comment] 2021-06-14 14:41
duplicate of #2012, closing the card as this work is done.

**Closed by lijenn** 2021-06-14 14:41 UTC
