### ISSUE TITLE
wk4_aug epic: UAT BUG - Co-Planning & MTL Teams not running through nightly routine after initial setup 

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2192] opened 2021-08-24 22:07 UTC
1. **Who encountered the bug:** Jennifer Li

2. **Which instance are you testing in?:** QA

3. **Date/Time of the bug:** 8/24 ~9am Pacific

3. **Role:** Admin

4. **Detailed description of the bug:** 

On Mon. 8/23:
- Created co-planning groups and MTL teams for each Facilitator (group and teams have their name and the word 'email' in it).
- Added each facilitator into their specific group or team.
- Checked the 3 boxes (Facilitator, Admin, Setup complete).

On Tues. 8/24:
- Found that the co-planning groups and MTL teams were still in my dashboard under "My coplanning groups" or "My MTL teams" and the nightly process did not create the Dynamics group in the backend from the overnight process.
- Facilitators confirmed they did not see their coplanning group or MTL team

![image](https://user-images.githubusercontent.com/59668647/130696407-182ed01a-7579-49a8-9239-ef66a8edd35a.png)

Co-planning groups:
1. v01_matt_coplanning_email_group
2. v01_marcia_coplanning_email_group
3. v01_theresa_coplanning_email_group
4. v01_john_coplanning_email_group
5. v01_claire_coplanning_email_group

MTL Teams:
1. matt_email_mtl_team
2. john_email_mtl_team
3. theresa_email_mtl_team
4. claire_email_mtl_team
5. marcia_email_mtl_team
6. jane_email_mtl_team
7. debbie_email_mtl_team
8. david_email_mtl_team
9. cindy_email_mtl_team
10. tanya_email_mtl_team
11. swap_email_mtl_team

Note: Also got the same issue for 2 other groups I created as well, will post the names in the Facilitate WG channel's UAT Thread.

**Comment by hsnyder2** [comment] 2021-08-25 14:41
Jenn - Arlene and I have had a look at this and it doesn't seem as though the plug in ran for these teams when you checked "Setup Complete."  We both just went in and unchecked the Setup complete and rechecked it and it did.  Not sure why it didn't work when you did it but we would like to take 10-15 mins to do a screen share so we can get a little more detail about how it was done.  LMK when might work for you.  Thx!

**Comment by hsnyder2** [comment] 2021-08-30 14:45
Haven't been able to reproduce and no one else has reported this since it happened this one time so closing this ticket.

**Closed** 2021-08-30 14:45 UTC
Labels: d365
