### ISSUE TITLE
3/20 Populate mtl.how w/ COP questions

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#747] opened 2019-10-04 21:52 UTC
1. community guidelines 
2. code of conduct 

for 

- Team PSD Wiki (issues/features/voting) and 
- MTL Wiki (questions/answers/voting

**Comment by lzim** [comment] 2019-10-28 19:11
@staceypark 

I’m going to need help with this from HQ.

**Comment by ritahitching** [comment] 2019-11-12 20:41
@lzim @staceypark 

- Useful organization (https://www.contributor-covenant.org/) their code http://citizencodeofconduct.org/
- Possible covenant code using Markdown  https://www.contributor-covenant.org/version/1/4/code-of-conduct.md
- Alternative code of conduct https://www.djangoproject.com/conduct/
- Additional alternative code https://www.djangoproject.com/conduct/enforcement-manual/

**Comment by staceypark** [comment] 2019-12-20 23:02
Merging content with #829 

from @staceypark 
Categories:
1) Data UI
- How do I get access to the data folders? 
- How do I add new staff to our team's data folder?
2) Sim UI
- Where can I find the Vensim Models?
- How do I get a tutorial of the Sim UI?
3) Demo
- How can I sign up for a quick demo of the sim UI?
4) Facilitation
- Where can I find the Learner SEE guides?
- Where can I find the Facilitator SAY guides?
- Who is facilitating *Modeling to Learn*?
- Can anyone become a *Modeling to Learn* facilitator?
- How do I become a *Modeling to Learn* facilitator?
5) Research
- Where can I find the research grants supporting this project?
- Where can I find

form @lzim 
@staceypark 
These are nice first steps, but I think they focus a bit too much on the public audiences and not enough on the types of question that a learner will have when actively participating in _Modeling to Learn_

Can you work to build the FAQs of a typical clinician in the field going through _MTL_?
Does that make sense?

**Comment by staceypark** [comment] 2020-01-24 18:58
@jamesmrollins @branscombj @dlkibbe @dlounsbu 
I've started fleshing out the GitHub Wiki FAQ questions, in response to Lindsey's comments to make them more learner facing. Could folks take a look at the Questions above and add a few of their own as well that would be useful to a learner?

**Comment by branscombj** [comment] 2020-01-27 16:32
general questions - suggest replacing
> Where can I find the research grants supporting this project?
with
* Who developed _Modeling to Learn_?
* How is _Modeling to Learn_ funded? (and put all the NCPTSD/QIICs support in addition to all the research grants)

**Comment by dlounsbu** [comment] 2020-01-27 16:35
Hi @staceypark 

Your list of questions for the wiki is comprehensive.  Agree with Lindsey that, maybe, you can keep lists of questions for each section to no more than 6. 

I would add one quest for the Community of Practice section, specifically, "What is the community of practice?"; "How information I contribute to Community of Practice processed?" ("Who views it?" and/or "How will it be used?").

**Comment by staceypark** [comment] 2020-01-31 18:29
@branscombj @dlkibbe + HQ member will get back the meeting time in the upcoming MTL Facilitate meetings (Mon 2/3, Wed 2/5, Fri 2/7, Mon 2/10, Wed 2/12) to work on populating the mtl.how GitHub wiki with answers.

For questions with existing answers in our resources, the answers should be populated with links that point the learner to the richer resource. For example, for the question "What are the main units of the simulation interface?", we would point the learner to the Session 5 Learner SEE guide.

**Comment by staceypark** [comment] 2020-01-31 19:30
What is Modeling to Learn?
answer
Who facilitates Modeling to Learn?
asnwer
Who developed Modeling to Learn?
How is Modeling to Learn funded?
What is Modeling to Learn Red vs. Modeling to Learn Blue?

**Comment by branscombj** [comment] 2020-01-31 21:44
> 
> For questions with existing answers in our resources, the answers should be populated with links that point the learner to the richer resource. For example, for the question "What are the main units of the simulation interface?", we would point the learner to the Session 5 Learner SEE guide.

@dlkibbe @staceypark and I agreed that the only time a link would be all that's given is if there is a 100% congruence between the question and the linked resource; e.g., Where can I find Modeling to Learn videos? Otherwise, the wiki needs a short answer _plus_ a link to a resource; e.g., "What are the main units of the sim UI?" would not ONLY point to a see guide, because that would require the person looking for a quick response to go to another location and then wade through it for the answer to their question.

**Comment by branscombj** [comment] 2020-02-10 18:15
**General**

_What is Modeling to Learn?_
>*[Modeling to Learn (MTL)](https://github.com/lzim/mtl)* provides resources for frontline healthcare teams to improve local care quality to better serve their community. 

_Who facilitates Modeling to Learn?_
>*MTL Live* sessions are remotely co-facilitated by pairs of [subject matter experts](https://forio.com/app/va/va-psd-team/teampsd.html) (SMES) -- one VA mental health SME and one systems thinking SME. All facilitators have completed intensive training in *MTL* by TeamPSD.

_Who developed Modeling to Learn?_
>*MTL* was developed by Team Participatory System Dynamics, led by principal investigator L[indsey Zimmerman, PhD](https://lindseyzimmerman.com/). Read about Co-Investigators, Key Partners, and Work Group Leads [here](https://forio.com/app/va/va-psd-team/teampsd.html).

_How is Modeling to Learn funded?_
>*MTL* is funded by the National Institutes of Health (NIDA [R01DA046651](https://projectreporter.nih.gov/project_info_description.cfm?aid=9684317&icde=43169143&ddparam=&ddvalue=&ddsub=&cr=2&csb=default&cs=ASC&pball=) and [R21DA042198](https://projectreporter.nih.gov/project_info_description.cfm?aid=9318487&icde=42957249&ddparam=&ddvalue=&ddsub=&cr=1&csb=default&cs=ASC&pball=)) and the Veterans Health Administration (HSRD I01HX002521 PI: Zimmerman ). 

_What is Modeling to Learn Red vs. Modeling to Learn Blue?_
>Some teams in *MTL* Live are learning with [*MTL* Red resources](https://github.com/lzim/mtl/tree/master/red) and some teams are learning with [*MTL* Blue resources](https://github.com/lzim/mtl/tree/master/blue).

**Comment by branscombj** [comment] 2020-02-10 20:08
mtl.how - I suggest not using branded links as section headings; what about "Resources"?

What is the main Modeling to Learn homepage?
>You will find everything *Modeling to Learn* at [mtl.how](https://github.com/lzim/mtl
). 

Where can I find the Learner SEE guides?
>Learner SEE guides take you step by step through each session, with gifs, screenshots and hyperlinks to help. For *MTL* Red, go to [mtl.how/red](https://github.com/lzim/mtl/tree/master/red), choose Part1 or Part2, then select the Learner folder.  For *MTL* Blue, go to [mtl.how/blue](https://github.com/lzim/mtl/tree/master/blue), choose the session, then select the Learner folder. 

Where can I find the Facilitator SAY guides?


Where are the cheatsheets and how can I print one?

Can anyone become a Modeling to Learn facilitator?
>*Modeling to Learn* facilitator are mental health or systems thinking subject matter experts eligible for permission to access the VA corporate data warehouse. Additional qualifications are under development.

How do I become a Modeling to Learn facilitator?
>*MTL* Facilitate is the training course for *Modeling to Learn* facilitators. It is currently under review for accreditation. Please sign up for our listserv at _____ to receive updates on training opportunities.

**Comment by branscombj** [comment] 2020-02-10 20:50
Hi @staceypark I'm done with the 2 sections above!

**Comment by branscombj** [comment] 2020-02-10 21:44
mtl.how/data

Note: This and others will need to link to the cheatsheet(s), once we have those in mtl.how. Since they are somewhat buried when they're just in the session folders, could we add links to them on the Red and Blue ReadMe pages?

**Data Resources**

_How do I get access to the data folders?_
>Log in to the *MTL* data UI at [mtl.how/data](https://spsites.cdw.va.gov/sites/PTSD_OMHO/Pages/Default.aspx
) and select your VISN and Facility. You will see your data_UI folder at the bottom of the page.

_How do I add new staff to our team's data folder?_
>

_Our team makeup / clinic grids are changing. How do I update our team data?_
>

_New priorities are emerging in the VA. How do I drill down to a specific measure or template?_
>

_What is the difference between the data in the Splashpage and the data in the folders?_
>The Splashpage and the data_UI spreadsheet both allow you to interface with the VA corporate data warehouse and extract real-time data tables and trend charts. On the Splashpage, these are at the facility level. The data_UI lets you specify exactly what clinics or providers make up your frontline staff team and pull hyper-local data and charts. You can also drill down to see the individual patients to better understand how your charting becomes VA data; and you can generate a set of central-tendency parameters that summarize your team's trends over the past 2 years in each of the 5 modules of *MTL*.

_What is the difference between the folders: data_ui, team_data_sim_ui, and team_data_table?_
>

_Where does the data come from? How do I know it is valid?_
>The *MTL* data UI interfaces in real time with the VA corporate data warehouse, which is made up of data from your charting and other records the VA manages.

_What is the difference betwen the "Get Patient Level Data" and "Get Team Data Table" buttons in the data user-interface (data UI)?_
>

_I see blurry / blacked out columns in the data user-interface (data UI). How do I fix it?_
>

**Comment by staceypark** [comment] 2020-02-12 00:41
@branscombj would you be able to populate the rest of these before the MTL facilitate meeting tomorrow and I can fill these into mtl.how?

**Comment by staceypark** [comment] 2020-02-12 17:28
@branscombj @dlkibbe will finish posting the answers to the COP questions by 2/19

**Comment by branscombj** [comment] 2020-02-19 17:31
**Using the simulation user-interface**

_What is the difference between the modules - Care Coordination, Medication Management,_ 

_Psychotherapy, Aggregate, and Measurement Based Stepped Care & Suicide Prevention?_

_Can I experiment in more than one module in the sim UI?_

_What is the difference between the team and individual worlds?_

_How do I load new data into the sim UI?_

_Where does the data in the sim UI come from?_

_How were the mathematical models created?_ 

_How are the relationships between variables calculated?_

_What are the main units in the sim UI?_

_What are the different colors and shapes in the sim UI diagram?_

_How do I compare the results of multiple experiments at once?_

_Can we export the results of an experiment to show to our leadership?_

_How can I pull up a previous experiment?_

_What are the plus and minus signs in the model diagram?_

_Where can I find more information about each variable?_

**Comment by branscombj** [comment] 2020-02-19 17:32
**Access to the simulation user-interface**

_Can I try out the simulation user-interface (sim UI) if I’m not in *Modeling to Learn*?_

_How can I get a tutorial of the sim UI?_

_Can I see the actual Vensim models running the sim?_

_I am having login issues at mtl.how/sim. What can I do?_

**Comment by branscombj** [comment] 2020-02-24 10:42
For the questions about the data UI above, @dlkibbe you have been working with the data UI more recently than I; could you take a stab at short, linked responses? @staceypark otherwise I may need to fill these in when we do the data UI review.

**Comment by branscombj** [comment] 2020-02-24 11:55
@dlkibbe The attached is a compendium of questions and answers I've completed so far. I made a few changes to the order and wording of questions vs @staceypark 's far above; and I used different group headings. Trying to make sections have fewer than 10 questions, as David suggested. I will not be able to work on this for the next couple of days, so if you have any time to continue, please do! Thanks.
[COP_Q&A.docx](https://github.com/lzim/teampsd/files/4244390/COP_Q.A.docx)

**Comment by staceypark** [comment] 2020-02-27 16:53
Need to create pinned note:

**Comment by staceypark** [comment] 2020-03-04 00:05
@branscombj how are these coming? will these be ready by tomorrow your COB?

**Comment by lijenn** [comment] 2020-03-04 22:05
Few more questions and answers from a pilot reviewer:

_When should I use Internet Explorer or Chrome?_
> Use Explorer when you’re using the Data User Interface at https://mtl.how/data to get patient data or build your team data table.
> Use Chrome when you’re looking for the Session Guides at https://mtl.how or when using the Simulation User Interface at https://mtl.how/sim

_Are there different sign-on's in the Simulation User Interface? Individual and Team World?_
> Yes, you can select either one from the Simulation User Interface drop down menu.
> Team world is only needed for during your Team Blue Team Meeting. It enables the whole team to log in to the same place together at each learning session.
> Individual world is for learning on your own. And, it likely will be most helpful for MTL Video review.
 
_Will I need a different log-in username and password for each World?_
> No, you will use the same username (which will be your email) and password for each World log-in.

_Can I use my PIV card to log-in to any of the worlds?_
> No, unfortunately, we don’t have PIV “single sign-on” yet. (But, we hope to have it for a future release!)
> You will need your username (which will be your email) and password.

**Comment by branscombj** [comment] 2020-03-04 22:30
FYI @staceypark I am finding that I am able to edit the locked issues without unlocking them. Checked the specs:

- Other users can’t add new comments to this issue.
- You and other collaborators with access to this repository can still leave comments that others can see. _[and apparently edit subjects and content]_
- You can always unlock this issue again in the future.

**Comment by branscombj** [comment] 2020-03-04 23:27
@staceypark Where does the COP Guidelines document live? I'm trying to answer questions that are based on them. Plus we have the Before you Start alert at the top not linked to anything?

**Comment by branscombj** [comment] 2020-03-04 23:56
Question B. The long list of questions is daunting; although I realize it's sortable if people figure out where they can put in keywords. See the few (sort by Recently Updated) I added a grouping word to the front of the issue name and whether that seems worth it. I'm not sure the default order is alphabetical, so this is probably not all that helpful. Would be if they fell out in groups that way - easier to scan your eye down.

**Comment by branscombj** [comment] 2020-03-05 00:08
Question C. These are not entered into mtl.how:

**Questions I'm not sure how to answer:**
1. How are the relationships between variables calculated?
2. Is Modeling to Learn mandatory?
3. Why was I removed from the Community of Practice?
4. How is the information I contribute to Community of Practice processed? Who views it and/or how will it be used?
5. I have a question that cannot be posted in a public setting. Who do I email? 

**Data UI questions I have not gotten to looking up answers for yet:**

1. How do I add new staff to our team's data folder?
2. Our team makeup/clinic grids are changing. How do I update our team data?
3. New priorities are emerging in the VA. How do I drill down to a specific measure or template?
4. What is the difference between the folders: data_ui, team_data_sim_ui, and team_data_table?
5. What is the difference between the "Get Patient Level Data" and "Get Team Data Table" buttons in the data UI?
6. I see blurry/blacked out columns in the data UI. How do I fix it?

**Other Questions about Questions:**
1. How do I join my team's virtual meeting?
> Type mtl.how/live into any browser and it will take you to the sign-in page for the virtual meeting.

_That's what I put; but I did not link mtl.how/live to anything yet. Also, this is only for video and I think audio and video should be answered at the same time._

2. Where can I find the meeting link and conference code to join the meeting?

_Is this different or the same as above? Maybe this was intended to be answered with Check your pre-session and post-session emails, or your Team Time report. ?_

3. I missed a session of MTL Live. Where can I access the TMS Videos to make up the session?
> Go to mtl.how/video to find video recordings of all Modeling to Learn Blue sessions, for all 5 modules of MTL.

_That's what I put, but I'm not sure where we've landed re: where the videos will live and if it's a different place for TMS vs non-credit? Can we have a TMS-like landing page at mtl.how/video that links to each video plus gives instruction and links for TMS credit?_

**Comment by branscombj** [comment] 2020-03-05 02:33
> Few more questions and answers from a pilot reviewer:
> 
> 

Thanks @lijenn ! I've added these.

**Comment by staceypark** [comment] 2020-03-05 02:53
In the Wiki at mtl.how
> @staceypark
> Question A. Where does the COP Guidelines document live? I'm trying to answer questions that are based on them. Plus we have the Before you Start alert at the top not linked to anything?

**Comment by staceypark** [comment] 2020-03-05 02:55
Default order is by issue # in descending order, so having the keywords won't really help people unfortunately.

> Question B. The long list of questions is daunting; although I realize it's sortable if people figure out where they can put in keywords. See the few (sort by Recently Updated) I added a grouping word to the front of the issue name and whether that seems worth it. I'm not sure the default order is alphabetical, so this is probably not all that helpful. Would be if they fell out in groups that way - easier to scan your eye down.

**Comment by branscombj** [comment] 2020-03-05 03:17
@staceypark Oh yes, thanks! I added the link - wasn't able to make the Test Don't Guess graphic link to it (but it needs to link somewhere besides the image itself), so I just put it at the top of the comment box. Please see what you think.

> Question A. Where does the COP Guidelines document live? I'm trying to answer questions that are based on them. Plus we have the Before you Start alert at the top not linked to anything?

**Comment by staceypark** [comment] 2020-03-05 03:32
@branscombj I can handle the data questions.

I think the "Questions on Questions" section can remain how you answered them for now.

For the "Questions I'm not Sure" - Some of them can be answered from the wiki where the guidelines are. The rest, I think we can just not answer for now.

**Comment by branscombj** [comment] 2020-03-05 03:37
@staceypark  
> For the "Questions I'm not Sure" - Some of them can be answered from the wiki where the guidelines are. The rest, I think we can just not answer for now.

Yes, now that you reminded me where to find the guidelines, I'll answer post any remaining ones I can answer with that.

Sorry this took me so long!! Thank you for finishing the data questions. See my additional notes in the original Question C. entry above and feel free to post those ones I wasn't sure about if you think they're right!

Thank you!! 🏅

**Comment by lijenn** [comment] 2020-03-06 18:26
@branscombj 

Hi Jane! I don't believe I have access to the MTL repo yet so I cannot edit it.

For question/issue card 87 (https://github.com/lzim/mtl/issues/87), could you please edit the answer to the question to follow the same wording as it shows on the log-in page for the Sim:

>For the data UI, which is on the BISL SharePoint site, use Internet Explorer/Microsoft Edge. 

>The Modeling to Learn simulation user interface does not work on Explorer. Please use Edge, Firefox, Chrome or Safari via desktop or mobile.

Thank you!

**Comment by lzim** [comment] 2020-03-09 04:16
Hi @lijenn @branscombj and @staceypark 

#47-61 mtl repo - COP Issues Q&A
- Once this initial "seeding" of Q&A is complete this probably needs an automatic action or something in Zenhub for tracking these? 
- Can these be closed without disappearing them?
- For example, we will want to make sure that they come in as "New Issues" that get responded to in < 24 hours.
- Put them in a new ZenHub "MTL COP Questions" Pipeline for now…

**Comment by staceypark** [comment] 2020-03-09 15:49
From Workgroup Leads Meeting 2020/03/09:
Would we want several folks on the team to be point-persons for the mtl_how repo, meaning they would setup their notifications to receive alerts for all activity here?

**Comment by staceypark** [comment] 2020-03-11 18:09
Remaining task on this card is to populate the data-related questions on mtl.how which will be part of the data training (TBD after #918 is re-assessed)

Another point of consideration - 
1. Do we want to use labels and teach people how to use that to sort? Kind of like below how there are categories.

![image](https://user-images.githubusercontent.com/31089501/76448094-05f68c00-6387-11ea-94a3-28697aa09aa0.png)

**Comment by branscombj** [comment] 2020-03-11 18:13
Hmm, @staceypark does Github generatae labels

**Comment by branscombj** [comment] 2020-03-11 18:17
Also, perhaps change the title of the current pinned issue to just
Community of Practice Guidelines
so that shows in the compressed card. Add "- please read" if there's room.

**Comment by staceypark** [comment] 2020-03-11 19:04
Add to the SOP for the Community of Practice:
1. Clarify how issue cards are locked and when they will unlocked
2. How questions that are already answered will be addressed and cross-ref'ed (perhaps redundant questions should even be closed?)
3. How the search functions work in GitHub repo vs. ZenHub for those answering questions and how questions will be answered
4. Create document_card in the document_team tracker that tracks the SOP for the Community of Practice

**Comment by staceypark** [comment] 2020-03-19 23:19
@dlkibbe This is the community of practice issue I mentioned during the meeting. Jane thought you would be able to populate answers for the remaining Data-related questions.

Would you be able to do that on mtl.how? Not sure if you were ever oriented on where/how that goes. Let me know if you need help

**Comment by branscombj** [comment] 2020-03-20 13:22
@dlkibbe This Word document has the questions that still need answers in red. If you could write answers and return it, I'll post them at mtl.how. To see additional examples of the type of answers we're providing, go to the Issues tab at mtl.how. Thanks!
[cop_data_only.docx](https://github.com/lzim/teampsd/files/4359732/cop_data_only.docx)

**Comment by dlkibbe** [comment] 2020-03-20 13:25
@branscombj I'm conducting interviews this morning but will work on this this afternoon.

**Comment by dlkibbe** [comment] 2020-03-20 17:19
@branscombj I'll have to do this late tonight or early tomorrow morning - i've been "kicked off" the VA VPN when trying to get to the data UI.

**Comment by dlounsbu** [comment] 2020-03-20 17:33
I was able to use my SMART Card to connect. But I need to test my access to the DUI. Who could assist me?

**Comment by branscombj** [comment] 2020-03-20 17:34
@dlkibbe I think it can wait until your next workday opportunity. I wonder if your problem with the data UI has to do with the permissions thing we've submitted a form for?

**Comment by staceypark** [comment] 2020-03-25 15:32
I believe we've been testing permissions during the Facilitate meetings, so the team will be ready to support you then.
> I was able to use my SMART Card to connect. But I need to test my access to the DUI. Who could assist me?

**Comment by staceypark** [comment] 2020-03-25 15:32
@dlkibbe were you able to get into the VPN to complete these questions?

**Comment by branscombj** [comment] 2020-03-25 15:42
> @dlkibbe were you able to get into the VPN to complete these questions?

She was! I'm in process of copying them here for a quick look by you/Jen/Anthony before populating them on mtl.how

**Comment by branscombj** [comment] 2020-03-25 15:47
How do I add new staff to our team's data folder?
>New staff can be added to access the MTL data user interface by sending an email to mtl.help@va.gov.

Our team makeup / clinic grids are changing. How do I update our team data?
>Open the most recent Excel team data file that will be named in a specific format:
station number_team type_team name or color_data_ui_2020_Month_Day. Add or remove clinics on the ClinicSelection tab (column C) in the Excel file. Follow steps 3 through 5 in the Session #2 Learner Say Guide on mtl.how to create a fresh data file. Creating a new data file may take a significant amount of time due to the volume of data. 

New priorities are emerging in the VA. How do I drill down to a specific measure or template?
>In your team’s data file, click on the data tabs (dataDiag, dataHF, dataMeas) and see encounter type, CPT or ICD codes and descriptions, mental health templates used, and various other clinic measures.

What is the difference between the folders: data_ui, team_data_sim_ui, and team_data_table?
>**Data_ui** – Once you’ve logged into mtl.how/data, the data_ui folder appears at the bottom of your splashpage. This folder contains a sortable Excel file with clinic, clinician, and patient data presented in means, medians, and percentages for key variables likely to influence the team’s priorities for learning from Modeling to Learn.
>**Team_data_sim_ui** – Once you’ve logged into mtl.how/data, the team_data_sim_ui folder appears at the bottom of your splashpage. This folder contains the team data for use in the simulation user interface (sim UI).
>**Team_data_table** – This is an Excel data file that contains baseline parameters and general data notes for the MTL module your team selected (CC, MM, PSY, Agg, SP). The variables shown in bold red font are used in the simulation user interface (sim UI).

What is the difference betwen the "Get Patient Level Data" and "Get Team Data Table" buttons in the data user-interface (data UI)?

>After selecting clinics on the ClinicSelection tab for inclusion in your team’s data file, you click the “Get Patient Level Data” button to generate a file. This query, which includes data from the past 2 years, can take up to 15 minutes. The “Get Team Data Table” generates a file for use in the simulation user interface. In order to generate this file, you must select clinics on the SPReferrals tab that your team steps patients up to (GMH team) or steps patients down to (SMH team).

I see blurry / blacked out columns in the data user-interface (data UI). How do I fix it?

>Debbie and I don't know the answer to this one.

**Comment by staceypark** [comment] 2020-03-25 17:03
cross-ref #600
@branscombj @dlkibbe @lijenn 
My apologies, I populated these questions when language was still changing and didn't update it. This question should really read only have two parts - data_ui and team_data_table, which is why there isn't an explanation of all three. I've updated the answer below.

Having said that, we should still explain the difference between the two folders in one place across the resources. I see it at the top of Session 03 in the SAY, but we should also do it in the SEE guide (and double check the RED guides as well): #1237

I can put a one liner in the cheatsheet addressing that: #1236

What is the difference between the folders: data_ui and team_data_table?

Once you’ve logged into mtl.how/data, navigate to your specific VISN and facility. At the bottom of the Splashpage, you should see your team's folder. Once you click on that, you see see two folders: data_ui and team_data_table folder. 

data_ui – This folder contains the data UI, a sortable and filterable Excel user-interface with two buttons that pulls your team's data. "Get Patient Level Data" pulls a hyper-local query of patient data and team trends based on the clinics selected that make up your team. "Create Team Data Table" pulls parameters for the 5 _MTL_ modules and puts this file in the team_data_table folder.

team_data_table – This folder contains the team data table, an Excel file that contains means, medians and percentages of key variables for the 5 _MTL_ modules: CC, MM, PSY, AGG, SP.  

For _MTL_ blue: See here (add link) for further details.
For _MTL_ red: See here (add link) for further details.

**Comment by branscombj** [comment] 2020-03-25 18:28
Thanks, @staceypark ! We can do the See/SAY Blue/Red updates.

**Comment by staceypark** [comment] 2020-03-25 20:42
@branscombj @dlkibbe I've also updated the answers a bit below.

How do I add new staff to our team's data folder?
> New staff can be added to team folders at mtl.how/data by going to mtl.how/data, clicking on "Request Team Membership Change," and filling out the form.

Our team makeup / clinic grids are changing. How do I update our team data?
>Go to mtl.how/data. Click on your team folder and then click on your data_ui folder. Open the most recent Excel team data_ui file. Add or remove clinics on the ClinicSelection tab (column C) in the Excel file. Follow steps 3 through 5 in the Session #2 Learner Say Guide on mtl.how to create a fresh data file. Creating a new data file may take a significant amount of time due to the volume of data.

>For _MTL_ Blue: See here (add link) for further details.
>For _MTL_ Red: See here (add link) for further details.

New priorities are emerging in the VA. How do I drill down to a specific measure or template?
> In your team’s data_ui file, click on the data tabs (dataDiag, dataHF, dataMeas) and filter to the encounter type, CPT or ICD codes and descriptions, mental health templates, etc. in question.

>For _MTL_ Blue: See here (add link) for further details.
>For _MTL_ Red: See here (add link) for further details.


What is the difference betwen the "Get Patient Level Data" and "Create Team Data Table" buttons in the data user-interface (data UI)?

> After selecting clinics on the ClinicSelection tab for inclusion in your team’s data file, you can click either the “Get Patient Level Data” or "Create Team Data Table" buttons. 

> "Get Patient Level Data" pulls a hyper-local query of patient data and team trends based on the clinics selected that make up your team.

> "Create Team Data Table" pulls parameters for the 5 _MTL_ modules (CC, MM, PSY, AGG, SP) and puts this file in the team_data_table folder.  This file contains means, medians and percentages of key variables for these modules. 

> Unlike the "Get Patient Level Data" button, in order to generate this file, you must choose the modules you want to generate parameters for: all the modules with SP, all the modules without SP, or one of the modules individually. If you include the SP module, you must select clinics on the SPReferrals tab that your team refers to (General Mental Health or Specialty Mental Health team).

>For _MTL_ Blue: See here (add link) for further details.
>For _MTL_ Red: See here (add link) for further details.

I see blurry / blacked out columns in the data user-interface (data UI). How do I fix it?
> Click on a different tab and then go back, or try to widen the column until the blurriness resolves.

**Comment by staceypark** [comment] 2020-03-27 21:41
@branscombj @dlkibbe Added the remaining ones and done!
Debbie, I followed your recommendation and included  a screenshot for the team data folder question.

> How do I add new staff to our team's data folder?
> New staff can be added to team folders at mtl.how/data by going to mtl.how/data, clicking on "Request Team Membership Change," and filling out the form.

**Closed by staceypark** 2020-03-27 21:41 UTC
Labels: facilitate
