### ISSUE TITLE
ICEBOX: Prod/UAT Bug - Response to an Team email routed to the wrong team & Replying to an Email with no Response (<- Escalated bug with MS)

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2212] opened 2021-08-31 21:58 UTC
1. **Who encountered the bug:** Marcia and Jenn at Facilitate Workgroup today

2. **Which instance are you testing in?:** QA

3. **Date/Time of the bug:** Tues. 8/31 around 10am Pacific

3. **Role:** Marcia - Facilitator, Jenn - Admin

4. **Detailed description of the bug:** 

- Marcia and Jenn were testing if a Facilitator could see and response to a Team email (in a Team that the Facilitator is not mapped to) from the Activity Dashboard from the "All Activities" view.
- Marcia was able to find the email (though this was rather difficult, see feature request at the bottom of ticket) by searching for the subject line the Activity Dashboard.
- Marcia responded to this below from clicking on it from the Activity Dashboard and replied All to it.
![image](https://user-images.githubusercontent.com/59668647/131580794-e22c6718-cc50-404c-9a98-6aa339c78fc7.png)
- Jenn got the response at her gmail (as expected).
- **Bug: Email response was found in the Activity Dashboard, but now routed to the wrong team, it went to jenn3_email_mtl_team rather than jenn_mtl_team_email:**
![image](https://user-images.githubusercontent.com/59668647/131580550-e4bd3d3f-a0af-4566-b5ae-da7e23266a61.png)
- **Bug: Since Marcia responded to this email, shouldn't the email response date be recorded here as well (this Email is the one that contains Marcia's response)**:
![image](https://user-images.githubusercontent.com/59668647/131581229-082d45f7-74c9-405c-8afc-477754cd1418.png)

**Comment by lijenn** [comment] 2021-08-31 22:03
**Feature Requests to make finding Activities easier:** 
- Can we use the column filter when were using the "All Activities" view? These look to be greyed out/disabled:
![image](https://user-images.githubusercontent.com/59668647/131581609-76ef67eb-0a90-4466-b83c-ab787ababeb0.png)

- Can we rename the Owner column to be Group/Team instead? 
![image](https://user-images.githubusercontent.com/59668647/131581541-167d0ae9-6475-455a-9be7-c355d6a42610.png)

**Comment by hsnyder2** [comment] 2021-09-03 14:57
@lijenn OK, per our screenshare/call yday, we ID'd that the Email Response Date is working correctly.  It's tagged to the email that was replied to, not the reply.

The routing also worked as designed:  any incoming email to MTLH routes to the sender's most recently assigned team.  Jenn's gmail contact was assigned to the "Jenn4" team between Marcia's last reply and Jenn's response to that, so the final response went to Jenn's new team.  We ID'd two ways to resolve this:  1.  Allow users to reassign the email to the correct team so it shows up on the right "MTL Help Email Tab" and 2.  Train Facilitators to reply to Team emails in D365 ("From" should be MTLH email).  Unfortunately, an error occurs in D365 when Facilitators try to do #2.  Looks like a bug MS will have to troubleshoot as it's not something we have control over.  We've reached out to  them and are awaiting their response.  Currently, the only thing we can do is allow users to change the Team associated emails and have a story for Spr 11 to implement this.

**Comment by lijenn** [comment] 2021-09-07 13:12
Thanks @hsnyder2!

Trying to rejog my memory from the break...let me know if I got this right?

1. For number 2, which is to reply to emails from D365, I actually see the reply button working for some emails, but I assume this is also part of the problem that we're waiting on MS to respond to?
2. Since Facilitators can't always reply from D365 due to issue above, does that mean we should train Facilitators to send emails from Outlook then?
3. And because of the routing issue where if a Facilitator gets mapped to more than 1 group or team, the response to that email will get routed only to the latest group or team they were assigned to, we'll need to use reassign incorrectly routed emails to the right group and team.

**Comment by hsnyder2** [comment] 2021-09-14 15:19
Arlene's completed CR work to route email to teams based on **Tracking Token** stored in email header.  If a **Tracking Token** is not found, then she looks for a matching **Parent Activity ID**.  If a matching **Parent Activity ID** is not found, then she looks for a matching **Conversation ID**.  If a matching **Conversation ID** is not found, then she relies on the senders **latest Team Assignment**.  If a **Team Assignment** for the sender is not found, then the email is only available in email views that are not Team specific (i.e. it has no Team assignment).

**Comment by hsnyder2** [comment] 2021-09-15 15:04
Testing in DEV passed.  Arlene's deploying to QA now.  As soon as she's done with the deployment, I'll retest it there and if it works the same as it did in DEV, I let you know it's ready for you all to test.  *fingers crossed*  If retesting of the routing and fix for #2240 (deployed yesterday) pass today, this would be the version we'd deploy to PROD this week.

**Comment by lijenn** [comment] 2021-09-15 15:56
Got it, thanks @hsnyder2!

**Comment by hsnyder2** [comment] 2021-09-15 17:52
This has been deployed to QA and ready to retest.

**Closed** 2024-03-05 18:08 UTC
Labels: d365, bug, Development, Operations
