### ISSUE TITLE
wk3 oct_epic: ANDON Appointment Supply DAX Code in 3.0 Release of Team (AGG) Care not consistent w/Prior Releases

### ISSUE THREAD

**Issue by dlkibbe** [lzim/teampsd#2743] opened 2022-09-27 20:16 UTC
**1. Add description:** 

Team data in Aggregate Module for blue team needs review and validation. Appointment Supply numbers in Agg module are considerably lower than in the individual modules of Care Coordination (CC), Psychotherapy (Psy) or Medication Management (MM). The team suggested the Appointment Supply (AS) showing in Agg was less than actual. Screenshots for AS for CC, MM, Psy and Agg for comparison of AS numbers. The AS definitions from the "Descriptions" and "Details" section of the Data UI are pasted below for reference:
*DETAILS* in the Data UI indicate: Appointment Supply (median and 75th percentile) – These estimates were calculated from the weekly visit counts by the patient cohort with the team over one year. The model uses the 75th percentile.
*DESCRIPTIONS* in the Data UI indicate: Appointment Supply (median and 75th percentile) – An estimate of the median total weekly number of medication management appointments available with this team. The estimate is calculated using the volume of medication management visits completed with he team over one year. (appt/wk)

Use of data in SIM UI will begin October 17, 2022. 

<< Paste screenshots here>>
<img width="204" alt="AS-CC-Alexandria" src="https://user-images.githubusercontent.com/31182258/192624406-31d433ee-b9aa-4713-9aab-7faceb34f84c.PNG">
<img width="196" alt="AS-Psy-Alexandria" src="https://user-images.githubusercontent.com/31182258/192624421-c23a0434-0368-4bf8-b269-70bbf5597f74.PNG">
<img width="185" alt="AS-MM-Alexandria" src="https://user-images.githubusercontent.com/31182258/192624432-cb04b8b0-cfb4-4180-abbb-1c916ec12336.PNG">
<img width="503" alt="AS-Agg-Alexandria" src="https://user-images.githubusercontent.com/31182258/192624440-91657c40-8e8e-455f-b46a-e1638e72e447.PNG">

1. When was the bug discovered? 
- 9-24-2022 during prep session with Klocek, Nappi, Askerlund, and Kibbe. 
2. Is this an invidivual or shared world? 
- not in SIM UI, Data UI
3. What is the name of the experiment? 
- Not an experiment, Data UI only

**Comment by lzim** [comment] 2022-09-28 00:05
@emilymetcalf114  & @lzim  discussed at **support_workflow** **wk4 sept_epic**

_Next Steps:_
- [ ] Check the time units at https://mtl.how/demo 
- [ ] Check the time units at https://mtl.how/data 
- [x] @lzim reviwed DataNotes w/Emily and doesn't see the Team (AGG) Care Service Arrays in the Data Notes 1 or 2 tab.
- [ ] Identify documentation at https://github.com/lzim/research/tree/master/data_ui

**User Persona**
- [x] SD Modeler - SDM-DOC
- [x] NIH Program Officer - Open Science; Open Standard SDM-DOC 
- [ ] @emilymetcalf114  _Can a typical Team PSD member find the answer to the time units (unit/wk) for appointment supply in this documentation?_

**Comment by emilymetcalf114** [comment] 2022-09-29 16:43
First step: @emilymetcalf114 looked at a comparison _MTL_ blue site (Tuesdays at 11am PST) on the morning on 9/29 and witnessed the same effect, where Agg Care appt supply #'s are lower and do not add up to appt supplies of MM, CC, Psy, etc. 
![image](https://user-images.githubusercontent.com/111393225/193089916-0aa180ce-18ce-4bdf-8a4d-cb4aa637b54a.png)
Psy: 
![image](https://user-images.githubusercontent.com/111393225/193089952-f6ee1827-8566-481d-8ff2-c7454f3ed4fd.png)
![image](https://user-images.githubusercontent.com/111393225/193089970-153390ef-efab-45b7-a72a-d2ffc478a3e6.png)
![image](https://user-images.githubusercontent.com/111393225/193089986-bd1cf2c8-4ee5-4124-b387-31081f6b2563.png)

**Comment by emilymetcalf114** [comment] 2022-09-30 16:38
@emilymetcalf114 compared with another _MTL_ blue site (Thursdays at 11am PST) on 9/30 am and witnessed the same effect, where Agg Care appt supply #'s are lower and do not add up to appt supplies of MM, CC, Psy, etc.

<img width="170" alt="image" src="https://user-images.githubusercontent.com/111393225/193316402-776b60ec-e8c6-4e95-a416-98c0a8934f02.png">
<img width="178" alt="image" src="https://user-images.githubusercontent.com/111393225/193316487-80ea215a-309a-49af-84c8-dbbc5cf75176.png">
Psy:
<img width="167" alt="image" src="https://user-images.githubusercontent.com/111393225/193316536-e86900a0-7691-4e1a-99a6-254f3a4e209c.png">
<img width="596" alt="image" src="https://user-images.githubusercontent.com/111393225/193316866-e013e929-88bc-4f82-b2ca-06ce6e78eb4c.png">

**Comment by emilymetcalf114** [comment] 2022-09-30 17:14
Definitions for appt supply are different between CC, MM, etc. and in the Agg care model. Here are the definitions in the Data_UI: 
CC, MM & Psy: 
<img width="570" alt="image" src="https://user-images.githubusercontent.com/111393225/193318036-7700905b-6647-4293-b106-e427891405b8.png">

Agg Care:
<img width="601" alt="image" src="https://user-images.githubusercontent.com/111393225/193317799-f4cb284a-0d11-4be6-95a4-302f00290d07.png">
<img width="594" alt="image" src="https://user-images.githubusercontent.com/111393225/193318275-110c0b85-0e0d-449f-9b93-b6936b6a0f6f.png">

**Comment by emilymetcalf114** [comment] 2022-09-30 17:56
Documentation from mtl.how/demo: 
- CC (v36 2022_01_10) - time unit = weeks
<img width="552" alt="image" src="https://user-images.githubusercontent.com/111393225/193327273-46782a70-1cce-41dc-99db-ad23d5b98348.png">

- MM (v36 2022_01_11) - time unit = weeks 
<img width="452" alt="image" src="https://user-images.githubusercontent.com/111393225/193327515-215020c3-4eaf-40e2-94f2-b7357ebab377.png">

- Psy (v21 2022_02_11) - time unit = weeks
<img width="547" alt="image" src="https://user-images.githubusercontent.com/111393225/193327877-91fd89fd-a534-4eb2-9dbf-52ecf4e9160a.png">

- Agg Care (v15 **2021_01_20**)  - time unit = weeks
<img width="777" alt="image" src="https://user-images.githubusercontent.com/111393225/193328839-7ab54655-2ea3-4358-b4ac-d727cb4de847.png">
(equation continued)
<img width="539" alt="image" src="https://user-images.githubusercontent.com/111393225/193328591-20eaf5b8-7a6d-4792-9fb0-397f2ca9de5e.png">

**Comment by lzim** [comment] 2022-09-30 18:15
Thanks for reviewing docuementation @emilymetcalf114 💪🏽 
It's very helpful to have it all in one place, and it confirms what I expected was happening.
But, wanted to double-check our documentation.

**In _MTL_ time for these variables will always be in weeks because the clinical decision-makers told us that was the most useful period of time for team care decision.**

**But, for unit checking we have to review and confirm the validity of any unit conversations**: **unit/wk.**
For example, appt/wk is not hrs/wk.

_From the sim_
![image](https://user-images.githubusercontent.com/7454688/193330046-6afa3013-d8a6-4735-9136-4ebef5b441fd.png)

_From your post above_
![image](https://user-images.githubusercontent.com/7454688/193330597-8e0e0e07-15b1-42f0-a3f9-e51bb86d37ad.png)

So, the conclusion is that the documentation needs to be clearer that:

**CC, MM, PSY are using appt/wk for appointment supply (75%ile, etc.) in any given week**
and
**Team (AGG) care is using hrs/wk for appointment supply (see equation from documentation above),** which enables experiments standardized to hrs in Team Care given the services have different lengths.

So, the next step would be:
- [ ] Confirm that the calculation is working as intended between appt/wk and hrs/wk starting with our Monday team.
- [ ] Review our archive in Team PSD > quant_workflow of the highlighted Team (AGG) Care data array information below back in Data Notes in the Data UI (i.e., _MTL 3.0_). Clearly this documentation is not sufficient for facilitators to read it an understand what it is doing.

![image](https://user-images.githubusercontent.com/7454688/193331720-fdb5a42b-ce16-417c-a364-e3911774989a.png)

FYI: @dlkibbe

**Comment by emilymetcalf114** [comment] 2022-09-30 18:35
I pulled up the archived _MTL_ 2.0 data_ui documentation for how Agg **appointment supply** was calculated, and the definition is identical to what we see in the current 3.0 documentation on the data_ui.

**Comment by lzim** [comment] 2022-10-04 03:08
@epearman 
We talked about **Story A2 R01** as a top **research** priority for **oct_epic.**
Once we establish your access, reviewing this **operations** bug would be helpful!

We want to double-check the estimation procedures for appointment supply between (CC, MM, PSY) Care modules and the Team (AGG) Care module.

FYI: @emilymetcalf114

**Comment by epearman** [comment] 2022-10-12 17:19
I see two different things going on. 

1) CPT codes used to define the encounter type in the Agg table (_App.AGGVisitDetails_) Tables. See SQL code [here](https://github.com/lzim/research/blob/master/data_ui/sql_scripts/DataUI_Params_DataRefresh.sql):

- CPT codes 90833 and 90836 are assigned to both encounter type PSY and MM using a CASE WHEN function (line 165). CASE WHEN functions stop evaluating after the first condition is met so all CPT codes 90833 and 90836 are assigned to encounter type PSY and NOT MM. Just want to check that this is what we want. 

    - CASE WHEN cpt.CPTCode in ('90791','90792','99201','99202','99203','99204','99205') THEN 'Intake' WHEN cpt.CPTCode in ('90834','90837','90833','90836') THEN 'PSY' WHEN cpt.CPTCode in ('90853') THEN 'Group' WHEN cpt.CPTCode in ('99212','99213','99214','99215','90833','90836') THEN 'MM' WHEN cpt.CPTCode in ('t1016','90832','90839') THEN 'CC' ELSE 'Adjunct' END AS [EncounterType],

**Comment by dlkibbe** [comment] 2022-10-17 14:15
@emilymetcalf114 @lzim 
Thank you @epearman for the information above. @jwklocek and I shared the information in our team discussion. Questions below from QIICs:

The following are CPT codes for Psychotherapy: 90832, 90834, 90837 (90832 is included in care coordination, although we have certainly seen this used for short session psychotherapy like follow-up CBT-I sessions)
90839 (psychotherapy for crisis - It looks like this is called care coordination as well)
- It is helpful for us to know about these categorization decisions so we can explain them to the site as we could certainly see some of the team wondering why 90832 and 90839 are considered care coordination. 

The couples/ family psychotherapy codes are missing (90846, 90847). Maybe this was intentional, but it could impact extent to which data reflects what is happening given some sites do a fair amount of evidence based couples psychotherapy?

The following are CPT codes for Psychotherapy (add on) when it is conducted with a Medication Management Visit. It seems that if you include these with PSY, it will muddy the waters with Medication Management. It would be helpful to understand why a decision was made to include these in PSY.  
90833
90836
90838

Carla tried clicking on the SQL code link and was sent to a page with an error message indicating page not found so she is unable to assess the CPT codes for Agg Visit Details. 

Can we have explanation of why 99201-99205 are assigned to Intake? Related to intake, it does appear that Intake is capturing codes 90791 and 90792 so it seems strange that data UI TeamAgg for ALX PCT team is showing only 1.25 appt supply yet dataEnc shows them using this code.

**Comment by emilymetcalf114** [comment] 2022-10-17 21:10
During **Live _MTL_ prep session today**, @emilymetcalf114 and @epearman met with facilitators:

Why is intake true missed appt % = 0 for all teams? 
@epearman looked at dax/sql code and saw it was written to be set to 0 (not calculated).

**Comment by lzim** [comment] 2022-10-19 22:31
** @lzim discussed briefly with @emilymetcalf114 @epearman** 
**wk3 oct_epic support_workflow**

- [x] Several of the decisions here have been carefully considered by the team in the past.
- [ ] Cross-ref #2753 documentation issue task card

**Comment by epearman** [comment] 2022-10-20 16:40
Scoping of Bug: 

[ ] Emily P needs access to the DEV, Test, Prod, Environments. 
[ ] Emily P. needs data to populate her data UI? (may be able to develop without this). 
3. Emily needs training on how to develop the Data UI through Dev, Test, Prod 
4. Emily P needs to

**Comment by epearman** [comment] 2022-10-24 18:47
I have made the appropriate DAX code changes on a new personal version of _Data UI - Master_ on power BI desktop. 

Next Steps: 
- [ ] Testing - @lzim at @emilymetcalf114 can I give it a try using [these directions](https://github.com/lzim/research/blob/master/data_ui/PublishingToTEST.md) directions? Is there any automatic syncing between the Test and Production pipeline that I should be aware of or am I free to to upload and test as needed in the testing environment?
- [ ] Publish to production once tested.

**Comment by epearman** [comment] 2022-10-24 23:32
I have hit a wall. I cannot connect my test reports to the PTSD OHMO database through the Gateway connection in the testing pipeline. 

I would like to know if this is an access issue (I see LEAF request has an option for "Add user to gateway") or something else.

- [ ] @lzim @lijenn Do you know anything about this? If not, try following my directions below and see if you get the same gateway connection issue as I do (i.e. no gateways to connect to). 


1.  Navigate to [power bi could](https://app.powerbigov.us/home) and select Deployment pipelines -> PTSD_OHMO Pipeline.![Capture.PNG](https://images.zenhubusercontent.com/63331eaba895626f74a7c3a6/140d3637-ef3e-4b81-a7d8-3713043cd8b6)
2. Under the PTSD_OMO [Test] pipeline, select the three dots to the right of "DatUI - Emily P #2473 VISN 16" and select settings. ![Capture2.png](https://images.zenhubusercontent.com/63331eaba895626f74a7c3a6/347d79ce-5961-4fde-85db-8361b011a151)
3. Scroll down in the setting and expand the "Gateway Connection" setting. See photo below for what I see. See item [5c](https://github.com/lzim/research/blob/master/data_ui/PublishingToTEST.md) in Jeff's directions for a picture of what you should see. 
![Capture3.PNG](https://images.zenhubusercontent.com/63331eaba895626f74a7c3a6/e458120c-926e-471d-bf19-f1693dd9b108)

**Comment by epearman** [comment] 2022-10-25 22:24
The [testing ](https://app.powerbigov.us/groups/me/apps/857e87fb-976f-49b1-b84f-0f5dc8208e7d/reports/504dd198-86aa-40cf-9bfe-1e11ddb566b5/ReportSectionc1400815adc30a7d894a?ctid=e95f1b23-abaf-45ee-821d-b7ab251ab3bf) Pipeline is currently ready for Review. 

- [ ] @emilymetcalf114 review test reports and export data sets for SIM UI 
- [ ] @lzim review impact of new measures in the SIM UI

**Comment by emilymetcalf114** [comment] 2022-10-26 01:01
1st test: Monday Blue _MTL_ live team:
**NEW RESULTS in test Pipeline** followed by OLD results below. 
![image](https://user-images.githubusercontent.com/111393225/197909286-a94130c3-0ebc-4827-b218-9f351d0cfa88.png)


For easy comparison, here are the **OLD Results**
![image](https://user-images.githubusercontent.com/111393225/197906375-ab7f8dcb-566f-4fa5-ace0-cbe63882ff24.png)

@epearman @lzim 
Would you expect several of these to **DECREASE** after the changes that Emily P made? (see CC, MM, Adjunct, and Group) 

File for sim attached: 
[Mon_Blue_MTL_data for sim_TEST.xlsx](https://github.com/lzim/teampsd/files/9865051/Mon_Blue_MTL_data.for.sim_TEST.xlsx)
I can run 2nd test and get data file for Thurs MTL live team tomorrow.

**Comment by emilymetcalf114** [comment] 2022-10-26 14:39
Test #2: Thurs Blue _MTL_ live team: 
**NEW RESULTS in test pipeline** HERE (Followed by OLD results below):
Appointment Supply increased across all services
![image](https://user-images.githubusercontent.com/111393225/198053967-28702061-9732-45dc-918c-f5d65d8aba0b.png)

For easy comparison, here are the **OLD Results**
![image](https://user-images.githubusercontent.com/111393225/198054261-f3907f45-8243-4bcf-894d-24ddc4418d11.png)

@lzim File for sim attached: 
[Thurs_Blue_MTL_data for sim_TEST.xlsx](https://github.com/lzim/teampsd/files/9870537/Thurs_Blue_MTL_data.for.sim_TEST.xlsx)

**Comment by emilymetcalf114** [comment] 2022-10-26 20:51
FYI @epearman 
I updated the clinic selections for the second test (above). The numbers match how we would expect them to now. 

For documentation: 

- [ ] It was not adequate to compare the new code in the test environment to our previous screen shots of Agg Care data from over a month ago (see beginning of this issue card), because the cohort has been refreshed
- [ ] To test the new code in the test environment, it required both aligning clinic selections in the test and prod environments for both live teams, and producing new screen shots of Agg care in both TEST and PROD environments. 

Next Steps:

- [ ] upload data files to sim shared environments for further testing.

**Comment by emilymetcalf114** [comment] 2022-10-26 22:31
@lzim 
The new test data file for Thursday's _MTL_ live session prep tomorrow has been uploaded to the sim for you.

**Comment by lzim** [comment] 2022-10-27 17:50
@epearman 
_Can you check off any functional requirement or task list boxes above that you believe are done from all the updates above?_
_Or is this current?_

It looks like we might be ready to move on to #2753 and #2509
💥

**Comment by epearman** [comment] 2022-10-27 18:31
Crossref #2764  QA Test Card.

**Comment by epearman** [comment] 2022-10-27 18:40
@lzim @emilymetcalf114 

- should I push the minimal viable product to production? (i.e. the new data UIs with updated appointment supply calculations for Monday Blue MTL live team and Thurs Blue MTL live team)? Will these sites be needing the Data UI next week?

**Comment by lzim** [comment] 2022-10-27 19:03
@epearman 
Testing in the Sim UI now and will update#2764 QA Test Card when done.

**Comment by epearman** [comment] 2022-11-03 18:34
This issue has been closed: 
- Any remaining functional requirements related to this ANDON are listed in the Training card crossref #2775.
- Production role of these changes across all VISN is tracked in crossref [455](https://app.zenhub.com/workspaces/team-psd-workspace-5e4ac9bd8d388dfba6d9aef5/issues/lzim/research/455).

**Closed** 2022-11-14 20:44 UTC
Labels: facilitate, bug

**Comment by lijenn** [comment] 2026-02-27 20:13
wk4 2026_02 #quant_workflow @power_bi
@lzim 
@jeffhoerle
@hnorthcraft 
@kmacia 
@lijenn 

We confirmed that all 'appointment supply (median)' calculations (1) follow legacy code rules and (2) were fixed in the DAX Code in the latest DataUI - Master from 2/26/2026 as a part [lzim/research/#1286](https://github.com/lzim/research/issues/1286).

- [x] Intake
- [x] CC
- [x] MM
- [x] Psy
- [x] EBPsy
- [x] Group
- [x] Adjunct

> This varies from the [legacy code](https://github.com/lzim/research/blob/master/data_ui/sql_scripts/Legacy_AGGParams.sql) line 264, which follows the array documented: select 'Appointment Supply (median)' as Label, [Intake] as intake, [psy] as psy, [ebpsy] as ebpsy, [cc]*0.5 as cc, [mm]*0.5 as mm , [adjunct]*0.25 as adjunct, ([group]*1.0/6) as 'group'
