### ISSUE TITLE
wk3 jul_epic URGENT BUG: Facility File - Missing Data in HF tab ends in April 2021

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2115] opened 2021-07-07 18:59 UTC
Discussed at Thurs. 7/7 Quant WG at 11am Pacific:

@anazariz to look into why some data in the HF tabs end in April 2021 in the Facility file.

Please provide an estimate on the card once you're able to.

**Comment by anazariz** [comment] 2021-07-07 22:24
I ran several queries on the backend (database) to see if there's any data missing. I did see a missing month.
Since all 4 tables HF, Diag, Meas and Enc are in the same monthly update. I decided to rerun May and June.
I see see some slight changes in some of the record counts. Not sure why. 

Here are the results of the initial queries. 

**HF**

after rerun
YEAR	MONTH	COUNT
2021	4	3611831
2021	5	3272636
2021	6	3516208

before rerun
YEAR	MONTH	COUNT
2021	4	3611831
2021	5	3271802
2021	6	3495898

**Meas**

after rerun
YEAR	MONTH	COUNT
2021	4	604727
2021	5	720932
2021	6	758294

before rerun
YEAR	MONTH	COUNT
2021	4	604727
missing month 
2021	6	681492

**Diag**

after rerun
YEAR	MONTH	COUNT
2021	4	1448063
2021	5	1353570
2021	6	1442238

before rerun
YEAR	MONTH	COUNT
2021	4	1448063
2021	5	1353363
2021	6	1431491

**Enc**
after rerun
YEAR	MONTH	COUNT
2021	4	1728472
2021	5	1618299
2021	6	1729938

before rerun
YEAR	MONTH	COUNT
2021	4	1728472
2021	5	1618161
2021	6	1717930

**Comment by anazariz** [comment] 2021-07-08 00:10
I ran this simple query on the backend.
 
select
   tmp.patientsid
  ,tmp.visitsid
  ,tmp.DivisionName
  ,tmp.locationname
  ,tmp.visitdatetime
  ,tmp.HealthFactorCategory
  ,tmp.HealthFactorType
  ,EBPtemplate
  ,EBPinitiate
  ,[Encounter Type]
  ,sta3n
from 
   ptsd_omho.splash.SplashSourceHF tmp
where 
          tmp.VisitDateTime >= '2021-5-1'
   and HealthFactorCategory = 'MH PEI Templates'
   
It seems like certain Facilities have this data and some Facilities don't (post the above date),
If this was universal, then it would mean that the process is filtering certain  HealthFactorCategories after '2021-5-1'. But the fact that certain facilities do show data in the vizHF shows that something may be going on the the CDW side.

**Comment by staceypark** [comment] 2021-07-12 16:43
7/12 wg leads
@anazariz did you submit the YourIT helpdesk ticket for what you assessed to be a CDW issue? As a reminder, please put it into teampsd > help_desk_tickets once you do

@staceypark will crosswalk facilities with missing HF data with Cerner rollout sites

**Comment by anazariz** [comment] 2021-07-15 21:53
This issue is fixed.

**Comment by lzim** [comment] 2021-07-16 21:07
@anazariz discussed in quant_operations on 7/15 and discussed this issue on the Teams quant_workgroup channel on 7/16. 

 - [ ] 1a.  Explain below your reference on Teams thread for a need for a fuzzy rather than exact query. It is unclear why any changes would have been made to the facility file propagation query that would result in dropping April and May health factor data for some facilities, but not others.
 
 - [ ] 1b.  Describe below the quality assurance steps that you have taken to address this issue.
 
 - [ ] 1c.  Document in the "Splashpage_monthly_update_readme.docx" file how a Team PSD member can determine which SQL files and CDW tables are used in the facility file propagation routine.

**Comment by lzim** [comment] 2021-07-16 22:38
On Teams quant_workgroup channel 7/16 @anazariz confirmed that he can reproduce missing HF data for April & May using the April, May and newest Power BI version of the facility file.

**Comment by lzim** [comment] 2021-07-16 22:49
As a result of taking all these finding together ruling out any missing CDW data, any Excel explanations, or any facility file propagation or query changes, it makes sense to me that the problem is likely to be in any dependent tables that are hard for Team PSD member to assist with reviewing - **_Cross-ref Story 2!_**

@anazariz @lijenn @staceypark @dkngenda

**Comment by lzim** [comment] 2021-07-20 14:18
@anazariz 

Let us know as soon as you have an update on #2115 #2126 or #2127 this morning, since one of the co-planning meetings is first thing tomorrow. Thanks!

@lijenn & @staceypark As a fall-back we will want to queue up a Data UI for the two co-planning meetings with Matt, so that we can use this if the facility file bugs are not squashed in time.

**Comment by anazariz** [comment] 2021-07-21 00:04
The existing code in the Facility workbook, when resetting the filter on the vizHf had a bug. It was hard-coded like this:

'str = ActiveChart.PivotLayout.PivotTable.PivotFields("[dataHF].[healthfactorcategory].[healthfactorcategory]").PivotItems("[dataHF].[healthfactorcategory].&[REACH VET]")
'str = str & "," & ActiveChart.PivotLayout.PivotTable.PivotFields("[dataHF].[healthfactorcategory].[healthfactorcategory]").PivotItems("[dataHF].[healthfactorcategory].&[MH ACT TEMPLATES (ACCEPT & COMMITMENT)]")
'str = str & "," & ActiveChart.PivotLayout.PivotTable.PivotFields("[dataHF].[healthfactorcategory].[healthfactorcategory]").PivotItems("[dataHF].[healthfactorcategory].&[MH CBT-D TEMPLATES (COG BEHAVIORAL)]")
'str = str & "," & ActiveChart.PivotLayout.PivotTable.PivotFields("[dataHF].[healthfactorcategory].[healthfactorcategory]").PivotItems("[dataHF].[healthfactorcategory].&[MH CPT TEMPLATES (COGNITIVE PROCESSING)]")
'str = str & "," & ActiveChart.PivotLayout.PivotTable.PivotFields("[dataHF].[healthfactorcategory].[healthfactorcategory]").PivotItems("[dataHF].[healthfactorcategory].&[MH IBCT TEMPLATES]")
'str = str & "," & ActiveChart.PivotLayout.PivotTable.PivotFields("[dataHF].[healthfactorcategory].[healthfactorcategory]").PivotItems("[dataHF].[healthfactorcategory].&[MH IPT FOR DEPRESSION]")
'str = str & "," & ActiveChart.PivotLayout.PivotTable.PivotFields("[dataHF].[healthfactorcategory].[healthfactorcategory]").PivotItems("[dataHF].[healthfactorcategory].&[MH PEI TEMPLATES]")
'str = str & "," & ActiveChart.PivotLayout.PivotTable.PivotFields("[dataHF].[healthfactorcategory].[healthfactorcategory]").PivotItems("[dataHF].[healthfactorcategory].&[OPIOID ASSESS]")
'str = str & "," & ActiveChart.PivotLayout.PivotTable.PivotFields("[dataHF].[healthfactorcategory].[healthfactorcategory]").PivotItems("[dataHF].[healthfactorcategory].&[PBM PHARMD MH DEPRESSION MED]")
'str = str & "," & ActiveChart.PivotLayout.PivotTable.PivotFields("[dataHF].[healthfactorcategory].[healthfactorcategory]").PivotItems("[dataHF].[healthfactorcategory].&[PBM PHARMD MH SUBST ABUSE MED]")
'str = str & "," & ActiveChart.PivotLayout.PivotTable.PivotFields("[dataHF].[healthfactorcategory].[healthfactorcategory]").PivotItems("[dataHF].[healthfactorcategory].&[SUICIDE RISK SCREEN]")
'str = str & "," & ActiveChart.PivotLayout.PivotTable.PivotFields("[dataHF].[healthfactorcategory].[healthfactorcategory]").PivotItems("[dataHF].[healthfactorcategory].&[SUICIDE SAFETY PLAN REVIEW]")
'str = str & "," & ActiveChart.PivotLayout.PivotTable.PivotFields("[dataHF].[healthfactorcategory].[healthfactorcategory]").PivotItems("[dataHF].[healthfactorcategory].&[VA-SUICIDE PROTECTIVE FACTORS [C]]]")
'str = str & "," & ActiveChart.PivotLayout.PivotTable.PivotFields("[dataHF].[healthfactorcategory].[healthfactorcategory]").PivotItems("[dataHF].[healthfactorcategory].&[VA-SUICIDE RISK ASSESSMENT [C]]]")
'str = str & "," & ActiveChart.PivotLayout.PivotTable.PivotFields("[dataHF].[healthfactorcategory].[healthfactorcategory]").PivotItems("[dataHF].[healthfactorcategory].&[VA-SUICIDE RISK EVALUATION TYPE [C]]]")
'str = str & "," & ActiveChart.PivotLayout.PivotTable.PivotFields("[dataHF].[healthfactorcategory].[healthfactorcategory]").PivotItems("[dataHF].[healthfactorcategory].&[VA-SUICIDE RISK FACTORS [C]]]")
'str = str & "," & ActiveChart.PivotLayout.PivotTable.PivotFields("[dataHF].[healthfactorcategory].[healthfactorcategory]").PivotItems("[dataHF].[healthfactorcategory].&[VA-SUICIDE SAFETY PLAN]")

This caused problems because it assumes that all the values in the filter (in this case healthfactorcategory) are always there. 
But that is not so. The filters are dynamic and come from the vizData (in this case). So if the filter is not in the data (and the Pivot table) it causes an error.  
There was no error catching in the code so the error would go silent. 

*************************************************************

I fixed this issue by making the code dynamic.

First = True
str = ""
For Each pvtField In ActiveChart.PivotLayout.PivotTable.PivotFields
   If pvtField.Name = "[dataHF].[healthfactorcategory].[healthfactorcategory]" Then
      For Each pvtItem In pvtField.PivotItems
         
         Field = "[dataHF].[healthfactorcategory].&[REACH VET]"
         If pvtItem.Name = Field Then
            If First = True Then
               First = False
               str = str & ActiveChart.PivotLayout.PivotTable.PivotFields(pvtField.Name).PivotItems(Field)
            Else
               str = str & "," & ActiveChart.PivotLayout.PivotTable.PivotFields(pvtField.Name).PivotItems(Field)
            End If
         End If
         Field = "[dataHF].[healthfactorcategory].&[MH ACT TEMPLATES (ACCEPT & COMMITMENT)]"
         If pvtItem.Name = Field Then
            If First = True Then
               First = False
               str = str & ActiveChart.PivotLayout.PivotTable.PivotFields(pvtField.Name).PivotItems(Field)
            Else
               str = str & "," & ActiveChart.PivotLayout.PivotTable.PivotFields(pvtField.Name).PivotItems(Field)
            End If
         End If
         Field = "[dataHF].[healthfactorcategory].&[MH CBT-D TEMPLATES (COG BEHAVIORAL)]"
         If pvtItem.Name = Field Then
            If First = True Then
               First = False
               str = str & ActiveChart.PivotLayout.PivotTable.PivotFields(pvtField.Name).PivotItems(Field)
            Else
               str = str & "," & ActiveChart.PivotLayout.PivotTable.PivotFields(pvtField.Name).PivotItems(Field)
            End If
         End If
         Field = "[dataHF].[healthfactorcategory].&[MH CPT TEMPLATES (COGNITIVE PROCESSING)]"
         If pvtItem.Name = Field Then
            If First = True Then
               First = False
               str = str & ActiveChart.PivotLayout.PivotTable.PivotFields(pvtField.Name).PivotItems(Field)
            Else
               str = str & "," & ActiveChart.PivotLayout.PivotTable.PivotFields(pvtField.Name).PivotItems(Field)
            End If
         End If
         Field = "[dataHF].[healthfactorcategory].&[MH IBCT TEMPLATES]"
         If pvtItem.Name = Field Then
            If First = True Then
               First = False
               str = str & ActiveChart.PivotLayout.PivotTable.PivotFields(pvtField.Name).PivotItems(Field)
            Else
               str = str & "," & ActiveChart.PivotLayout.PivotTable.PivotFields(pvtField.Name).PivotItems(Field)
           End If
         End If
         Field = "[dataHF].[healthfactorcategory].&[MH IPT FOR DEPRESSION]"
         If pvtItem.Name = Field Then
            If First = True Then
               First = False
               str = str & ActiveChart.PivotLayout.PivotTable.PivotFields(pvtField.Name).PivotItems(Field)
            Else
               str = str & "," & ActiveChart.PivotLayout.PivotTable.PivotFields(pvtField.Name).PivotItems(Field)
            End If
         End If
         Field = "[dataHF].[healthfactorcategory].&[MH PEI TEMPLATES]"
         If pvtItem.Name = Field Then
            If First = True Then
               First = False
               str = str & ActiveChart.PivotLayout.PivotTable.PivotFields(pvtField.Name).PivotItems(Field)
            Else
               str = str & "," & ActiveChart.PivotLayout.PivotTable.PivotFields(pvtField.Name).PivotItems(Field)
            End If
         End If
         Field = "[dataHF].[healthfactorcategory].&[OPIOID ASSESS]"
        If pvtItem.Name = Field Then
            If First = True Then
               First = False
               str = str & ActiveChart.PivotLayout.PivotTable.PivotFields(pvtField.Name).PivotItems(Field)
            Else
               str = str & "," & ActiveChart.PivotLayout.PivotTable.PivotFields(pvtField.Name).PivotItems(Field)
            End If
         End If
         Field = "[dataHF].[healthfactorcategory].&[PBM PHARMD MH DEPRESSION MED]"
         If pvtItem.Name = Field Then
            If First = True Then
               First = False
               str = str & ActiveChart.PivotLayout.PivotTable.PivotFields(pvtField.Name).PivotItems(Field)
            Else
               str = str & "," & ActiveChart.PivotLayout.PivotTable.PivotFields(pvtField.Name).PivotItems(Field)
            End If
         End If
         Field = "[dataHF].[healthfactorcategory].&[PBM PHARMD MH SUBST ABUSE MED]"
         If pvtItem.Name = Field Then
            If First = True Then
               First = False
               str = str & ActiveChart.PivotLayout.PivotTable.PivotFields(pvtField.Name).PivotItems(Field)
            Else
               str = str & "," & ActiveChart.PivotLayout.PivotTable.PivotFields(pvtField.Name).PivotItems(Field)
            End If
         End If
         Field = "[dataHF].[healthfactorcategory].&[SUICIDE RISK SCREEN]"
         If pvtItem.Name = Field Then
            If First = True Then
               First = False
               str = str & ActiveChart.PivotLayout.PivotTable.PivotFields(pvtField.Name).PivotItems(Field)
            Else
               str = str & "," & ActiveChart.PivotLayout.PivotTable.PivotFields(pvtField.Name).PivotItems(Field)
            End If
         End If
         Field = "[dataHF].[healthfactorcategory].&[SUICIDE SAFETY PLAN REVIEW]"
         If pvtItem.Name = Field Then
            If First = True Then
               First = False
               str = str & ActiveChart.PivotLayout.PivotTable.PivotFields(pvtField.Name).PivotItems(Field)
            Else
               str = str & "," & ActiveChart.PivotLayout.PivotTable.PivotFields(pvtField.Name).PivotItems(Field)
            End If
         End If
         Field = "[dataHF].[healthfactorcategory].&[VA-SUICIDE PROTECTIVE FACTORS [C]]]"
         If pvtItem.Name = Field Then
            If First = True Then
               First = False
               str = str & ActiveChart.PivotLayout.PivotTable.PivotFields(pvtField.Name).PivotItems(Field)
            Else
               str = str & "," & ActiveChart.PivotLayout.PivotTable.PivotFields(pvtField.Name).PivotItems(Field)
            End If
         End If
         Field = "[dataHF].[healthfactorcategory].&[VA-SUICIDE RISK ASSESSMENT [C]]]"
         If pvtItem.Name = Field Then
            If First = True Then
               First = False
               str = str & ActiveChart.PivotLayout.PivotTable.PivotFields(pvtField.Name).PivotItems(Field)
            Else
               str = str & "," & ActiveChart.PivotLayout.PivotTable.PivotFields(pvtField.Name).PivotItems(Field)
            End If
         End If
         Field = "[dataHF].[healthfactorcategory].&[VA-SUICIDE RISK EVALUATION TYPE [C]]]"
         If pvtItem.Name = Field Then
            If First = True Then
               First = False
               str = str & ActiveChart.PivotLayout.PivotTable.PivotFields(pvtField.Name).PivotItems(Field)
            Else
               str = str & "," & ActiveChart.PivotLayout.PivotTable.PivotFields(pvtField.Name).PivotItems(Field)
            End If
         End If
         Field = "[dataHF].[healthfactorcategory].&[VA-SUICIDE RISK FACTORS [C]]]"
         If pvtItem.Name = Field Then
            If First = True Then
               First = False
               str = str & ActiveChart.PivotLayout.PivotTable.PivotFields(pvtField.Name).PivotItems(Field)
            Else
               str = str & "," & ActiveChart.PivotLayout.PivotTable.PivotFields(pvtField.Name).PivotItems(Field)
            End If
         End If
         Field = "[dataHF].[healthfactorcategory].&[VA-SUICIDE SAFETY PLAN]"
         If pvtItem.Name = Field Then
            If First = True Then
               First = False
               str = str & ActiveChart.PivotLayout.PivotTable.PivotFields(pvtField.Name).PivotItems(Field)
            Else
               str = str & "," & ActiveChart.PivotLayout.PivotTable.PivotFields(pvtField.Name).PivotItems(Field)
            End If
         End If
      
      Next pvtItem
   End If
Next pvtField
   
I then ran some queries to see if this fixed the 2115 issue. 

As seen in this screenshot the issue still exists. .

![image](https://user-images.githubusercontent.com/39805164/126406085-02dc44ab-6ff6-4514-a421-7d35b62fd83f.png)

I then focused on  Two. One filter with cutoff and one without. 

![image](https://user-images.githubusercontent.com/39805164/126407107-11cc9b55-b3cc-46fd-ade7-70b0ec3c6a3b.png)

**I ran the following query MH CPT-D TEMPLATES (COGNITIVE BEHAVIORAL)** 
Shows null values.

SELECT 
   Count(*) [MH CPT TEMPLATES (COGNITIVE PROCESSING) MAY counts]
FROM
(
SELECT DISTINCT 
  visitSID
FROM 
   ptsd_omho.splash.SplashSourceHF 
WHERE 
       sta3n in ('589')
   AND YEAR(VisitDateTime) = 2021 
   AND MONTH(VisitDateTime) = 5 
   AND TRIM(HealthFactorCategory) = 'MH CPT-D TEMPLATES (COGNITIVE BEHAVIORAL)'
) T1
--0

SELECT 
   Count(*) [MH CPT TEMPLATES (COGNITIVE PROCESSING) MAY counts]
FROM
(
SELECT DISTINCT 
  visitSID
FROM 
   ptsd_omho.splash.SplashSourceHF 
WHERE 
       sta3n in ('589')
   AND YEAR(VisitDateTime) = 2021 
   AND MONTH(VisitDateTime) = 6 
   AND TRIM(HealthFactorCategory) = 'MH CPT-D TEMPLATES (COGNITIVE BEHAVIORAL)'
) T1
--0

**Comment by lzim** [comment] 2021-07-21 01:13
@anazariz @staceypark @lzim & @lijenn meet to review Ash's progress on this bug on 7/20/21.

- Ash is still not sure what is causing the issue of missing HF values for May June in vizHF tab of the **facility.xlsb** file.

_**Recommendation**_ based on the fact that @lijenn was able to query the co-planning facility for tomorrow's 9AM meeting using the **Data UI.xlsm** complete with the May & June HF data ( _Note:_ This has been a consistent finding that the Data UI displays May & June values even when the facility file does not).
- Review the carefully the differences in how these data are pulled, especially since Ash was finding discrepencies between his queries & the facility.xlsb for some HF values.

**Comment by dkngenda** [comment] 2021-07-22 21:39
Ash has set a test environment for David to start training. Ash has oriented David to the testing environment

**Comment by lzim** [comment] 2021-08-03 20:19
As discussed at **team_time** and **facilitate_workgroup**

@staceypark and @lijenn are preparing and permissioning the Data UI on Sharepoint Online at https://mtl.how/data
We will continue with this approach and forego the facility file for now, as this bug was never squashed and we're prioritizing **Story 13 #2112 #1961**

_Future Directions_: **quant_workgroup** taking the production of data and QA for data back over. 

We'll close this issue for now - A **new issue task card #2157** to make the **edits in SEE & SAY guides.**
Note: **#2119 describes guide edits for Autosave** that apply across the _MTL_ guides, cheatsheets & manuals.

- [ ] _MTL_ Red part 1 SEE/SAY
- [ ] _MTL_ Blue session 2 SEE/SAY
- [ ] _MTL_ Data Cheatsheet

_We'll review #2157 & #2119 on Thursday at hq_workgroup_

**Closed by lzim** 2021-08-03 20:19 UTC
Labels: quant, urgent
