### ISSUE TITLE
wk1 jun_epic  #mm story_1: Model manuscript walkthrough of systems stories for SP

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1511] opened 2020-10-07 00:07 UTC
Write out systems story walkthrough for SP model to submit in manuscript

**Comment by lijenn** [comment] 2020-10-15 15:25
Hi @branscombj! Let us know how this is going or if there's any difficulty with this one specifically?
FYI @lzim @staceypark

**Comment by branscombj** [comment] 2020-10-15 15:47
SP - in the main view, Effects of Measurement Based Stepped Care on Patients’ Symptoms and Risk
- [ ] Higher care quality improves recovery - **I cannot trace a feedback loop for this in this diagram view. I wonder if the loop label should be removed from it.**

SP- in the view, Specialty mental health stepped care
- [ ] Overwork and burnout reduce care quality (R)
- [ ] Work pressure delays care decisions (R)
- [ ] Access pressure increases starts (B)
- [ ] Work pressure reduces access (B)
- [ ] Higher care quality improves recovery (R)

**Comment by lzim** [comment] 2020-10-15 16:45
@branscombj 

It’s true for “Higher Care Quality Improves Recovery” I believe you have to toggle between views to fully trace this story. I’m not sure what the best way is to note it in the diagram or describe it in a systems story using what’s there now (or whether removing the label in one place makes it clearer).

FYI: 
@TomRust 
@staceypark 
@lijenn 
@jamesmrollins

**Comment by branscombj** [comment] 2020-10-16 17:33
Re the loop called R:Overwork and Burnout Reduce Care Quality:
It looks like the loop label refers to the light blue loop immediately around it: GMH Patient Load -> GMH Effect of Patient Load on Manageable Total Patients -> GMH Manageable Total Patients -> GMH Patient Load. But that a) reads by the +- signs as a Balancing loop and b) I don't see how it incorporates Care Quality within the loop.

![image](https://user-images.githubusercontent.com/29778290/96288030-c6dd8880-0fb0-11eb-92fd-02632c0e23d0.png)

**Comment by branscombj** [comment] 2020-10-16 17:47
> Hi @branscombj! Let us know how this is going or if there's any difficulty with this one specifically?
> FYI @lzim @staceypark

Yes I'm really struggling with SP. I watched the video for S06-SP and it helped, but I think capturing the feedback stories for this model would benefit from dialoging through it with Lindsey or Tom.

**Comment by branscombj** [comment] 2020-10-16 17:51
BTW (@staceypark @lijenn ?) I watched MTL videos s06SP from the link here https://github.com/lzim/mtl - i.e.  https://players.brightcove.net/2851863979001/default_default/index.html?videoId=6115633697001
and noticed it has captions by default. I wonder if it could be an option to include them. The video's visuals are complex enough with what the presenters are doing/showing and the pop-up messages, so the text is probably more distracting than helpful for anyone who can hear the audio.

**Comment by staceypark** [comment] 2020-10-16 19:15
@lijenn  can you check with EES? Perhaps this is due to accessibility concerns though 

> BTW (@staceypark @lijenn ?) I watched MTL videos s06SP from the link here https://github.com/lzim/mtl - i.e. https://players.brightcove.net/2851863979001/default_default/index.html?videoId=6115633697001
> and noticed it has captions by default. I wonder if it could be an option to include them. The video's visuals are complex enough with what the presenters are doing/showing and the pop-up messages, so the text is probably more distracting than helpful for anyone who can hear the audio.

**Comment by dlounsbu** [comment] 2020-10-21 18:28
@branscombj 

Today I met with the Qualitative Workgroup today (Katherine, Jesslyn, Lindsey, Swap, me). We are making very good progress with the R21 Fidelity paper, which will report on our early MLT co-facilitation experiences. We are coding for BOTH ‘participatory learning’ and ‘systems thinking.’

We created an Excel spreadsheet that is organized around ‘Levels of systems thinking’ for each MLT module (CC, MM, PSY, and AGG) but not for SP!! Actually, we did not have an SP module when we first build this codebook. 

Would you be able to help me describe these ‘levels of systems thinking’ in the context of SP? 

We would simply need to add a row to the bottom of the spreadsheet. 

Lindsey referred me to this issue (1511).  I am going to send you an e-mail about this, with the Excel spreadsheet I refer to in this comment. 

THANKS!

**Comment by branscombj** [comment] 2020-10-21 19:44
Hi @dlounsbu - Unfortunately, I am having trouble sussing out the systems stories in SP - have never gotten facile at connecting across the zooms in/out. I am hoping for a tutorial from @TomRust , which I imagine some others will be interested in as well.

**Comment by dlounsbu** [comment] 2020-10-21 19:52
No worries. Okay. A tutorial session with Tom would be very useful. It think the fundamental systems story is about how to manage 'stepping up' to specialty MH care and 'stepping down' to general MH care. Something like that.

**Comment by lijenn** [comment] 2020-10-22 15:25
FYI, EES confirmed we can't have MTL videos on Brightcove with captions default to Off since this would affect all the other EES Brightcove videos and 508 accessibility compliance. 
We could make a note (I'm guessing it'd have to be in the lzim/mtl readme) to let viewers know they can turn off captions if they prefer.

**Comment by lzim** [comment] 2020-10-23 03:40
@lijenn - Yes, instructions on how to turn the captions on/off would be great to add.

@branscombj and @dlounsbu Thanks. I've asked @TomRust if he can take a look at the questions you have.

If you scroll down at the link below, would the HSRD CyberSeminar Series videos here be helpful for your questions about the SP system stories?

http://lindseyzimmerman.com/videos/

**Comment by TomRust** [comment] 2020-10-28 20:09
Hi @branscombj and @dlounsbu !  It's been a minute, huh?  I hope you are both adapting well, as _thriving_ seems like a particularly high bar these last couple of months.  

I'd be happy to talk about SP.   I'll also carve out some time this week to write down some loop descriptions here, too.

**Comment by lzim** [comment] 2020-10-29 03:08
Thanks @TomRust!!

**Comment by TomRust** [comment] 2020-11-06 17:22
Overwork and Burnout Reduce Quality of Care:  
If a setting suddenly starts taking on more patients than usual, then the patient load (the ratio of the total number of patients seen in GMH over the manageable total patients -- i.e., demand over supply) increases. Without any changes to the "supply," this imbalance will cause the providers in that setting to have more work and be more stressed than usual.  These long hours and stress are unsustainable, and eventually lead to fatigue, which causes providers to take more sick time, reduces their productivity, and, if not relieved, will eventually will lead to burnout and providers quitting.  All of these factors reduce the capacity to provide care, so the the hypothetical number of patients who can be seen with the desired quality and access declines (i.e., reduces the Manageable Total Patients).   When that happens, it reduces the "supply" part of the Patient Load ratio, causing a further increase in the overall ratio.  Without intervention, this pattern of behavior would continue, further reinforcing any initial change

**Comment by TomRust** [comment] 2020-11-10 16:58
@branscombj -- is this (above) what you're looking for?

**Comment by branscombj** [comment] 2021-01-02 17:46
> Overwork and Burnout Reduce Quality of Care:
> If a setting suddenly starts taking on more patients than usual, then the patient load (the ratio of the total number of patients seen in GMH over the manageable total patients -- i.e., demand over supply) increases. Without any changes to the "supply," this imbalance will cause the providers in that setting to have more work and be more stressed than usual. These long hours and stress are unsustainable, and eventually lead to fatigue, which causes providers to take more sick time, reduces their productivity, and, if not relieved, will eventually will lead to burnout and providers quitting. All of these factors reduce the capacity to provide care, so the the hypothetical number of patients who can be seen with the desired quality and access declines (i.e., reduces the Manageable Total Patients). When that happens, it reduces the "supply" part of the Patient Load ratio, causing a further increase in the overall ratio. Without intervention, this pattern of behavior would continue, further reinforcing any initial change

Finally delving into this. Yes! Your narrative brings in some implicit variables and makes great sense, @TomRust - Thank you! One question that remains for me is whether the loop should be named differently since, as depicted, this part of the story does not incorporate the actual variable named Care Quality. See suggestion below, along with my retelling of what you described.

For my purposes, I'm calling Manageable Total Patients by the name Manageable Care Capacity. I'm not necessarily suggesting we go changing it - it just helped me to think of it this way. Because we're talking about patients and not appointments, the concept of _capacity_ fits better to me than _supply_. 

I also wonder if clinicians might be confused by our using the term Load as dimensionless. Don't they consider Load to be their total number of patients in care instead of the number in care relative to what they can handle? I'm throwing in the concept of _experienced_ load, trying to get at the ratio aspect. Would be interested in thoughts from Psy SMEs on this.

**GMH Patient Load Affects Manageable Care Capacity:** Patient Load is the team’s collective experience of total number of patients in care relative the total number to whom they can sustainably provide quality care – what we call their Manageable Care Capacity. 

An unbalanced Patient Load influences the team’s Manageable Care Capacity, which in turn affects Patient Load in a vicious or virtuous cycle. 

For example, if Patient Load increases through a rise in the total number of Patients in Care without a corresponding increase in Manageable Care Capacity, this imbalance will drive down the team’s Manageable Care Capacity by increasing providers’ stress and causing them to work longer hours and/or shortcut quality, leading to fatigue, dissatisfaction, burnout, and ultimately some quitting. With Manageable Care Capacity dropping, the overall Patient Load further increases – even without further increases in the number of Patients in Care – causing a downward spiral in Manageable Care Capacity. 

The reverse is also true: If the number of Patients in Care drops without a corresponding drop in Manageable Care Capacity, this reduction in the team’s Patient Load gives providers more ease and more time to provide quality care, resulting in greater satisfaction and staff retention. This increases the team’s Manageable Care Capacity, further driving down its experienced Patient Load. 

Each of these dynamics has limits. Patient Load can only rise so high before the team either is able to increase its Manageable Care Capacity by bringing in new staff, or to reduce its Patients in Care by referring some to outside providers or limiting its new patient intakes and allowing attrition to patients in care through completion of treatment and graduation from care. Likewise, Patient Load can only drop so far before the team either determines that it is overstaffed and reassigns some providers, or takes on greater patient load through expanded referral sources. 

[How are these limits accounted for in the model; and do we need to address how this loop is actually a balancing loop over the longer term?]

@lzim @dlounsbu - Your thoughts??

**Comment by dlounsbu** [comment] 2021-01-11 19:26
Higher Care Quality Improves Recovery:
If patient load (the ratio of the total number of patients seen in GMH over the manageable total patients; i.e., demand over supply) decreases, the capacity of the providers to provide High Care Quality will increase. This allows providers to better manage work-related stress. . . . .

which, in turn, increases Manageable Total Patients. Increases in Manageable Total Patients will help providers delivery Higher Care Quality, which will shortens (improves) recovery time. 

[still working on this]

**Comment by branscombj** [comment] 2021-12-14 19:13
### Higher Care Quality Improves Recovery
_This loop works the same for any of the three care settings: GMH, PC/PCMHI, and SMH_

As the team **increases** Care Quality, their Time to Unflag High Risk Patients **decreases**. This means the High Risk Patient Unflag Rate **increases**, more quickly **lowering** the total number of High Risk Flag Patients they have in care. This **reduces** their Patient Load (expand inset diagram to see this), enabling further **increase** in Care Quality.

**Comment by branscombj** [comment] 2021-12-14 19:32
> for “Higher Care Quality Improves Recovery” you have to toggle between views to fully trace this story
> FYI: @TomRust @staceypark @lijenn @jamesmrollins @lzim 

<img width="346" alt="image" src="https://user-images.githubusercontent.com/29778290/146064573-8bcf7ffc-2e29-4564-a15c-bf98dd72a552.png">

Please help me see what I'm missing: It seems to me like there could be a full loop within this view: Make Patient Load a regular variable and add a + causal arrow to it from High Risk Flag Patients (although the "i" says it's totally new patients)? I also wonder if it would be clearer to show the referral rate variables as regular gauges in this view and then have the toggle-out option downstream from that? For some reason my gut likes to have the anchor between diagrams be a stock - but there's probably a SD convention and I'm sure @TomRust knows what's correct.

**Closed** 2024-03-28 23:33 UTC
Labels: co-i_manuscript
