### ISSUE TITLE
Small Sim UI bugs/typos

### ISSUE THREAD

**Issue by branscombj** [lzim/teampsd#249] opened 2018-10-29 19:20 UTC
Appointments for Existing Patients
On the diagram in PSY it's labeled "appiontments".

**Comment by jamesmrollins** [comment] 2018-11-06 06:18
@branscombj @staceypark I have reported these two findings to DEV.  I am assuming the issue with Service Proportions from Team Data was in the AGG model.  Thanks James

**Comment by jamesmrollins** [comment] 2018-11-06 06:43
@branscombj @staceypark  both reported issues are fixed.

**Comment by branscombj** [comment] 2018-11-07 13:34
Thanks @jamesmrollins !
@TomRust @dlounsbu @lzim This looks like an unlabeled reinforcing loop in CC and MM? I don't recall hearing/telling this story:
True Missed Appointment Rate -> Appointments to Reschedule -> Rescheduling Rate -> Completing Rate -> True Missed Appointment Rate

**Comment by lzim** [comment] 2018-11-07 15:53
Thanks @branscombj re: “looks like an unlabeled reinforcing loop” 
I think there was a reason this wasn’t labeled that way, right @TomRust?

I’m not sure I’m getting the functionality you describe. Ever since the floating text box you can see text, diagram (when text is on left) and output or experiments (when text is in right), but not the full expanded outputs and main model diagram at the same time. That has never been a function.


jamesmrollins

**Comment by branscombj** [comment] 2018-11-07 16:02
@jamesmrollins My memory is that when you first made the Exp Outputs tile able to be re-sized, we could adjust it from smaller to larger, seeing the outputs as well as the text boxes, and slide it around. Now, I can't see output charts except in full Exp Output mode. I actually can't see the Decisions box on my monitor in the new default mode, by the way, and can't move or resize the pane so that I can.
![image](https://user-images.githubusercontent.com/29778290/48143252-66018d80-e27c-11e8-814d-5e04bba7e2f8.png)

**Comment by jamesmrollins** [comment] 2018-11-07 19:10
@branscombj When you load up the Sim UI, the minimized Expanded Outputs tile is presented.  The Outputs tile and the Experiments tile are both minimized as well.  By clicking on the Outputs tile, it will expand to reveal a chart as shown in the picture you attached.  You cannot get directly to the Expanded Outputs anymore.  When you click on "Expand" on the Outputs tile, the minimized Expanded Outputs tile will be presented.  To get to the full view, you have to expand the minimized Expanded Outputs tile.  

I hope this helps.  If you need a better explanation, give me a call or I can call you.

James

**Comment by branscombj** [comment] 2018-11-07 21:33
@jamesmrollins @lzim @staceypark We notice that the Text section is labeled Outputs in the blue bar. Should say Text when it's only the text section in default sim UI view.

**Comment by jamesmrollins** [comment] 2018-11-07 22:41
Roger, I will put in the change.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by dlkibbe** [comment] 2018-11-16 23:02
@jamesmrollins  Typo in care coordination model i text for "Effect of Wait Time on Referrals"
It says "The effect wait time has on referral rates, applied to potenital patients to CC specific to their primary diagnosis."  Spelling of "potential" needs to be corrected. Thanks.

**Comment by lzim** [comment] 2018-11-17 18:34
@dlkibbe the "i" information will all be edited in the Master Cross-Walk - Check-out System #208 and is not a bug 😅 

If you do find any MTL 1.7 issues - please post those to MTL Ver 1.7 Suicide Prevention - Test #257

Thanks 💓 

I'm going to close this issue, since the last issue from 10 days ago is resolved.



> @jamesmrollins Typo in care coordination model i text for "Effect of Wait Time on Referrals"
> It says "The effect wait time has on referral rates, applied to potenital patients to CC specific to their primary diagnosis." Spelling of "potential" needs to be corrected. Thanks.

**Closed by lzim** 2018-11-17 18:34 UTC
Labels: bug
