### ISSUE TITLE
wk3 jan_epic: Find and Replace Bug - Internal Server Error

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2463] opened 2022-01-14 21:20 UTC
@jamesmrollins 

1. The Find and Replace GitHub Actions on lzim/mtl is producing an internal server error bug.
- See output log [here](https://github.com/lzim/mtl/runs/4822148843?check_suite_focus=true).
- I do not believe that server error is coming from GitHub, it states its operational[ here](https://githubstatus.com).
![image](https://user-images.githubusercontent.com/59668647/149586562-a4d64199-c775-4dab-afcd-2320c9c96283.png)

2. @mnallajerla Was not able to trigger the Action in her forked repo, is there a step we need to configure (e.g. security or token?) in her forked repository to get the YML to work?

**Comment by jamesmrollins** [comment] 2022-01-16 17:31
Hi @hirenp-waferwire - Please see detailed bug report above and attempt to resolve.  I am available if you need to meet.  Thanks, James

**Comment by jamesmrollins** [comment] 2022-01-17 17:48
Hi @mnallajerla and @lijenn.  Jenn's hypothesis of the original find-and-replace action being taken down is confirmed.  The original action was called https://github.com/shitiomatic/ is no longer found on github.

We are creating a new action called https://github.com/jacobtomlinson/gha-find-replace, which operates under an MIT license. We are going to set that up tonight and hopefully have it available be Tuesday 1/18 morning.

**Comment by jamesmrollins** [comment] 2022-01-18 04:46
I have already updated this code in the lzim/teampsd and lzim/mtl master branches.  This code would need to be added to the workflow folder, findreplace.yml file, replace lines 49 through 63.

    - name: Find and Replace
      id: fn
      uses: jacobtomlinson/gha-find-replace@v2
      with:
          find: "hello"
          replace: "world"
          regex: false
          exclude: "**/*.yml"
          # search returns only committed file by user 
          #include: ${{ steps.getfile.outputs.files }} 
          # only searching such directory's files and subdirectory's files which is committed by the user
          #include: "${{ steps.getDirName.outputs.dirs }}/**"  
          # always searching directory or file by its name which is available with double quotes i.e "test", "test/xyx.txt", "xyx.txt"
          #include: ""


## See Instructions below for Parameters. 

By default, the code will check every file in the fnr-branch for the replacement conditions.  These parameters will focus the search to the committed file, the committed file directory or some custom path.  Remember to run only one parameter at a time.

![image](https://user-images.githubusercontent.com/30132017/149872525-ed62a78b-9c59-4adb-a8aa-020dc88b4fd8.png)

@jamesmrollins will update the fnr instructions in the SOP.

**Comment by jamesmrollins** [comment] 2022-01-20 03:30
Hi @hirenp-waferwire -  Take a look at the error message below.  Is this an issue where the internet has caused a file corruption, or does it indicate another problem? The end user indicated successful use of the findreplace action, except in the instance below.

![image](https://user-images.githubusercontent.com/30132017/150267135-e0131b6f-1398-4b5e-9cf2-d9e0f672cfc1.png)

**Comment by jamesmrollins** [comment] 2022-01-20 04:31
@mnallajerla - The exit code 128 might be caused by the back-slash.  We are going to check it out tonight to verify.

**Comment by jamesmrollins** [comment] 2022-01-20 15:18
Hi @mnallajerla - @hirenp-waferwire found the error and provided the instructions below:

## Fetch Depth Instruction Causing Error

![image](https://user-images.githubusercontent.com/30132017/150367201-003512c2-7f6d-4fc3-aec8-00565628fb50.png)

## Comment out Fetch Depth in FindReplace.yml lines 31-32

![image](https://user-images.githubusercontent.com/30132017/150367228-802b7161-8956-4cc7-9bf8-454c3868a9c6.png)

## Tested new instructions for "mtl.how" to "mtl.how/data" - appears to be working again

![image](https://user-images.githubusercontent.com/30132017/150367082-45725bae-2119-4106-931d-ed3623e972bb.png)

**Comment by mnallajerla** [comment] 2022-01-24 19:28
The FNR Action is working well and does not need further work. This bug has been resolved.

**Closed by mnallajerla** 2022-01-24 19:28 UTC
Labels: dev, bug, Operations

**Comment by hnorthcraft** [comment] 2025-05-12 16:09
#adjudicate_memo @lijenn can you estimate SP? Thanks!
