### ISSUE TITLE
SP team data table does not seem to be reading values into SIM

### ISSUE THREAD

**Issue by hmarcia** [lzim/teampsd#2033] opened 2021-06-03 17:28 UTC
![image](https://user-images.githubusercontent.com/50675495/120686923-7d727880-c46f-11eb-92b8-4dfe7c974aa2.png)

![image](https://user-images.githubusercontent.com/29778290/120687092-ab57bd00-c46f-11eb-903a-80a00630be9c.png)

**Comment by hmarcia** [comment] 2021-06-03 17:31
This is the prep from June 3rd with @branscombj and @hmarcia from 8:30 pacific to 10:30 pacific

@hmarcia was in her individual world within the team that this prep is for.

**Comment by staceypark** [comment] 2021-06-03 17:41
@anazariz I know you just fixed some bugs with the SP module for pulling the team data table on #2019. Based on what I see in the team data table xlsx vs. in the team data table in the sim, I think the issue is coming from the sim end, but any chance it might have to do with your fix?

**Comment by branscombj** [comment] 2021-06-03 17:47
Also @staceypark @anazariz I'm not sure if this observation was addressed in the other issue about creating the team data table with SP, but we noticed that in the SP tab, (pardon my describing without exact refs - my VA laptop's closed now) there are the 2 columns of calculated data, Constant/Variable and Encounters (or whatever that 2nd one is called). The bottom several cells of the latter are blank. The last few make sense because that's a user-specified number, but the ones above it were blank in the team data table all with SP that Stacey created today as they were in the previous one Marcia created using the default selection for referral GMH/SMH.

**Comment by jamesmrollins** [comment] 2021-06-04 05:34
Hi @branscombj @hmarcia @staceypark @anazariz 

Can someone please email me the team data file in question?  I am 99% sure the Sim UI is reading correctly - I would like to verify the team data file. 

Thanks - James

**Comment by hmarcia** [comment] 2021-06-04 12:55
589_kansas_city_pct_all_2021_06_03.xlsx


This is the file name. 😊

From: James Rollins ***@***.***>
Sent: Friday, June 4, 2021 1:35 AM
To: lzim/teampsd ***@***.***>
Cc: Hunt, Marcia ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [lzim/teampsd] SP team data table does not seem to be reading values into SIM (#2033)


Hi @branscombj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbranscombj&data=04%7C01%7C%7Ccee202a8fe9a44b9ca2b08d9271a80d4%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637583817064450657%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=pOQT1B6Sbb0T21H9b8Qsfsq57sAeHWvqorIiBBQnpDc%3D&reserved=0> @hmarcia<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhmarcia&data=04%7C01%7C%7Ccee202a8fe9a44b9ca2b08d9271a80d4%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637583817064460612%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=zkDJUNLMoIgMpYAqGNHgXD6VYF1Uo0xKF%2BMhtrgu7I0%3D&reserved=0> @staceypark<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fstaceypark&data=04%7C01%7C%7Ccee202a8fe9a44b9ca2b08d9271a80d4%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637583817064470568%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=PyxsebyJLTZG%2Fr9hETZSSQK1Z0eNQVrBj2covpLqMiM%3D&reserved=0> @anazariz<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fanazariz&data=04%7C01%7C%7Ccee202a8fe9a44b9ca2b08d9271a80d4%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637583817064470568%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=cDMImYklGB3hU7utWaSP1c4I35%2FpjVh9nZDEvYhHQSk%3D&reserved=0>

Can someone please email me the team data file in question? I am 99% sure the Sim UI is reading correctly - I would like to verify the team data file.

Thanks - James

**Comment by branscombj** [comment] 2021-06-04 13:02
Hi @jamesmrollins I think you'll be able to find it? but if not I can email you the actual file - I'll just have to wake my VA machine:)

**Comment by jamesmrollins** [comment] 2021-06-07 19:16
Thanks Marcia – I am indeed looking at the correct file.

James Rollins, Col - USA (Ret), MEd, MSS
PRAXIS ANALYTIX
(425)919-5153

**Comment by jamesmrollins** [comment] 2021-06-07 19:17
Thanks @branscombj and @hmarcia - I found the correct file and am troubleshooting accordingly. 

FYI @staceypark @lijenn

**Comment by jamesmrollins** [comment] 2021-06-08 00:34
Hi @branscombj @hmarcia @lijenn @staceypark 

FYI @TomRust @hirenp-waferwire 

After running some tests this afternoon and discovering a "Floating point error" in the model, I think I have a working hypothesis that may help us understand the problem.  

- Since the model stops running at time= -635 weeks, it never reaches time=0. 
- When the model records data values derived from equations, it reads these variables at time=0.
- We are using data values derived from equations, because we are filtering them through episode count minimums.  In other words, if the episode count for a given variable is not big enough to pass the criteria, the variable passes a "0" for that value.
- In the diagram below, the data value is passed to "Data_PC/PCMHI_to_GMH_Engagement_Time_Before_Step_up_-_filtered" by "Data_PC/PCMHI_to_GMH_Engagement_Time_Before_Step_up(median)" and multiplied by a "1" or "0" passed by the "Flag_PC/PCMHI_to_GMH_Engagement_Time_to_Step_up_EpC".  
- This is why in the Sim UI inspect window (see list of purple variables on left), we see none of the filtered values showing in the variable array, even though there are clearly values for the data variable present.
- Thus, if we fix the floating point error in issue #2034, the team data table should populate. 

![image](https://user-images.githubusercontent.com/30132017/121103875-a8cdce00-c7b5-11eb-9db6-f1c0bb81f08a.png)

**Comment by lzim** [comment] 2021-06-08 22:04
@jamesmrollins I think you're referencing #2032 above - Have you tried 0.1?

**Comment by jamesmrollins** [comment] 2021-06-09 22:39
@lzim yes, you are correct, I meant #2032.  I have corrected it above - thank you. Yes, I tested with 0.10 yesterday and it didn't work.  However, this issue has been resolved, model-wise, with the variable dependency realignment in the flagging system (see #2032).  I still believe we have to update the Data UI to present a minimum value of 0.10 in the GMH New Episode of Care Wait Time cell. 

With respect to the Team Data Table variables not loaded as reported by @hmarcia , the model crash due to the floating point error at time= -635 prevented the derived variables (filters) from calculating and populating the table at time=0.

This issue can be closed once we promote the new model to PROD.

**Closed** 2021-06-15 03:44 UTC
Labels: dev, sim_ui
