### ISSUE TITLE
ICEBOX: D365 Prod Backlog (Bug) - Replying to emails incoming from our shared inboxes from Outlook (but works for templated emails?)

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2268] opened 2021-09-24 01:20 UTC
1. **Who encountered the bug:** Jenn

2. **Which instance are you testing in?:** Prod

3. **Date/Time of the bug:** 9/23 6:00pm Pacific

3. **Role:** Admin

4. **Detailed description of the bug:** 

- Howard caught this bug on Wed 9/22 at ~12:30pm Meeting.
- Jenn was originally unable to see the incoming emails from MTL Help and Info from Outlook on Wed.
- Jenn sees it today Fri. 9/23 and able to recreate the bug
![image](https://user-images.githubusercontent.com/59668647/134603965-b2d1a8b3-afe6-4e1e-9bc4-66de251fcb2e.png)

**Comment by apisano0920** [comment] 2021-09-28 19:42
This is associated with one of the problems we reported to Microsoft that has potentially been fixed on DEV. I've asked for more info on it from Microsoft to get an idea of whether it's a different problem or the same. But it looks like it's caused by the fact that the owner of the email is the general D365 user account instead of a MTL team. I found one email that has MTL Help in the 'To' field and is owned by an MTL Team and I was able to successfully reply to it.
![image](https://user-images.githubusercontent.com/60359621/135154730-022edfa3-c88b-4ff3-a689-e04c1cd02076.png)
![image](https://user-images.githubusercontent.com/60359621/135154792-34447e6e-ead1-42af-8271-e734e9583a73.png)
![image](https://user-images.githubusercontent.com/60359621/135155002-abd7887e-2080-4beb-83a5-55f47899b424.png)

**Closed** 2024-03-05 18:05 UTC
Labels: d365, bug, Development
