### ISSUE TITLE
2024_wk1_apr: FEATURE: Change the learning modes of CC and MM from the Dynamic Dashboard

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#3132] opened 2024-03-22 21:37 UTC
## User Story

As an end user, I need a way to change the learning modes of CC and MM from the Dynamic Dashboard without having to completely to the beginning of the "GO" computer workflow.

When the user clicks on the red Learning Mode Label feature in the CC or MM sub-sections on the Dynamic Dashboard, then the system will present the Learning Mode pop up.  

If the user clicks on a different setting, such as, 'Existing patient Return to Clinic Visit Interval,'
then the system re-initializes based on the new learning mode when the user clicks 'Continue'.

Else, the user is returned to the Dynamic Dashboard with no action.

### 1. User clicks 'Learning Mode' label

![image](https://github.com/lzim/teampsd/assets/30132017/4116e53d-f205-4dbc-8766-dbb894746025)

### 2. Learning Mode pop is presented.

![image](https://github.com/lzim/teampsd/assets/30132017/abc519b8-9bb3-4edc-a2b8-76d8ffbe298c)

### 3. User selects different Learning Mode and clicks 'Continue'

![image](https://github.com/lzim/teampsd/assets/124643236/86578bf6-aad4-4620-a36b-1faab7a1068a)

### 4 The model re-initializes to time=0 in the selected Learning Mode

![image](https://github.com/lzim/teampsd/assets/30132017/a06773a0-5c78-4535-b2c5-1a949346ada0)

**Comment by ljmoody** [comment] 2024-03-26 15:48
Hi @tejaspesquare & @jamesmrollins - I modified the image in Step 3; Tejas should now be able to view.

**Comment by tejaspesquare** [comment] 2024-03-27 13:27
@jamesmrollins , @ljmoody - Development done in our local environment however this change forced to make some design related changes which is in-progress.

FYI-
![image](https://github.com/lzim/teampsd/assets/144898781/c5ae1f60-a227-4f9c-8c62-0017211903b7)

**Comment by ljmoody** [comment] 2024-04-04 02:23
@tejaspesquare, please let Jenn and I know when we can test this, and in which instance. Thank you.

**Comment by ljmoody** [comment] 2024-04-04 04:20
Discussed at 4/3/24 Sim UI standup.
- [ ] @ljmoody will test this tomorrow

**Comment by ljmoody** [comment] 2024-04-04 15:11
Hi @tejaspesquare - I tested this feature in Test-Slow (after doing a hard reset) with mixed results. It sometimes works and refreshes the DDD and other times it just hangs on the learning mode transitions. I [recorded what I experienced](https://takouba-my.sharepoint.com/:v:/g/personal/lmoody_praxisanalytix_com/ERi-8w2yZH9BswRLVvvq_jABwkWELoBuLCBw7hETfTZjPg?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=hi0YL7) so you can observe. Twice in the video I refreshed the browser screen to reset. 
Please revisit and let me know when to test again.

**Comment by lzim** [comment] 2024-04-04 18:56
FYI @lijenn @ljmoody & @tejaspesquare 

Yesterday and today using **Chrome** and my **VA Laptop** I experience "hung" result in the **Sim UI TEST Dynamic Dashboard** after selecting the **EPRVI Learning mode for both CC & MM** to initialize the Dashboard using the **Soft Moss Data** file.
 
Here is the **Inspector Console** and the view I receive. The only way out of it is to log off and try again.
![image](https://github.com/lzim/teampsd/assets/7454688/093f781f-36bb-454e-99ec-3d01628b2a1b)

**Comment by tejaspesquare** [comment] 2024-04-05 13:34
@ljmoody, @ljmoody - When we tested at our end (Test Slow) it gives expected result. Results attached as given below.

Initial Run
![image](https://github.com/lzim/teampsd/assets/144898781/f882d881-4a02-49b7-9489-46300649da05)

Learning Mode Change to NPSR
![image](https://github.com/lzim/teampsd/assets/144898781/35bd0b87-c824-41b5-a639-1427baa3649c)

![image](https://github.com/lzim/teampsd/assets/144898781/82a740b2-1fed-4f44-8722-9cac006a5ea4)

Switch back to EPRVI
![image](https://github.com/lzim/teampsd/assets/144898781/ce252c3e-b810-4d6d-888e-7f3e4d5a32ea)

Note: Version3 error (1st entry in your console error log) you won't encounter now. We tried to reproduce same error log however it ran successfully in our case. Would like to replicate issue, could you please share model file you have used in your test. 
Thanks!

**Comment by lijenn** [comment] 2024-04-08 03:56
Discussed 4/7 Sim UI Standup:
- @tejaspesquare Mentioned that the lack of consistency and inaccurate and unrealistic ranges of the modules is due to the data file issues described in #3134. This is expected to be resolved this week.
- @lijenn will test using various data files to see if toggling between learning modes requires a hard refresh or not, as this could be the case mentioned by @tejaspesquare:
 <img width="195" alt="image" src="https://github.com/lzim/teampsd/assets/59668647/67c6a911-dd0e-4e8d-b9d1-95c769e5e222">

**Comment by jamesmrollins** [comment] 2024-04-15 04:07
## 3/14 Stand Up

- @ljmoody will test this week.

**Comment by ljmoody** [comment] 2024-04-22 23:46
Tested 4/19 and 4/22 using one Blue team data set and one Red team data set. Both returned reasonable and consistent numbers for all modules and services within those with service options. Used green Go! button and red EPRVI/NPSR buttons to reinitialize data sets within the model. No hanging and no unreasonable numbers.

✅ Verified that changing learning modes works correctly and as intended. Moving to Done column in ZenHub.

fyi: @jamesmrollins

**Comment by lijenn** [comment] 2024-04-25 04:02
Discussed Stand Up 04/24/24:
- @lijenn will test and confirm. If all looks good, we can close this card!

**Comment by lijenn** [comment] 2024-04-29 01:45
Jenn verified and got the same dashboard and data results using the 4/19 and 4/22 data from Laura's test worlds.
@ljmoody feel free to close once the documentation is done!

**Comment by ljmoody** [comment] 2024-05-14 19:01
Closing card; documentation added to section 7.0 of existing _MTL_ manual "Dynamic Decision Dashboard" (specifically the overview of the DDD with numbered pins).

**Closed by ljmoody** 2024-05-14 19:01 UTC
Labels: sim_ui, feature, Development
