### ISSUE TITLE
2023_wks_2-4_oct_#story_b: As a facility leader, I need clear meters of performance in a convenient dashboard

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#2979] opened 2023-06-07 16:28 UTC
## Definition of Done:

- [ ] A completed and approved Wireframe illustrating the concepts below.
- [ ] A tested application that clearly communicates:
   - [ ]  a team's status regarding patients/wk, appointments/wk, and episodes of care in context to RVI (care meters and calendar concepts).
   - [ ] Color coding system that indicates whether a given stock has an equal in-flow to out-flow (yellow), greater net inflow to outflow (red), or lesser net inflow to outflow (green). (See illustration 1 below).
   - [ ] 6-month period where Engagement Duration is represented as a line going through a calendar icon and displays amount RVI using an "x" icon. (see Illustration 2)
   - [ ] A button/icon in the Dynamic Dashboard that shows the "Flows".
   - [ ] A user-manipulatable pie chart widget for Service Proportion %. 
 - [ ] The order of icons in the Dynamic Decision Dashboard: Feedback, Flow, Decision Meter, Calendar, Play.
- [ ] Variable array radio buttons are displayed under the module header.
- [ ] Widgets express standard units: patients/week appts/week, episodes of care/week, week, and percent.
Crossref #2804 
- [ ] Add a button/icon in the Dynamic Dashboard that shows the "Flows".
- [ ] Order of icons in the Dynamic Decision Dashboard: Feedback, Flow, Decision Meter, Calendar, Play
- [ ] Arrays need to be moved under the module header
- [ ] Units: patients/week appts/week, episodes of care/week, week, and percent
- [ ] Reference Illustration 3.

## Illustration 1

![image](https://github.com/lzim/teampsd/assets/30132017/5b619342-6662-4855-b4ff-a47f2a53bca9)

## Illustration 2

![image](https://github.com/lzim/teampsd/assets/30132017/c3111759-53ea-4107-beec-af8fdc286676)

## Illustration 3

<img width="1391" alt="image" src="https://github.com/lzim/teampsd/assets/59668647/d5ea04c5-36b3-4862-9209-9e69e8177b8b">

**Comment by jamesmrollins** [comment] 2023-06-21 23:35
FYI: @ljmoody @lijenn @hthrmarsh @dlkibbe @hirenp-esquare 

Hi @lzim!  Hope you are having a good week.  Below are needed decisions and clarifications for the progression of wireframe development.

## Decision 1:  Itemize Flows out of Psychotherapy Stocks, or Sum into a Single Flow? Recommend option 2 (Visual Simplicity for Decision-Maker) 

- [ ] There are three stocks with multiple outflows; Starters, Initiators and Completers.
- [ ] There is one stock with multiple inflows, Patients in Care for More than 3 Months.
- [ ] The addition of the variables for the outflow would not be displayed.
- [ ] Could also use radio buttons to show each contributor in the outflow (i.e., Total, Ending after First Visit, Initiation Rate, Continue after Three Months). 

### Option 1

![image](https://github.com/lzim/teampsd/assets/30132017/5ea28975-72ee-4cf2-bb3c-42bbac67a9f1)

### Option 2

![image](https://github.com/lzim/teampsd/assets/30132017/c46d818f-9c3d-4bb1-87d9-ac84ba63ea2c)

### Option 3

![image](https://github.com/lzim/teampsd/assets/30132017/ecb68324-4b37-4bb7-9d38-3c9a65cefab5)

## Decision 2: Do You Want to Reference Sankey from Flow Meters? Recommend "Yes"

- [ ] While Sankey does not display immediately after sim initiation, it could be referenced after a base case run, or to assist with illustration of an experiment.  We would gray it out until it has data to display.
- [ ] Would need to provide a supplemental pop-up that allows you to select saved experiments, so the sim knows what Sankey charts you want to display.
- [ ] Sankey button could also be provided from Dynamic Decision Dashboard, or just here, or both.

![image](https://github.com/lzim/teampsd/assets/30132017/29151d33-e8d1-442d-871e-4189d4178bbf)

## Clarification 1: Engagement Duration and Return to Clinic Visit Interval for Psychotherapy Will Need to Cover Starters, Initiators, Completers in the 25th, 50th and 75th Percentile.

- [ ] Yes
- [ ] No
 
![image](https://github.com/lzim/teampsd/assets/30132017/0914161d-e989-48dd-a593-7347fccb7226)

## Clarification 2: Is This How We Should Interpret Engagement Duration and Return to Clinic Visit Interval?

### Example 1

- [ ] Engagement Duration = 23 wks.
- [ ] RVI = 2 wks.

![image](https://github.com/lzim/teampsd/assets/30132017/383d1a61-41d1-47ce-b210-8b60dd886d91)

### Example 3

- [ ] Engagement Duration = 2 wks.
- [ ] RVI = 23 wks.

![image](https://github.com/lzim/teampsd/assets/30132017/c287adc5-e152-41b7-ab53-c91456f26469)

### For Reference

![image](https://github.com/lzim/teampsd/assets/30132017/87e729ee-f34b-41d9-9c28-e89243657467)

## Clarification 3: We Would Need to "Save" Decision Meter Heuristics from the Popup

- [ ] Yes
- [ ] No

![image](https://github.com/lzim/teampsd/assets/30132017/135ddf24-928e-42ef-b418-51efe147a1c5)

## Clarification 4: We Need Only 1 Psychotherapy Decision Meter Heuristic, Even Though There Are Initiators, Starters and Completers, Because We Are Encouraging As Many Completers as Possible - Correct? 

- [ ] Yes, correct.
- [ ] No, we will need to establish heuristics for all three categories. 

## Clarification 5: We Need Separate Decision Meter Heuristics for Each Cohort or Service in MM and Team Care Respectively.

- [ ] Yes
- [ ] No

![image](https://github.com/lzim/teampsd/assets/30132017/15c9011b-42b7-46d1-a6d9-69e12f820d52)

## Clarification 6:  Team Flow 

- [ ] This is a wildcard with respect to Engagement Duration, RVI, and Appointments.
- [ ] Team Flow relies step-up and step-down rates between clinics, affected by stepped care triggers and length of stay in a step of care and the implementation of measurement-based care - we may need different sets of Decision Meter heuristics and calendars to illustrate different variables such as time to step-up or step-down, and the effect of MBC on stepped care.

_Thank You!_

**Comment by dlkibbe** [comment] 2023-06-22 04:51
Just curious @jamesmrollins on Option 2 image would there be numbers associated with the text categories on the right of the Starters box (e.g. initiation rate, continue treatment, ending after 1st visit) and a total flow number?
![image](https://github.com/lzim/teampsd/assets/31182258/28164c84-b508-4085-9ca1-5fff02bfd59f)

**Comment by jamesmrollins** [comment] 2023-06-22 14:35
Hi @dlkibbe - The addition in text on the right was to illustrate that we would simply sum the three variables into the total flow and only depict the total flow in the arrow.  The addition would not be shown on the diagram.

**Comment by dlkibbe** [comment] 2023-06-22 18:06
Thanks @jamesmrollins - that leads me to ask how a new user would know what the total flow consists of? Would it be detailed in an "i" bubble and/or a facilitator would point to each data point (ED, RVI, etc.) summarized in the data table section?
With regard to the other designs: 1) the MM decision meter image is cool and easy to interpret for me - I think maybe the comma next to Delays should be replaced with "in"; 2) the calendar images are a bit confusing for me ... it feels like they take up a lot of space but don't necessarily portray the information effectively/succinctly. What new decision would I make using the information on those images?

**Comment by jamesmrollins** [comment] 2023-06-22 20:20
Thanks @dlkibbe for the review of these widgets.  They will help inform our designs. 

1.  With respect to flows in and out, it may be better to use either the radio button design, that would allow a detailing of the amounts of each outflow, or the multiple arrow option that accomplishes the same thing (although a busier diagram).
2. I like that design too.  Traffic lights are very universal.  The comma after delays, I think, is to differentiate between delays in the system and access.  I'm not sure it is "Delays in Access." @lzim should verify when she has a chance.
3. The calendars are supposed to illustrate the spacing over many months of engagement duration and RVI.  The idea of showing it over calendars would provide a spatial representation of data, instead of just a number.  What do you think might make it easier for you to interpret?  Would coloring in the days of the week be better than lines, or something similar?

Thanks again Debbie - you are big help!

**Comment by jamesmrollins** [comment] 2023-06-22 23:14
FYI @dlkibbe @TomRust @lijenn @ljmoody 

ACTION: @lzim 

## Wireframe Update

- [ ] See dialogue above for requested clarifications and decisions.
- [ ] Latest wireframe - [Sim UI Release 3.7 -Dynamic Dec Dash and Widgets.pdf](https://github.com/lzim/teampsd/files/11841167/Sim.UI.Release.3.7.-Dynamic.Dec.Dash.and.Widgets.pdf)
- [ ] Discussed Causal Diagrams with @TomRust and worked out a plan for completion.  However, Tom indicated he would like to discuss with you, if possible, the potential of using the existing system dynamics model diagrams we have developed for the sim.  Perhaps we could simplify those for the purpose of storytelling?  This is technically feasible, and we could preserve the layer builds as well.

**Comment by TomRust** [comment] 2023-06-23 01:00
Hi! @lzim -- I just met with James on creating CLDs for each module.  How do you feel about us starting with the diagrams we already have in the sim?  Just simplifying them down to CLDs -- taking away all the icons, making the rate arrows look the same as the information arrows, removing most of the data, sensitivity, and user-control variables, etc.  Will that get you what you're looking for?

Happy to send you one, then have a call to check if we're going the right direction.

FYI @jamesmrollins

**Comment by lzim** [comment] 2023-06-25 21:56
Thanks @TomRust & @jamesmrollins 

Yes, that sounds great. 
Would love to take a look at an example.

Thanks again!

**Comment by lzim** [comment] 2023-06-25 22:07
Great work on this!




### Decision 1:

Option 4: Showing a

UX Principles noticed:
- [ ] It's valuable to see all the separate outflows, including the total, all at once without requiring the user to click on anything.
- [ ] 

Needed:
- [ ] Inflow labeled "Inflow" (not flow)
- [ ] Outflow labeled "Outflow" (not flow)
- [ ] Stronger visual emphasis on the fact that both stock and flow depict a typical **week** over the last two years. 

Remove:
- [ ] Blue outline of the stock when in red, yellow, green state. It adds visual complexity without conveying meaningful info.

**Comment by TomRust** [comment] 2023-06-26 20:41
Basic draft for CC [here ](https://lucid.app/lucidchart/2070867e-b85c-4b3d-a628-0b16a1f5f303/edit?beaconFlowId=B30F61458BA5B11C&invitationId=inv_41a8d234-ffe3-4c52-a526-37eb7f7012e1&page=0_0#)-- needs arrow polarities and for the loop names to stand out more.

**Comment by lijenn** [comment] 2023-06-26 23:20
Discussed 6/26/23 in 2023_8am_workflow @lzim @jamesmrollins @dlkibbe @dlounsbu:

- [ ] Decide on features that also address a specific issue/use case based on the mandates to get feedback at tmrw's 6/28 consult_workflow

I had a hard time deciding on which specific features to cover at tmrw's consult_workflow as all seem important for feedback, especially since the **features/icons are organized this way for a reason**.

**We may want to briefly cover all the features based on its flow, as designed, starting with feedback, flow, decision meters, and so forth:**
<img width="416" alt="image" src="https://github.com/lzim/teampsd/assets/59668647/a48f54b7-d3b9-4486-87a2-cf681baa3555">

However, **if we had to only pick one or two to cover**, I'd pick the most visual and intuitive to understand in terms of supporting clinical decision making, which are the **Flow and Decision Meters**.

It also might even make sense to **just tell the story as described in this card** (i.e. As a facility leader (or Lead!), I need clear meters of performance in a convenient dashboard).

**Comment by jamesmrollins** [comment] 2023-06-27 00:22
FYI @lzim 

@lijenn - Your judgment above is sound. I spent much of today updating the wireframe to incorporate @lzim 's and @dlkibbe comments above.  Hopefully it will be good fodder to enable discussion. I updated Psychotherapy and Team Flow diagrams, as they both had multiple flows in and out of stocks. The other diagrams are pending update after we review with QIICs tomorrow.

@TomRust the diagram link you sent requires me to have permission to review it, for some unknown reason.  Can you provide please? 

Newest Wireframe: [Sim UI Release 3.7 -Dynamic Dec Dash and Widgets.pdf](https://github.com/lzim/teampsd/files/11876320/Sim.UI.Release.3.7.-Dynamic.Dec.Dash.and.Widgets.pdf)

**Please note that the layers have been enabled.**  If the reference numbers in the red circle turn up, just go to the layers in Adobe Acrobat and turn the layer "call out numbers" off.

**Comment by jamesmrollins** [comment] 2023-07-08 00:00
FYI @TomRust @lijenn @lzim @ljmoody @dlkibbe 

## Wireframe Update
- [ ] Aligned stocks and increased font sizes of stock descriptions.
- [ ] Reduced visual clutter of additional navigation buttons.
- [ ] Added three new icons 
   - [ ] Team Data
   - [ ] Directives
   - [ ] Arrays
   - [ ] Ellipses
- [ ] Redesigned the Learning Mode pop up  
- [ ] Updated the CC Feedback diagram based on @TomRust design.
- [ ] Aligned the bottom of the menus with the Dynamic Decision Dashboard
- [ ] Added Learning Mode tag.

To go:
- [ ] SAIL connection icon.
- [ ] Concept work for linking directives to use cases to case histories in the sim UI.

[Sim UI Release 3.7 -Dynamic Dec Dash and Widgets.pdf](https://github.com/lzim/teampsd/files/11986942/Sim.UI.Release.3.7.-Dynamic.Dec.Dash.and.Widgets.pdf)

**Comment by jamesmrollins** [comment] 2023-07-13 23:13
FYI @TomRust @lzim @lijenn @ljmoody 

ACTION:  @hirenp-esquare 

## Dynamic Decision Dashboard Released to DEV

1. PDF of wireframe - [Sim UI Release 3.7 -Dynamic Dec Dash and Widgets.pdf](https://github.com/lzim/teampsd/files/12045052/Sim.UI.Release.3.7.-Dynamic.Dec.Dash.and.Widgets.pdf)

2. EPS of dashboard - I will email these separately as they are not supported in GitHub.

3. Notes:
- See details on new dropdown scheme for navigation buttons and variable arrays.
- See details on Increase/Decrease widget in association with Feedback Causal Loop Diagrams.
- See details on Flow Meters Sankey Widget Logic and Stock Color Logic.
- See details on Decision Meter number entry by user.

**Comment by lzim** [comment] 2023-07-14 14:29
Thanks @jamesmrollins & @hirenp-esquare 🚀 

I also had some thoughts for the Dynamics Before Details problem that we considered based on QIIC feedback on Tues.
- [See Teams](https://teams.microsoft.com/l/message/19:cd8c8a819f6041219bdf78ad0dd9b93b@thread.skype/1689344611668?tenantId=e95f1b23-abaf-45ee-821d-b7ab251ab3bf&groupId=1db500d5-0d01-4254-af42-ad3f78bafacd&parentMessageId=1618439945589&teamName=teampsd_vha&channelName=sim_ui_workflow&createdTime=1689344611668&allowXTenantAccess=false)
"Dynamics before Details" learning challenge mentioned by Carla about why the 30 minute psychotherapy (90832) is grouped with other 30 min or less encounters, and the 45 (90833) and 60 minute (90834) psychotherapy.
 
**These follow-up on the array discussion** - **In the Dashboard we need:**


	**Team Care - Services** 
	1. **Indicate at a glance the visit length for each e.g. Med Mgmt (30 min)** (this helps interpret both the Team Data Table and in the Simulation Model where we defined and grouped these). 
	
	2. We should include a **link to the CPT Cheatsheet and Data UI s**omewhere on the dash.
	 
	**Medication Management - Patient Cohort** - _Did we decide about changing from "patient cohort" to something else?_ 
	We agreed it needs to align AND we saw there may be a lot of rework - think of the guides, not just the Sim UI, if we change it.
	1. Indicate at a glance the definition for AUD, dep, OUD, other - We need to confirm this is based on primary ICD-10 diagnosis on the visit)
	 
	**Team Flow - Setting** - We need to confirm this is based on stop codes. 
	1. Indicate at a glance the definition for PC/PCMHI, GMH, SMH

FYI: @lijenn @TomRust @ljmoody

**Comment by lzim** [comment] 2023-07-14 14:56
@hirenp-esquare & @jamesmrollins 

See screen below from [Sim UI Release 3.7 -Dynamic Dec Dash and Widgets.pdf](https://github.com/lzim/teampsd/files/12045052/Sim.UI.Release.3.7.-Dynamic.Dec.Dash.and.Widgets.pdf). It only shows how the proportions should work within an outflow example. 
But, it is also important to see the **Sankey inflow to the stock and the outflow from the stock in proportion to one another.**

![image](https://github.com/lzim/teampsd/assets/7454688/c19eed31-31a4-4bbd-8902-695e1b6ef7a1)

FYI: @TomRust @lijenn @ljmoody

**Comment by jamesmrollins** [comment] 2023-07-21 19:44
Hi @lzim 
FYI: @lijenn @ljmoody @dlkibbe @dlounsbu 

@hirenp-esquare I will provide an updated wireframe Monday night. 

## Hexapus Sankey Widget for Team Care Flow Meters

- [ ] Recommend fixed alphabetical order, vice thicker to thinner. I believe the consistency would help compare inflows and outflows, since they would be on the same visual line.

![image](https://github.com/lzim/teampsd/assets/30132017/9a991a08-4a80-4585-8d90-e61865971bc8)

## Sankey Style Flow Diagram for Team Care Flow
- [ ] Stocks modified to accommodate multiple flows. I tried multiple flows into the single legacy stock, and it was complex, ugly and confusing.
- [ ] Presents a visually simpler diagram.
- [ ] Stocks would become thicker as the number grows.

![image](https://github.com/lzim/teampsd/assets/30132017/117ac7be-c3cb-4739-9401-3286f2f81088)

## Sankey Style Flow Diagram for Medication Management

![image](https://github.com/lzim/teampsd/assets/30132017/799fefc1-c396-4318-83b0-5a91a80256a4)

## Care Decision Meters

- [ ] Below are three ideas on how to encourage a click-to-edit without a box.

![image](https://github.com/lzim/teampsd/assets/30132017/17508d74-d7cd-4bc8-8113-f1bcab67aca6)

## @hirenp-esquare 

- [ ] See below
- [ ] Please make the line for the top number thinner.  It appears too thick.
- [ ] The "click to edit" does not appear to allow the user to edit. Please use a smaller font.
- [ ]  On all options, when the user clicks away, the white line box reappears.  It should only be the number.  

![image](https://github.com/lzim/teampsd/assets/30132017/a1d29419-f446-4f1e-b2b0-955166788a27)

**Comment by jamesmrollins** [comment] 2023-07-26 19:54
Hi @lzim

FYI @hirenp-esquare @lijenn @ljmoody @dlkibbe @dlounsbu 

## Prototype for Calendar Feature using Timelines
![image](https://github.com/lzim/teampsd/assets/30132017/827180fe-3037-4677-b9b5-1f7eb4d21a7b)

## Return to Clinic Visit Interval Icon Prototype

![image](https://github.com/lzim/teampsd/assets/30132017/3d95090c-901a-431e-8bf6-da69d63c8970)

**Comment by jamesmrollins** [comment] 2023-07-28 19:56
@lzim 

FYI and Comment: @dlkibbe @dlounsbu @lijenn @ljmoody @hirenp-esquare 

## Variations on the Time Line Theme

![image](https://github.com/lzim/teampsd/assets/30132017/b8484d69-c04c-48b0-843f-c26b0903c150)


## Additional Return to Clinic Visit Interval Icons

![image](https://github.com/lzim/teampsd/assets/30132017/c8f85996-ecd7-44d3-a4ec-a09a72052ee0)

**Comment by dlkibbe** [comment] 2023-07-31 16:30
@jamesmrollins  - a couple of questions/comments:
1. On this image, "Rescheduling Rate" appears twice on the middle flows in the diagram, is that correct or should it be Booking Rate or some other descriptor?: 
<img width="475" alt="Sankey Capture - DK Question" src="https://github.com/lzim/teampsd/assets/31182258/df7b599e-f2be-4719-9b42-aced9b3cae83">
2. Timeline - The images with the vertical lines for weeks and months make much more sense to me. Because the models use "weeks" as the time window, it would seem weeks would be the logical timeline image to use.
3. RVI images with the Timeline - not able to see the images clearly without zooming in. 
4. What is another way to visually represent returning to clinic within a specific timeframe along with the engagement duration for a specific timeframe -- LZ notes "where their interplay is able to be gleaned at a glance?" current state vs. ideal state? Thinking about those sites we've worked with where the engagement duration is 300+ weeks, and the RVI range for weeks could be 1 to 20.

**Comment by dlounsbu** [comment] 2023-07-31 17:10
> @lzim
> 
> FYI and Comment: @dlkibbe @dlounsbu @lijenn @ljmoody @hirenp-esquare
> 
> ## Variations on the Time Line Theme
> ![image](https://user-images.githubusercontent.com/30132017/256920633-b8484d69-c04c-48b0-843f-c26b0903c150.png)
> 
> ## Additional Return to Clinic Visit Interval Icons
> ![image](https://user-images.githubusercontent.com/30132017/256920896-c8f85996-ecd7-44d3-a4ec-a09a72052ee0.png)

I like the timeline, but @lzim is recommending a calendar design. So, a box represents a month, so three boxes represents are three months. Dots in the box represent appts per month. 

Need to have an image to show ENGAGEMENT DURATION and RETURN TO CLINIC INTERVAL together.

**Comment by dlounsbu** [comment] 2023-07-31 17:17
**appt hours per patient per 3 months** RELATIVE TO **rvi** RELATIVE TO **engagement duration**. HOW TO COMMUNICATE THIS GRAPHICALLY?

**Comment by jamesmrollins** [comment] 2023-07-31 17:18
@dlounsbu I will take a crack at it with the suggestions provided.  Ill try to get something in the thread by early this afternoon if not sooner.

**Comment by dlounsbu** [comment] 2023-07-31 17:29
> **appt hours per patient per 3 months** RELATIVE TO **rvi** RELATIVE TO **engagement duration**. HOW TO COMMUNICATE THIS GRAPHICALLY?

Just give one or two examples. No need to calibrate to specific clinic/site. 

Aim is to help clinician conjure a mental model of key feedback loops (drivers).

**Comment by dlkibbe** [comment] 2023-07-31 17:38
One small thing @jamesmrollins on the Sankey scales, are you trying to spread the lines top to bottom with descriptive text equally? The bottom line of the Sankey scales "Group" seems to be "farther away" on the bottom scale.

**Comment by dlounsbu** [comment] 2023-07-31 17:44
![image](https://github.com/lzim/teampsd/assets/20574023/9bb2a853-4d3e-46cd-aefa-354c5eb4af23)

**Comment by jamesmrollins** [comment] 2023-07-31 18:02
@dkibbe - Yes they are trying to be equal in the drawing.  However, the widget may be more dynamic.

@dlounsbu - Thank you for the idea, I will draw that up too. I like that idea better than the segmented worm illustration above.

**Comment by ljmoody** [comment] 2023-07-31 19:34
@jamesmrollins, sharing some chicken scratches below from attempting to synthesize your design, feedback inputs, and my developing understanding of it all~
 
From L to R: 
- return to clinic icon brainstorms - will the size of these icons be similar to the worm illustration? If so, the challenge is simplifying yet understanding.
- engagement duration - a portion of a clock could be used to represent appt durations. It also seems possible to combine the return to visit icon with appt duration info.
- timeline - if treatment duration is represented by a calendar (vs the worm), played with a possible way to depict days and return to clinic events, without horiz&vert lines representing days...more boxes and circles 
- **?:** how many possible timeframes are meant to be visualized on/with the timeline? current state and EBP only? Additional scenarios? 


![IMG_4321.jpg](https://images.zenhubusercontent.com/6483906cab53e03a0946b96b/fe5c45f5-2214-49ce-8c45-de1cdb49d64b)

**Comment by jamesmrollins** [comment] 2023-08-01 16:25
FOR : @lzim 
Comments: @dlkibbe @dlounsbu @ljmoody @lijenn 

## New Calendar Design

- [ ] Displaying a whole year provides better context to the length of "Care as Usual."
- [ ] Illustrates the difference between EPB care and Care as Usual.
- [ ] Updated Return-to-Clinic-Visit-Interval icon.

![image](https://github.com/lzim/teampsd/assets/30132017/57706dc3-3b12-4ae8-9b5b-1e38bb9c56a5)

**Comment by dlkibbe** [comment] 2023-08-01 17:35
@jamesmrollins Thanks for the images above. I don't understand the arrow circle plus sign icon. What does that represent?

**Comment by jamesmrollins** [comment] 2023-08-01 17:51
@dlkibbe It is supposed to mean "Return-to-Clinic"

![image](https://github.com/lzim/teampsd/assets/30132017/b19ec043-2ca7-4b97-9a0a-2347c125c5de)

**Comment by jamesmrollins** [comment] 2023-08-01 17:55
@dlkibbe What do you think of this one?

![image](https://github.com/lzim/teampsd/assets/30132017/949c20d6-cc5e-4f66-869e-2cce998df73e)

**Comment by jamesmrollins** [comment] 2023-08-01 23:40
For: @lzim 
Comment: @dlkibbe @dlounsbu @TomRust 

![image](https://github.com/lzim/teampsd/assets/30132017/d3cdf8ac-d708-4c44-bd3c-98346ec36bef)

**Comment by lzim** [comment] 2023-08-09 20:19
**Discussed at sim_ui_workflow 08/9/2023**

**KEY IDEA: Evidence-based episode of care or evidence-based engagement.** 
- [ ] Integrates engagement duration AND return-to-clinic visit interval.

**Comment by jamesmrollins** [comment] 2023-09-13 20:30
@lzim @dkibbe @lijenn @ljmoody 

Latest wireframe

[Sim UI Release 3.7 -Dynamic Dec Dash and Widgets.pdf](https://github.com/lzim/teampsd/files/12601674/Sim.UI.Release.3.7.-Dynamic.Dec.Dash.and.Widgets.pdf)

**Comment by jamesmrollins** [comment] 2023-09-26 14:15
@lzim @dkibbe @lijenn @ljmoody @dlouns

Update on Sankey flow widget.  Below is the current development status.  Still much to do with proportionality and labels. 

![image](https://github.com/lzim/teampsd/assets/30132017/8cb66be1-37f1-4687-a6df-46be18f98173)

**Comment by jamesmrollins** [comment] 2023-10-02 18:54
Action: @lzim and @TomRust 
- [ ] Review and comment
  
FYI: @ljmoody @lijenn 

## New DRAFT Team Care Story - Causal Loop Diagram

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb2IzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a993470e6edb6e7921fc9427c3309a3c05e0cb1b/image.png)

## ## New DRAFT Team Flow Story - Causal Loop Diagram

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcFQzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2addfeba33199a8162ef751bebdba3fbca96540a/image.png)

**Comment by jamesmrollins** [comment] 2023-10-16 01:41
@lzim  FYI
@tejaspesquare latest Widget Wireframe with Team Flow diagram.  I will email EPS files for reference.

[Sim UI Release 3.7 -Dynamic Dec Dash and Widgets.pdf](https://github.com/lzim/teampsd/files/12911298/Sim.UI.Release.3.7.-Dynamic.Dec.Dash.and.Widgets.pdf)

**Comment by ljmoody** [comment] 2023-10-19 16:10
@tejaspesquare - please incorporate the following edits to the dashboard and reach out if anything isn't clear. Thank you ~
FYI: @jamesmrollins @lijenn @lzim 

- [ ] Dropdowns for Array:
<img width="310" alt="Screenshot 2023-10-17 at 4 39 45 PM" src="https://github.com/lzim/teampsd/assets/124643236/fc1a4683-ac8a-4138-bf82-cd672e61e817">

- [ ] Psychotherapy meters:
<img width="854" alt="Screenshot 2023-10-17 at 4 45 29 PM" src="https://github.com/lzim/teampsd/assets/124643236/f194fa67-6490-4861-8632-17846d6abfdd">

- [ ] Psychotherapy Story CLD:
<img width="643" alt="Screenshot 2023-10-17 at 4 47 25 PM" src="https://github.com/lzim/teampsd/assets/124643236/976154b6-8627-4e84-b942-f6279e7e0fd9">

- [ ] Team Flow Story CLD:
<img width="1036" alt="Screenshot 2023-10-17 at 4 48 57 PM" src="https://github.com/lzim/teampsd/assets/124643236/6d79a81b-8690-4130-9fab-31d31ce178e5">

- [ ] Team Care Decisions-Pt Svcs dropdown:
<img width="878" alt="Screenshot 2023-10-17 at 5 04 19 PM" src="https://github.com/lzim/teampsd/assets/124643236/a03131fc-752f-4bd0-870b-2ecf34c5239d">

- [ ] Medication Mgmt Evidence-based Episode of Care text:
<img width="695" alt="Screenshot 2023-10-18 at 4 32 43 PM" src="https://github.com/lzim/teampsd/assets/124643236/30517c7e-d190-4e95-bec0-5691e4181285">

- [ ] Psychotherapy Evidence-based Episode of Care text:
<img width="684" alt="Screenshot 2023-10-18 at 4 33 18 PM" src="https://github.com/lzim/teampsd/assets/124643236/8c48b391-3993-49df-b7e3-d194c1eee2b5">

**Comment by ljmoody** [comment] 2023-10-19 16:20
@jamesmrollins - please review the following changes I wasn't 100% sure about. Once you select the approved -or- do not make sugg'd changes checkboxes for each, I will tag Tejas to incorporate what you see fit.

1. Medication Management stock label:
- [ ] Approved
- [ ] Do not make suggested changes
<img width="670" alt="Screenshot 2023-10-17 at 4 44 53 PM" src="https://github.com/lzim/teampsd/assets/124643236/85477297-7910-4c4f-b030-396efde4a715">

2. Care Coordination Story CLD:
- [ ] Approved
- [ ] Do not make suggested changes
<img width="657" alt="Screenshot 2023-10-17 at 4 46 58 PM" src="https://github.com/lzim/teampsd/assets/124643236/2121d6db-6598-460a-b0d0-69ad4e6474fd">

3. Medication Management Story CLD:
- [ ] Approved
- [ ] Do not make suggested changes
<img width="647" alt="Screenshot 2023-10-17 at 4 47 06 PM" src="https://github.com/lzim/teampsd/assets/124643236/17089bb3-51d0-478f-981d-7a7a0adf81a9">


4. Team Care Story CLD:
- [ ] Approved
- [ ] Do not make suggested changes
<img width="757" alt="Screenshot 2023-10-17 at 4 48 13 PM" src="https://github.com/lzim/teampsd/assets/124643236/f5188020-cb4b-40b6-96cb-925fce97125f">


5. Decision Meters (across the board): 
- [ ] Approved
- [ ] Do not make suggested changes
<img width="959" alt="Screenshot 2023-10-18 at 4 32 11 PM" src="https://github.com/lzim/teampsd/assets/124643236/2a0a9c55-194d-49d8-8443-2a749b347fa8">

FYI: @lzim @lijenn

**Comment by jamesmrollins** [comment] 2023-10-19 18:40
> @tejaspesquare - please incorporate the following edits to the dashboard and reach out if anything isn't clear. Thank you ~ FYI: @jamesmrollins @lijenn @lzim
> 
> * [ ]  Dropdowns for Array:
> 
> <img alt="Screenshot 2023-10-17 at 4 39 45 PM" width="310" src="https://user-images.githubusercontent.com/124643236/276678840-fc1a4683-ac8a-4138-bf82-cd672e61e817.png">
> * [ ]  Psychotherapy meters:
> 
> <img alt="Screenshot 2023-10-17 at 4 45 29 PM" width="854" src="https://user-images.githubusercontent.com/124643236/276678912-f194fa67-6490-4861-8632-17846d6abfdd.png">
> * [ ]  Psychotherapy Story CLD:
> 
> <img alt="Screenshot 2023-10-17 at 4 47 25 PM" width="643" src="https://user-images.githubusercontent.com/124643236/276678918-976154b6-8627-4e84-b942-f6279e7e0fd9.png">
> * [ ]  Team Flow Story CLD:
> 
> <img alt="Screenshot 2023-10-17 at 4 48 57 PM" width="1036" src="https://user-images.githubusercontent.com/124643236/276678921-6d79a81b-8690-4130-9fab-31d31ce178e5.png">
> * [ ]  Team Care Decisions-Pt Svcs dropdown:
> 
> <img alt="Screenshot 2023-10-17 at 5 04 19 PM" width="878" src="https://user-images.githubusercontent.com/124643236/276678925-a03131fc-752f-4bd0-870b-2ecf34c5239d.png">
> * [ ]  Medication Mgmt Evidence-based Episode of Care text:
> 
> <img alt="Screenshot 2023-10-18 at 4 32 43 PM" width="695" src="https://user-images.githubusercontent.com/124643236/276678927-30517c7e-d190-4e95-bec0-5691e4181285.png">
> * [ ]  Psychotherapy Evidence-based Episode of Care text:
> 
> <img alt="Screenshot 2023-10-18 at 4 33 18 PM" width="684" src="https://user-images.githubusercontent.com/124643236/276678930-8c48b391-3993-49df-b7e3-d194c1eee2b5.png">

@ljmoody it looks from your feedback above that I need to include you into an edit step for wireframes.  Can you tell me which wireframe you referenced above.  I just released a new one on Sunday night.

**Comment by jamesmrollins** [comment] 2023-10-19 19:07
@ljmoody  great! I will add you in a a deliberate step next time. Thank you for your initiative!

**Comment by tejaspesquare** [comment] 2023-10-25 14:18
> @jamesmrollins - please review the following changes I wasn't 100% sure about. Once you select the approved -or- do not make sugg'd changes checkboxes for each, I will tag Tejas to incorporate what you see fit.
> 
> @tejaspesquare - Can you also please incorporate edits below that are **approved by James**. Also include any additional "Notes" James made (#s 4 & 5).
> 
> 1. Medication Management stock label:
> 
> * [ ]  Approved
> * [x]  Do not make suggested changes
> * [x]  Note:  You are correct, adding "Patients" would improve clarity.  However, it is named this way throughout the model and documentation, so we will leave it as is.
> 
> <img alt="Screenshot 2023-10-17 at 4 44 53 PM" width="670" src="https://user-images.githubusercontent.com/124643236/276682063-85477297-7910-4c4f-b030-396efde4a715.png">
> 2. Care Coordination Story CLD:
> 
> * [x]  Approved
> * [ ]  Do not make suggested changes
> 
> <img alt="Screenshot 2023-10-17 at 4 46 58 PM" width="657" src="https://user-images.githubusercontent.com/124643236/276682708-2121d6db-6598-460a-b0d0-69ad4e6474fd.png">
> 3. Medication Management Story CLD:
> 
> * [x]  Approved
> * [ ]  Do not make suggested changes
> 
> <img alt="Screenshot 2023-10-17 at 4 47 06 PM" width="647" src="https://user-images.githubusercontent.com/124643236/276683012-17089bb3-51d0-478f-981d-7a7a0adf81a9.png">
> 4. Team Care Story CLD:
> 
> * [x]  Approved
> * [ ]  Do not make suggested changes
> * [x]  Note - Add a note to the bottom with an asterisk ( *RVI - Return-to-Clinic Interval)
> 
> <img alt="Screenshot 2023-10-17 at 4 48 13 PM" width="757" src="https://user-images.githubusercontent.com/124643236/276683057-f5188020-cb4b-40b6-96cb-925fce97125f.png">
> 5. Decision Meters (across the board):
> 
> * [x]  Approved
> * [ ]  Do not make suggested changes
> * [x]  Note;  Yes, Return-to-clinic interval should be hyphenated throughout the boards.  However, keep in mind that it is not standardized as such within the legacy modules, so we need to use care with respect to backwards compatibility with this change.
> 
> <img alt="Screenshot 2023-10-18 at 4 32 11 PM" width="959" src="https://user-images.githubusercontent.com/124643236/276683106-2a0a9c55-194d-49d8-8443-2a749b347fa8.png">
> FYI: @lzim @lijenn

@ljmoody Except Casual Loop Diagrams changes are available in test.  
FYI - @jamesmrollins @lijenn

**Comment by ljmoody** [comment] 2024-02-09 22:38
Hi @jamesmrollins - Jenn and I recommend closing this card because we've created cards and are tracking progress through DEV/TEST/DOC/TRAIN cards for the DDD and its components (_MTL_ Reports, Feedback Loops, Flows, etc.) separately.

**Comment by ljmoody** [comment] 2024-02-13 01:22
Team Praxis has decided this card is closed! :)

**Closed by ljmoody** 2024-02-13 01:22 UTC
Labels: pi, sim_ui, sim ui dev, Development
