### ISSUE TITLE
wk1_june: SP module in SIM giving errors

### ISSUE THREAD

**Issue by hmarcia** [lzim/teampsd#2032] opened 2021-06-03 17:18 UTC
This is the prep from June 3rd with @branscombj and @hmarcia from 8:30 pacific to 10:30 pacific

@hmarcia was in her individual world within the team that this prep is for. 
![image](https://user-images.githubusercontent.com/50675495/120685256-a72aa000-c46d-11eb-8087-7b853df4f051.png)
<img>

![image](https://user-images.githubusercontent.com/50675495/120685459-d9d49880-c46d-11eb-978a-5ba75b6385b7.png)

**Comment by jamesmrollins** [comment] 2021-06-04 05:57
Hi @hmarcia - thanks for reporting this.  I was able to re-create this error and have reported my finding to DEV for further investigation.  We will let you know what we find out soon.  Thanks, James

FYI @staceypark @branscombj

**Comment by dkngenda** [comment] 2021-06-07 17:31
Discussed at 6/7 

- [ ] @jamesmrollins working on the cell SPReferrals tab cell C34 0.1 value angle to see if Vensim/Sim UI can read the table if this is not zero.

**Comment by jamesmrollins** [comment] 2021-06-08 00:09
@hmarcia @lijenn @staceypark @anazariz @branscombj @TomRust 

I was able to recreate this issue in my browser - but only for the facility file in question. The SP Module appears to run ok using other Team Data files. I have noted a floating point error in the client version of the simulation.  Floating point errors are normally created by "division by zero" type of situations.  I have passed this issue to the modeler for assistance.  I am not certain this is the genesis of the error generated by the Sim UI, but it is an independent variable that needs to be brought under control.

- In case the original file was corrupted somehow, I re-download the latest version of the Team Data file that was created during this morning's Workgroup Leads meeting to make the observations shown below.
- I did force-change one of the Team Data (ModelParameters.xlsx) values in cell C34 in the SPParams tab, to reflect a minimum of 1 week.  The Data UI produced a “0” in the original data pull. 
- With the team data file in question and latest version of the SP model running on my client, I get a floating point error for the “Max_transfers_to_GMH_from_PC/PCMHI” variable.  
- This file will not load Team Data properly into the Team Data table of the simulation. I cannot say for sure if the floating point issue is part of the data-value-loading-problem or not, but should be brought under control.  I am investigating the data-value-loading in issue #2033.
- Below are some screen shots of the preliminary investigation. 

![image](https://user-images.githubusercontent.com/30132017/121100652-22ae8900-c7af-11eb-99ac-6c5de1007ad3.png)

**Comment by lzim** [comment] 2021-06-08 21:59
Thanks for working on this @jamesmrollins and consulting with @TomRust  

**Can I confirm with you that you forced a 1 (per your message above), but not 0.1 in the value for SPReferrals tab cell C34?**
I wondered why you tried a 1, rather than the minimum value, given that the calculated value was returned as 0. The difference between 1 and 0.1 may be a big one for this small team.

for this: 
> With the team data file in question and latest version of the SP model running on my client, I get a floating point error for the “Max_transfers_to_GMH_from_PC/PCMHI” variable. 

**I don't see enough of the Vensim file in the screenshot to follow this “Max_transfers_to_GMH_from_PC/PCMHI” path for divisors.**
But, I should be able to check it in the documentation here: https://forio.com/app/va/va-psd-demo/spsdmdoc.html .
And, turn to Vensim DSS if I need to.

I wasn't sure whether you had a good test of the SPParams data with other locations, because this is the only team per @lijenn  and @staceypark that is working with SP this round.

**Comment by jamesmrollins** [comment] 2021-06-09 14:53
Hi @lzim 
FYI @TomRust @lijenn @staceypark 

Sorry I wasn't more clear.  I actually tried the 0.10 value and the 1.0 value.  Neither worked.  Regarding testing other team's data, I have only tested with a test model parameters I normally use for testing.  Yesterday, Tom said he found a "mis-wired" flag and was going to recheck the model for similar mistakes.  I am not sure the mis-wired flag is the culprit yet, but will continue the investigation and report at Support Workgroups.

**Comment by branscombj** [comment] 2021-06-09 14:59
> The difference between 1 and 0.1 may be a big one for this small team.

Just a reminder that it's Kansas City (the huge team) that's interested in SP. (For that reason, I assumed that whatever the limit about too few episodes for a reliable parameter estimate, theirs would surpass it.)

**Comment by jamesmrollins** [comment] 2021-06-09 15:00
@branscombj - I will check out the Kansas file to see if we have a hiccup.

**Comment by jamesmrollins** [comment] 2021-06-09 15:04
@branscombj looks like the huge KC team has not produced a Team Data file yet. Let me know when they get there so I can test.

**Comment by jamesmrollins** [comment] 2021-06-09 17:17
Hi @lijenn @lzim @branscombj @hmarcia 

@TomRust has completed his review and testing of the model.  Below is his report as to the cause of the floating point error.  I plan to update this model in TEST and run on the Sim UI before moving to PROD.

## Findings

One of our “data quality control” wires is crossed. See screenshot, where the SMH flag (which asks “is this start rate based on enough visits to be meaningful”) is controlling the data used for the PC start rate. 

![image](https://user-images.githubusercontent.com/30132017/121399808-ab423c00-c90b-11eb-833f-bc9323713a16.png)

## Analysis

The trick is that the floating point error is not the problem – it’s just a sign that something else is creating HUGE values (or, infinitesimally small values).  Which is usually a sign that a formula is wrong (missing a negative, or multiplying when you meant to divide), or in this case, the parameters are outside the boundary of what we had expected.

In this case, it meant that all the PC stocks that should have been initialized with some # of patients started instead with zero, so the model could never reach equilibrium.  The SMH stocks also were affected, starting with some patients instead of none, but this didn’t break the model as fast as the PC stocks did.

It should be good to go.  I checked all the other data quality flags, and they are all wired correctly.

**Comment by jamesmrollins** [comment] 2021-06-09 22:27
Hi @lijenn @lzim @branscombj @hmarcia @TomRust @anazariz 
I advanced the new model to TEST and tested using 0.10 and 0 for values in the "New Episode of Care Wait Time."  In both instances, the model was stable, loaded table values properly and was able to run to week 104.  **This still doesn't address the issue of the 0.10 minimum for that value in the Team Data Table.** I am assuming that is a Data UI action?



![image](https://user-images.githubusercontent.com/30132017/121437305-ead24d80-c936-11eb-865b-17734db254d7.png)

**Comment by jamesmrollins** [comment] 2021-06-10 21:27
Hi @lijenn @lzim @branscombj @hmarcia @TomRust @anazariz

# Update
I have not promoted this model to PROD yet, because I have an issue with the SDM doc production app.  I do not see any prep sessions for today or tomorrow, so I will resolve this tonight and promote by tomorrow.

Sorry for any inconvenience - James

**Comment by lijenn** [comment] 2021-06-10 21:38
Discussed at hq wg 6/10/21:

@jamesmrollins There is a prep meeting for a team at 4am Pacific with @clairecollie @dlkibbe. They may be interested in SP, but will most likely go with AGG.

**Comment by anazariz** [comment] 2021-06-10 21:45
@jamesmrollins I will create a new ticket for my work (0.1).

**Comment by lijenn** [comment] 2021-06-15 15:18
Discussed at Facil. wg meeting 6/15:
@anazariz to continue work on his .01 bug in the team data table.

**Closed by lijenn** 2021-06-15 15:18 UTC
Labels: dev, quant, sim_ui

**Comment by anazariz** [comment] 2021-06-17 16:17
I have created a new card [2056](https://app.zenhub.com/workspaces/team-psd-workspace-5e4ac9bd8d388dfba6d9aef5/issues/lzim/teampsd/2056)  for my work on this.
