### ISSUE TITLE
MTL Facilitate - OMHSP QIIC Training

### ISSUE THREAD

**Issue by branscombj** [lzim/teampsd#303] opened 2019-01-23 18:27 UTC
To prepare TAS for co-facilitating MTL Live and to develop our MTL Facilitate plan...

2 months is probably a challenging time frame to fully prepare folks who are brand new. TAS have a leg up because of the week intensive they already had. I think if I were designing MTL Facilitate for newbies, I would keep a chunk of intensive training (live if possible), but put it after their participation in
a) a 12-session MTL Live series and
b) completing 36 sessions of MTL Video on their own
This would allow for live role-playing of facilitation in the intensive week, after completing the course as a learner.

I propose that TAS do a and b above and then have some time with TeamPSD to directly discuss facilitation and mechanics. To accomplish this by the end of March could mean something like the below. (I used PSY as a placeholder for the module they do in MTL Live; could be whatever they actually prioritize.) The "pilot" column allows for time they'll need to complete the MTL Video piloting "paperwork" (not part of MTL Facilitate in future.)

Mo | Wk | MTL Live/live mtgs with TeamPSD | MTL Video | Hrs | Pilot
-- | -- | -- | -- | -- | --
Feb | 1 | 1,2,3 | 1,2,3,4,5PSY | 8 | 2
  | 2 | 4,5,6PSY | 6,7,8,9,10PSY | 8 | 2
  | 3 | 7,8,9PSY | 5,6,7,8,9MM | 8 | 2
  | 4 | 10PSY,11,12 | 10MM,5,6,7,8CC | 8 | 2
Mar | 1 | MM,CC | 9,10CC,5,6,7AGG | 8 | 2
  | 2 | AGG,SP | 8,9,10AGG,5,6SP | 8 | 2
  | 3 | Facilitation (3 hrs) | 7,8,9,10SP,11,12 | 8 | 2
  | 4 | Facilitation (3 hrs) | Planning (3) | 6 | 0

For TeamPSD this would mean facilitating one team through the 12-session plan in a compressed, 3 sessions per week time frame. We could take turns co-facilitating, with those not facilitating a given session sitting in as "learners" along with the TAS.

ALTERNATIVELY, we could do Sessions 1,2,3, live/remote with TAS as learners, then do 1,2,3, live/remote with TAS as co-facilitators; etc. Although switching back and forth between Learner and Facilitator was difficult in Chicago, this might be a reasonable compromise and let them lead closer to the time they were exposed to the session, and give them facilitating practice as we go along rather than all at the end.

**Comment by dlkibbe** [comment] 2019-01-24 02:19
Thanks for this summary @branscombj - Question: for the R01 study would @lzim and @TomRust do the Audit & Feedback clinics since they facilitated the data sessions?

**Comment by branscombj** [comment] 2019-01-29 19:45
To your question, @dlkibbe , probably not, because in MTL Live, each TeamPSD member co-facilitates _all_ of the sessions (1-12) along with one TAS. And it will probably fit the research design best for the A&F teams to be co-facilitated by one TAS and one TeamPSD member just as the 12-session plan teams are.

**Comment by lzim** [comment] 2019-03-02 02:27
Hi Everyone - HAPPY WEEKEND! :smiley_cat: 

Moving @branscombj's update for all of Team PSD Co-Facilitators to GitHub:
- @dlkibbe @dlounsbu @TomRust and @staceypark 

**Jane says:**
We have a Lucid meeting template for our meetings with TAS to conduct MTL Live with them. (Thank you Stacey for your help and for finishing it up!) For admin tasks in Lucid, we have to use LZ’s login credentials, which are in the Lucid notes from yesterday’s MTL Launch meeting.

We will use mtl.how/live (Adobe Connect) for video, but unlike national roll-out, we will use Lucid for audio instead of VANTS.

**Lindsey Clarifies:**

1.  For this week, @staceypark and I will make sure the Lucid invite goes out on Monday - with instructions and a link to the session 1 pre-email.
2. @staceypark and I will set up a template for these Wednesday _MTL Facilitate_ sessions so that **Facilitate Workgroup Co-Leads** just grab that template, adapt it for the week (purpose, outcomes  agenda) and send it out. 
3. In March, for our review of the 12-session plan with OMHSP TAS co-facilitators in **learner mode** for _MTL Live_ we plan to consistently use this GENERAL FORMAT:

- Schedule 2 hours for each session like we will during the roll-out
- Break out so that Team PSD **co-facilitators** do the 30 minute pre/post checklists for the session
- Concurrently the OMHSP TAS **learners** will do the "DO" from the standard pre/post emails during the same time period (e.g., the TAS do their session 1 pre-meeting “DO" in the first 30 minutes; and while we de-brief they complete the intersession "DO." 

**NOTE:** We may NOT want the TAS to focus on the pre-session 2 DO next week, as @holbrooa is still working to prep updates to the data UI code. We should have an update regarding this on Monday.

**Back to Jane:**
- For next week, Tom and Jane will co-facilitate Session 1. 
- For Session 1 their pre-work is just to join the audio and video. 

Hope everyone has a wonderful weekend it's already MARCH :cherry_blossom:

**Comment by staceypark** [comment] 2019-03-07 20:50
@lzim @dlounsbu @dlkibbe @TomRust @branscombj 
Given that we plan on doing 2 sessions per week, I'm wondering if the meeting structure would look like:
1) 30 min pre + 60 min session + 30 min post + 30 min pre + 60 min session + 30 min post
or 
2) 60 min pre + 120 min session + 60 min post

Option 1 makes more sense to me in terms of keeping it consistent to how we rollout with the teams and esp for the do/done from the learner end. Thoughts?

**Comment by branscombj** [comment] 2019-03-07 21:27
@lzim @dlounsbu @dlkibbe @TomRust @staceypark I agree; your option 1 makes more sense to me too. I'm just not sure if the TAS are going to be able to set aside 4 hours at a time to do 2 sessions in one sitting. 

If we could get two one-hour slots with them per week, we could let them do the between-session DOs on their own - more flexibility that way - and we'd complete mtl live in 6 weeks.

Even better if we could swing three (MWF) one-hour sessions per week and get through mtl live in 4 weeks!

I'm not sure the schedule for TAS to watch mtl video. I'd say they should watch the session just completed live in addition to the between-session DO - but then their piloting wouldn't be done until close to the end of their training.

For mtl facilitate in general, we should go about a more methodical outline of learning content; but to start off, I'm going to propose a 5-part concept (feel free to suggest better names for these!):
**A. Live:** Complete the mtl live 12-session plan as a learner.
**B. Video:** Complete the mtl video 36 sessions as a pilot reviewer. (Future cohorts of mtl facilitate _might_ only do, as learners not piloters, the videos of Sessions 5-10 in the modules they didn't do in live.)
**C. Admin:** Learn the back-end tasks of modeling to learn. (could be learned by doing in conjunction with D)
**D. Practice:** Co-facilitate at least 6 sessions of the 12-session plan, complete with half-hour co-facilitator prep, half-hour co-facilitator post-session debrief, and additional, 1-hour group discussion.
**E. Study:** Read designated background/mtl materials.

**Comment by dlounsbu** [comment] 2019-03-08 19:59
Not sure where we are with respect to finalizing the MOU for training TSA members. I did not see a specific meeting schedule for the training yet. I am hoping that there is a way to build in some level of flexibility and/or redundancy in scheduling, so that when one of us has a conflict, there is a way to reschedule and/or arrange a substitute that keeps the training moving forward and keeps everyone up to date. Thoughts?

**Comment by staceypark** [comment] 2019-03-15 00:09
@dlkibbe @dlounsbu @branscombj @TomRust @lzim 
Based on the poll, here's where we landed for the March schedule (times in Pacific).
This is what the teampsd and tas availability look like so far:

Time | Session | TeamPSD | TAS
-- | -- | -- | --
Wed 3/20 @7:30am | Session 1 | Lindsey, Debbie, Jane, Tom, Stacey | Gayle, John, Marcia, Matt
Wed 3/20 @11:30am | Session 1| Lindsey, David, Debbie, Jane, Tom, Stacey | Marcia, Matt, Theresa
Thurs 3/21 @11:30am | Session 2|  Lindsey, Debbie, Jane, Stacey | Gayle, John, Matt, Theresa
Mon 3/25 @9:30am | Session 3| Lindsey, Debbie, Jane, Tom, Stacey | Gayle, John, Theresa

Note, we are doing Session 1 twice on Wednesday

**Comment by lzim** [comment] 2019-04-12 00:59
@staceypark  @branscombj @dlkibbe @dlounsbu @TomRust 

Below is the updated/confirmed April and May schedule that we discussed this morning.
We will be updating the TAS and sending around invites soon.

We also aim to get the June/July schedule set up ASAP.

Thanks!


Role | Date | Time | Content | Link
-- | -- | -- | -- | --
Learner | Mon 4/15 | 09:30a PST / 12:30p EST | Session 6 | https://meet.lucidmeetings.com/meeting/211360
Learner | Mon 4/18 | 09:30a PST / 12:30p EST | Session 7 | https://meet.lucidmeetings.com/meeting/211361
Learner | Wed 4/24 | 09:30a PST / 12:30p EST | Session 8 | https://meet.lucidmeetings.com/meeting/211363
Learner | Fri 4/26 | 11:30a PST / 02:30p EST | Session 9 | https://meet.lucidmeetings.com/meeting/212078
Learner | Mon 4/29 | 11:30a PST / 02:30p EST | Session 10 | https://meet.lucidmeetings.com/meeting/211365
Learner | Wed 5/1 | 07:30a PST / 10:30a EST | Session 11 | https://meet.lucidmeetings.com/meeting/212081
Learner | Wed 5/8 | 07:30a PST / 10:30a EST | Session 12 | https://meet.lucidmeetings.com/meeting/212211
Co-Facilitator | 09:30a PST / 12:30p EST | Learner Debrief & CoF Plan | https://meet.lucidmeetings.com/meeting/212966
Co-Facilitator | Fri 5/17 | 09:30a PST / 12:30p EST | Session 1 | https://meet.lucidmeetings.com/meeting/212213
Co-Facilitator | Wed 5/22 | 07:30a PST / 10:30a EST | Session 2 | https://meet.lucidmeetings.com/meeting/212214
Co-Facilitator | 09:30a PST / 12:30p EST | Session 3 | https://meet.lucidmeetings.com/meeting/213103

**Comment by lzim** [comment] 2019-05-11 00:11
@staceypark @branscombj @dlkibbe @dlounsbu @TomRust @holbrooa @jamesmrollins @clairecollie @MattMoore2 @theresaschmitz 

Hi Everyone,

We're working on where to indicate who will miss parts of the May/June/July training schedule.
Here's a first draft of a table for that, until we can come up with something better.
- You can click the edit button and indicate when you will miss

  |   |   |   |  
-- | -- | -- | -- | --
Week | Session | #manuscriptmondays | Wed Intersession Prep  | Fri   Co-Facilitation Practice
MONDAY | PT 9:30-11:30 / ET 12:30-2:30 | FRIDAY
May 13-15-17 | S2 |   |   |  
May 20-22-24 | S3 |   |   |  
May 27-29-31 | S5 | Memorial day holiday - no   meeting |   |  
Jun 3-5-7 | S6 |   |   |  
Jun 10-12-14 |   |   | F2F Travel | In person
Jun 17-19-21 |   | In person | F2F Travel |  
Jun 24-26-28 | S7 | Lindsey & David out  | Lindsey & David out  |  
Jul   1-3-5 | July 4th holiday - no meetings this week  | 
Jul   8-10-12 | S8 |   |   |  
Jul   15-17-19 - DESIRED R01 LAUNCH WEEK | S9 |   |   |  
Jul   22-24-26 | Most of Team PSD at System Dynamics Society
Jul   29-31 Aug 2  | S10 |  Lindsey out | Lindsey out  | Lindsey out |

**Comment by MattMoore2** [comment] 2019-05-11 20:10
Hi Lindsey and Team – I’m trying to figure out how to edit this – wondering if some formatting is missing/not showing up in Outlook?  I don’t see an “edit button”…

**Comment by lzim** [comment] 2019-05-13 17:03
@MattMoore2 

Great question, the edit button is available under the ellipsis ... see screenshot 😸 
![edit_button](https://user-images.githubusercontent.com/7454688/57640053-45d1c480-7566-11e9-9108-8198905336e6.png)

**Comment by jwklocek** [comment] 2019-05-22 17:23
@lzim with the exception of 10 - 11 PT, I'll be available on 6/17

**Comment by gyiwamasa** [comment] 2019-05-22 17:23
@lzim tropical drink

**Comment by branscombj** [comment] 2019-05-22 17:23
@lzim I'll be in Menlo Park!

**Comment by gyiwamasa** [comment] 2019-05-22 17:24
where is my emoji?

**Comment by theresaschmitz** [comment] 2019-05-22 17:24
@lzim I'm out the week of June 3-7 as well. 
🍹

**Comment by gyiwamasa** [comment] 2019-05-22 17:24
:tropical_drink:

**Comment by MattMoore2** [comment] 2019-05-22 17:24
🍹

**Comment by gyiwamasa** [comment] 2019-05-22 17:24
:cheese:

**Comment by MattMoore2** [comment] 2019-05-22 17:25
🥇 🍹

**Comment by lzim** [comment] 2019-05-22 17:25
💯

**Comment by theresaschmitz** [comment] 2019-05-22 17:26
@gyiwamasa 🍹

**Comment by branscombj** [comment] 2019-05-22 17:48
> Hi Lindsey and Team – I’m trying to figure out how to edit this – wondering if some formatting is missing/not showing up in Outlook? I don’t see an “edit button”…

Hi @MattMoore2 - I think @lzim may have told you on the phone - but for anybody else who wonders, you can edit your own comment using one of the options at the 3 dots at top right beside the smiley face. 
We typically follow a norm of not editing *other* people's comments; instead, you can use the 3 dots "quote reply", which is what I did here.
An exception, of course, is where we're all putting our own input into a group message like the schedule table in this issue.

**Comment by lzim** [comment] 2019-05-22 18:38
@branscombj is right (I'm "quote replying" her here):

> We typically follow a norm of not editing _other_ people's comments; instead, you can use the 3 dots "quote reply", which is what I did here.
> An exception, of course, is where we're all putting our own input into a group message like the schedule table in this issue.

It is **_rare_** that we edit each other's comments, but sometimes we do need to do so.
🌺

**Comment by jessfroe** [comment] 2019-07-10 15:30
@lzim @staceypark 
I noticed that September 2nd (Labor Day) is included in this schedule and it is indicated that we are meeting for #manuscriptmondays. Should this be updated? I'm assuming Labor Day is a holiday.

**Comment by branscombj** [comment] 2019-07-10 15:34
> @lzim @staceypark
> I noticed that September 2nd (Labor Day) is included in this schedule and it is indicated that we are meeting for #manuscriptmondays. Should this be updated? I'm assuming Labor Day is a holiday.

Yes, 9/2 is a holiday; we should not have anything scheduled. Also @staceypark I notice that most of my recurring Lucid appointments end in August.

**Comment by jessfroe** [comment] 2019-07-10 15:36
@branscombj 
Thanks, Jane!
@staceypark and I will make sure the meetings continue past August.

**Comment by branscombj** [comment] 2019-08-01 14:31
Hi all! @clairecollie @MattMoore2 @gyiwamasa @jwklocek @theresaschmitz @dlkibbe @staceypark @jessfroe @dlounsbu @TomRust @lzim 
Debbie put a question in the Lucid Meeting notes yesterday that I don't think got answered. My understanding is that **YES, our Friday practice sessions are designed to be full run-throughs including opening and closing Done/Do reviews.** 
p.s. Is **(at)hmarcia** "our" Marcia? I didn't ping it because I wasn't sure.

**Comment by jessfroe** [comment] 2019-08-01 15:34
@branscombj I think we need @staceypark 's input here - my latest impression is that the facilitation practice should be to only focus on the middle "meat" of the session, excluding opening and done/do review. But, we should get further clarification to be sure.

**Comment by branscombj** [comment] 2019-08-01 15:59
> @branscombj I think we need @staceypark 's input here - my latest impression is that the facilitation practice should be to only focus on the middle "meat" of the session, excluding opening and done/do review. But, we should get further clarification to be sure.

Thanks, @jessfroe . Yes, let's see what @staceypark says. My impression was that we focus Intersession Prep on the 30-minute in-session exercise but still do the whole session on Friday. But that may be wrong.

**Comment by staceypark** [comment] 2019-08-01 16:09
@clairecollie @MattMoore2 @gyiwamasa @jwklocek @theresaschmitz @dlkibbe @staceypark @jessfroe @dlounsbu @TomRust @lzim @branscombj @hmarcia (hmarcia is our Marcia!)

Yes, @branscombj is correct. 
Wednesday's Prep hour focuses only on the **middle 30 min "meat" of the session.**
Friday's co-facilitation hour is a run-through of the **entire session including done/do review & the in-session exercise**

**Comment by staceypark** [comment] 2019-09-04 16:49
Session | 2 | 3 | 4 | 5 | 6
--- | --- | --- | --- | --- | --- |
Date | 7/19 | 8/2 | 8/9 | 8/23 | 8/30
Co-F | Gayle, Debbie | Theresa, David | Lindsey, David| David, Gayle | Jane, Claire
Team | Lindsey, Theresa, John | Debbie, Gayle, Jessilyn, Jay | Jane, Debbie, Matt, Stacey | Jessilyn, Theresa, Stacey, Jay | Gayle, Jessilyn, David
Prep | Lucid | Lucid | Adobe | Adobe no audio | not backed | 
Live Co-F | Lucid | Lucid | Adobe backup error | not backed | not backed

Session | 2 | 3 | 4 | 5 | 6
--- | --- | --- | --- | --- | --- |
Date | 7/19 | 8/2 | 8/16 | 8/23 | 8/30
Co-F | Tom, Claire | Jane, Matt | Tom, Marcia | Jane, Tom | Tom, Marcia
Team | Marcia, Stacey, Jessilyn | Marcia, Claire, Stacey | Gayle, Jane, Theresa, Lindsey, David, Tom, Debbie, Jessilyn, Stacey | Claire, Matt, Jane | Debbie, Stacey, John
Prep | Adobe | Adobe no audio | Adobe | Lucid | not backed | 
Live Co-F | Adobe | Adobe no audio | Adobe  | not backed | not backed

**Comment by branscombj** [comment] 2019-09-04 16:57
Hey @staceypark this  is awesome! Thank you for tracking. I do think it's helpful to have a reality check on who's done what.

**Comment by branscombj** [comment] 2019-09-04 18:51
Team | Session | Date | Gayle | Theresa | Claire | John | Jay | Matt | Marcia | Jane | Debbie | David | Lindsey | Tom | FAC total | tm total
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
2 | 2 | 7/19 | FAC | tm |   | tm |   |   |   |   | FAC |   | tm |   | 2 | 3
4 | 2 | 7/19 |   |   | FAC |   |   |   | tm |   |   |   |   | FAC | 2 | 1
2 | 3 | 8/2 | tm | FAC |   |   | tm |   |   |   | tm | FAC |   |   | 2 | 3
4 | 3 | 8/2 |   |   | tm |   |   | FAC | tm | FAC |   |   |   |   | 2 | 2
2 | 4 | 8/9 |   |   |   |   |   | tm |   | tm | tm | FAC | FAC |   | 2 | 3
4 | 4 | 8/16 | tm |   |   |   |   |   | FAC | tm |   |   |   | FAC | 2 | 2
2 | 5 | 8/23 | FAC | tm |   |   | tm |   |   |   |   | FAC |   |   | 2 | 2
4 | 5 | 8/23 |   |   | tm |   |   | tm |   | FAC |   |   |   | FAC | 2 | 2
2 | 6 | 8/30 | tm |   | FAC |   |   |   |   | FAC |   | tm |   |   | 2 | 2
4 | 6 | 8/30 |   |   |   | tm |   |   | FAC |   | tm |   |   | FAC | 2 | 2
  |   | FAC total | 2 | 1 | 2 | 0 | 0 | 1 | 2 | 3 | 1 | 3 | 1 | 4 |   |  
  |   | tm total | 3 | 2 | 2 | 2 | 2 | 2 | 2 | 2 | 3 | 1 | 1 | 0 |   |

**Comment by ritahitching** [comment] 2019-09-06 16:59
**Possible addition to the Training Manual**

Recording options: Lucid (audio only) or Adobe (audio & visual) or Skype (audio only)
Recording issues: Ensaure breakout sessions occur in Skype - as Adobe is only able to record the meeting host's screen / audio
Hosting & Scheduling Meetings: Use Lindsey account
Attending Meetings: Use own account

Each Lucid meeting invitation needs to include #303 `https://github.com/lzim/teampsd/issues/303` ranking the training links with the most recent first

**Adobe File Naming Convention"

Session_Team_training_date 
**Example** S06_t2_mm_2019_09_06**
Session: always minimum of 2 digits starting 01
Team: options include t2 (team 2) or t4 (team 4)
Training: MM (Manual Monday) or FF (Fidelity Friday) or WW (WWednesday) 
Date: YYMMDD

Ensure that audio / visual is posted to **BaseCamp** and **follow up email** is sent

**Comment by branscombj** [comment] 2019-09-06 17:01
It wouldn't break anything if we renamed this issue OMHSP IC Training (vs. TAS)? I need all the reinforcement I can get to make the switch!

**Comment by lzim** [comment] 2019-09-07 00:53
Done!

**Comment by lzim** [comment] 2019-09-23 22:25
@ritahitching 

- Will you please update the "tm" portion of @branscombj's table to reflect last week?
- I see you have it in @staceypark's table, which is great.

Thanks!

**Comment by lzim** [comment] 2019-09-23 22:26
@ritahitching and @staceypark 

- Can you confirm whether the "not yet in 000" are actually correct for session 6? Thanks!

**Comment by ritahitching** [comment] 2019-09-23 23:05
@lzim and @staceypark just double checked the 000 folder - we have no audio or visual for Session 6 intersession-prep dated 08/28 - table updated

**Comment by staceypark** [comment] 2019-10-02 18:58
@MattMoore2 @theresaschmitz @clairecollie @jwklocek @gyiwamasa @dlkibbe @branscombj @dlounsbu  
It looks like the OOO schedule isn't the most up to date for some folks. We are missing folks at meetings that have not indicated they will be out. Please double check and make sure your piece of the schedule is up to date. Thanks

**Comment by MattMoore2** [comment] 2019-10-03 12:58
Hi Stacy – I’ve “lost” where that schedule is located – could you send directions or link so I can find it again?

Thanks.

**Comment by ritahitching** [comment] 2019-10-03 14:58
hi Matt,
I believe the schedule is in issue 303 (
https://github.com/lzim/teampsd/issues/303)
thanks,
Rita
Rita Hitching
650-283-4871

**Comment by MattMoore2** [comment] 2019-10-03 15:15
Thanks, I will book mark that as this is kinda buried.

**Comment by lzim** [comment] 2019-10-03 15:38
@ritahitching and @staceypark 

Will you please clean up and remove the email details from Matt’s comment?
- We need to orient the ICs to this. 

After we get the latest updates, let’s consider closing #303 and opening a fresh schedule issue with 3 tables in it.
- The schedule also needs to be updated in the **team_tracker** schedule. 

Let’a cover this in a huddle today

**Comment by ritahitching** [comment] 2019-10-03 15:56
@lzim @staceypark comments from Matt updated.

**Closed** 2020-02-12 00:05 UTC
