### ISSUE TITLE
ANDON wk2 2024_06 - Cannot login to Sim UI with administrator or facilitator login

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#3181] opened 2024-06-08 02:21 UTC
**wk1 2024_06 #sim_ui_workflow - Unable to login to Sim UI** 
@jamesmrollins 
@tejaspesquare 
@ljmoody 
@lijenn 

@lzim tried to prep _MTL 3.7 Blue_ consult today.
Could not get the Sim UI to allow login via Chrome on VA FGE laptop - Inspector console below.
Also saw a mix of old teams in my drop-down, which I cannot display via screenshot.
FYI: 
@dlkibbe 
@dlounsbu 

![image](https://github.com/lzim/teampsd/assets/7454688/93e04fda-443b-4f00-8edc-10624487e997)

**Comment by lzim** [comment] 2024-06-08 02:30
Also rebooted completely and got this: 

![image](https://github.com/lzim/teampsd/assets/7454688/6339ba30-3239-4878-ae2e-f4b2cb328ffd)

**Comment by tejaspesquare** [comment] 2024-06-10 05:30
Hello @lzim,

Last week we encountered a login problem with a few test accounts on the Development and Test environments, which was due to unauthorized access (DELETE API issue). Fortunately, this issue was resolved with assistance from David of the Forio Team. 
We have also confirmed that several accounts on the production environment are now working properly. 
Should the problem persist, could you please provide your credentials so that we can troubleshoot the login issue with your account.

FYI - Until the problem is resolved permanently, we have made the decision to refrain from performing any deletion actions on both the Group and its members.

Thanks!

**Comment by ljmoody** [comment] 2024-06-10 14:32
Thank you for responding, @tejaspesquare. Can you clarify what you mean by 
> We have also confirmed that **several** accounts on the production environment are now working properly.

This sounds [to me] like only a few accounts in PROD are working correctly - not the majority. Is this correct? Can prepping for consults happen in PROD?  FYI: I am able to log in to PROD this morning. 
Are the TEST and DEV login issues resolved now?

Please provide another comprehensive update on this issue card during/at the end of your next workday
@jamesmrollins @lijenn @lzim

**Comment by lzim** [comment] 2024-06-10 14:59
Thanks @tejaspesquare & @ljmoody 
I’m on a plane for the next four hours, but as long as the WiFi works okay, I’ll test my login again. 

I’ll send you my login information on the Secure research repo in case someone would be able to test my login sooner. 

Thanks again!

**Comment by ljmoody** [comment] 2024-06-10 16:22
@lzim I _successfully logged into PROD with your credentials._ 
I took a screenshot of the dropdown and blurred site ID info; if these need to be removed or addressed in some way, please let @tejaspesquare know:
![image](https://github.com/lzim/teampsd/assets/124643236/87b25a01-23f8-4647-96eb-4e02e8d32707)
Moving card to Under Development.

**Comment by lzim** [comment] 2024-06-10 19:34
Thanks @ljmoody 

- Since there are no longer facilitator roles or the word “facilitator” anywhere in _MTL 3.7_, there is only “administrator” access, I’m not sure why I or anyone would see “facilitator.”
- I also don’t believe I or anyone is supposed to be seeing any teams in their drop down. Rather in _MTL 3.7_ you select teams only from within the Administrator dashboard. 

FYI: @dlkibbe & @dlounsbu

**Comment by ljmoody** [comment] 2024-06-10 21:37
@tejaspesquare, per Lindsey's comment directly above re: **PROD instance**:
- [ ] When will the **facilitator_login** dropdown choice be removed?
- [ ] When logging in, are users supposed to see teams in addition to the administrator_login choice? Is this part of the "several accounts on the production environment are now working properly" you mentioned above - that this is not currently working properly? Trying to gain a better understanding.

**Comment by tejaspesquare** [comment] 2024-06-11 05:39
Hello @ljmoody ,

> This sounds [to me] like only a few accounts in PROD are working correctly - not the majority. Is this correct? Can prepping for consults happen in PROD? FYI: I am able to log in to PROD this morning. Are the TEST and DEV login issues resolved now?

In my previous post, I mentioned that we have utilized the Delete API (provided by Forio) for a specific functionality. Initially, we encountered a login issue after removing a member from the team through the "Settings -> Team Setup" option. Later, we also experienced a login issue after deleting a test group (for SME development) which affected some default members of it, including yourself.
The login issue has been resolved for both the Development and Testing environments. However, it is important to note that the Delete API call had an impact on users' ability to access their respective teams/groups, regardless of the environment (e.g. Development, Testing, Production, etc.).

Currently, we are actively investigating this matter in coordination with David from the Forio Team.

**Comment by tejaspesquare** [comment] 2024-06-11 06:00
Hello @lzim , @ljmoody ,

> * Since there are no longer facilitator roles or the word “facilitator” anywhere in _MTL 3.7_, there is only “administrator” access, I’m not sure why I or anyone would see “facilitator.”
> * I also don’t believe I or anyone is supposed to be seeing any teams in their drop down. Rather in _MTL 3.7_ you select teams only from within the Administrator dashboard.


We have initiated the implementation of this requirement (to hide Facilitator on SIM UI) and are currently conducting an impact analysis to ensure that this fix does not impact the existing functionality in any way.

It is normal to observe the presence of certain teams on the world selection dropdown when you log in. This occurrence is expected because you do not possess the Facilitator role (on Epicenter) for those particular groups.

![image](https://github.com/lzim/teampsd/assets/144898781/9df47e1a-1f34-46cd-9420-74e227f7aa2d)

**Comment by tejaspesquare** [comment] 2024-06-11 13:03
Hello @lzim , @ljmoody ,

> to hide Facilitator on SIM UI

The necessary modifications have been implemented and can now be tested on the Test-slow platform.

**Comment by ljmoody** [comment] 2024-06-11 20:39
@tejaspesquare, I verified the "facilitator" dropdown choice is removed from TEST instance. Please migrate to PROD when possible as long as doing so does not impact the existing functionality in any way.

![image](https://github.com/lzim/teampsd/assets/124643236/cd8e42e5-3c73-4fa9-a360-455acfe1f3e3)

fyi: @lzim

**Comment by ljmoody** [comment] 2024-06-11 20:54
@tejaspesquare, regarding the Delete API issue, I'm unsure of how to robustly test whether this is functioning properly. 

Here's what I did: 
1. Logged into TEST using VA credentials. 
2. Edited laura_june_testing_team by removing my Praxis member self. 
3. Kept my Praxis self as a member on the laura_june_testing_ind team:
![image](https://github.com/lzim/teampsd/assets/124643236/fa28b2e3-937d-47de-8d46-f3aff2a02fd4)

4. Logged off and back in using my Praxis account, where I see the laura_june_testing_ind team listed in the login dropdown:
![image](https://github.com/lzim/teampsd/assets/124643236/c20fcb52-2f9d-4325-bcf7-95969c0c11bf)

5. I do not see the above _ind team listed under Settings > Facility Team Setup, likely because I was listed as "team lead", correct?
![image](https://github.com/lzim/teampsd/assets/124643236/3a4176cc-27a7-4016-91ea-1ebdc0552098)


Unsure if this is proof of anything - or not...

**Comment by tejaspesquare** [comment] 2024-06-12 07:31
Hello @ljmoody 

> @tejaspesquare, regarding the Delete API issue, I'm unsure of how to robustly test whether this is functioning properly.

The results you have obtained are indeed accurate.
The system is handling the functionality in the following manner.
1. If you hold the Administrator role in any group, along with added into 'administrator_login' on Epicenter -
    i. You will be allowed to login as 'administrator_login' world.
    ii. Otherwise, it will load teams & on selection you will be redirected to Home screen & bypassing the Dashboard. 
2. Teams under Settings -> Facility Team Setup: 
    i. When you log in, only the teams that you have joined and have the 'Administrator' role will be shown.
    ii. 'Lead' & 'Member' permissions teams won't be visible for logged in user.

**Comment by tejaspesquare** [comment] 2024-06-12 12:09
Hello @ljmoody ,

This is to inform you that during the migration process of the latest development to Production, we would like to bring the following matter to your attention.

According to the communication, you have listed following features that need to be moved.
  i. #2993- MTL support Directives
  ii. #3181- Remove 'facilitator_login' choice to remove from login world

There are a few more fixed components that must be included with the above items, as it is essential to handle them within the same source files.
  i.   #3154 Member deletion confirmation message (during & after creation team)
  ii.  #3123 SME-This link will be hidden & written code won't impact other operations.
  iii. #3154 Recent Team setup changes
  iv. Alert message for Groups (Administrator_login) -- I will put separate note in this card

Kindly advise.

FYI - @jamesmrollins

**Comment by tejaspesquare** [comment] 2024-06-12 12:28
@jamesmrollins, @ljmoody - would like to have your confirmation whether this feature is required on not. 
Kindly verify on Test-slow.

When you are added into 'administrator_login' on Epicenter & NOT holding an 'Administrator' role in any group then we will display this alert message to user. On close popup, user is redirected to login screen.

![image](https://github.com/lzim/teampsd/assets/144898781/54443b97-c111-4114-af23-06db7593fe2b)

![image](https://github.com/lzim/teampsd/assets/144898781/382f9da5-6962-42f9-85ea-4d0965f63483)

If this looks ok, then please suggest text as well.
![image](https://github.com/lzim/teampsd/assets/144898781/1eb5bf02-ea07-4ae0-b2b9-ab9af664c3b9)

**Comment by ljmoody** [comment] 2024-06-13 19:16
✅ Facilitator login has successfully been removed from PROD login.
Any Team Setup issues, if they remain, will be tracked via #3154.

fyi: @lzim, @dlkibbe, @dlounsbu, @jamesmrollins

**Comment by ljmoody** [comment] 2024-06-13 19:17
✅ Facilitator login has successfully been removed from PROD login.
Any Team Setup issues, if they remain, will be tracked via #3154.
Closing this card.

fyi: @lzim, @dlkibbe, @dlounsbu, @jamesmrollins

**Closed by ljmoody** 2024-06-13 19:17 UTC
Labels: sim_ui, urgent, sim ui dev, bug
