### ISSUE TITLE
mar_epic: Story H, Story B, Story Hawaii:  Team PSD & Demo Website Updates

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#2875] opened 2023-02-11 20:26 UTC
@jamesmrollins 
@emilymetcalf114 
@epearman 

Tasks below support Portfolio & Education Value Streams
Story H: Hiring and Growth
Story B: 2023 Roadmap
Story Hawaii: Plan, Act, Reflect (PAR) Cycles & Launch

Divvy up tasks below based on available velocity.
Anyone can do these through Forio Epicenter.

### Tracking a set of tasks for mar_epic 2023 to update the following on [mtl.how/team](https://mtl.how/team) :

- [x] Update the link to the updated R&D manager job post
- [ ] Add the link to the Data Scientist USA Jobs job post when available
- [ ] Update the Maps & Sections to reflect the updated terminology and roles of Team PSD members, e.g.,: 
- [ ] Add Consultants or use Consultants instead of Facilitators
- [ ] Add new ILEAD Partners: Anne PM, Carl Producer
- [ ] Update any details
- [ ] Add the 2022 Growth Award winner, Jenn Li
- [ ] Add the 2022 Team Award winners, Emily P & Emily M

### Both [mtl.how/team](https://mtl.how/team) and [mtl.how/demo](https://mtl.how/demo) #crossref #2957
- [ ] Add the SAMSHA grant link to the top paragraph with the other grants
- [ ] Add the SAMSHA, Hawaii DOH/CAMHD Logos to the appropriate sections

**Comment by epearman** [comment] 2023-05-01 16:50
#ajudicate_memo this card is a duplicate of #2886

**Closed by epearman** 2023-05-01 16:50 UTC
Labels: Duplicate
