### ISSUE TITLE
ALL: Output Charts not displaying the quarter before experiments start

### ISSUE THREAD

**Issue by TomRust** [lzim/teampsd#729] opened 2019-09-26 20:39 UTC

**Comment by TomRust** [comment] 2019-09-26 20:41
What happened to showing the quarter before the experiment in the output charts?  We start all model in negative time so that we can do this, to provide a sense of the equilibrium value before the experiment starts.  See screen shot below, comparing the output charts have recorded in the videos to the current state:

![image](https://user-images.githubusercontent.com/32961420/65723458-70876a00-e07c-11e9-9444-4e95cb155cc1.png)

**Comment by jamesmrollins** [comment] 2019-09-26 20:59
@TomRust sorry, but this was designed out with the ReportOffset function that we had to implement to limit file run size. We now just start with "Today."

**Comment by lzim** [comment] 2019-09-26 23:56
> @TomRust sorry, but this was designed out with the ReportOffset function that we had to implement to limit file run size. We now just start with "Today."

Yes, @jamesmrollins made us away of this as Forio required it of us. The models load much faster, which is nice.

Do you have a concern though, @TomRust ?  In terms of what to address with the learners and facilitators?

**Comment by TomRust** [comment] 2019-09-27 14:16
@lzim -- It just makes it harder to use the Output charts in the papers.  The SD reviewer will be expecting us to show some "before experiment" results on our charts of behavior over time.  It's a standard in the field, like labeling feedback loops in a model diagram (i.e., not necessary for function, but expected).

**Comment by TomRust** [comment] 2019-09-27 14:20
AND - @lzim & @jamesmrollins  -- 
Why did we apply this to all models? Only PSY and SP have long initialization periods that we don't show to the users.  CC, MM, and AGG all start in equilibrium, so we're only cutting the file size by ~10% there.

**Comment by lzim** [comment] 2019-09-27 14:32
> @lzim -- It just makes it harder to use the Output charts in the papers. The SD reviewer will be expecting us to show some "before experiment" results on our charts of behavior over time. It's a standard in the field, like labeling feedback loops in a model diagram (i.e., not necessary for function, but expected).

@TomRust I see, so we will struggle to publish these using the Sim UI output as we’d hoped. That’s a big deal. 
- And, the convention exists to help interpret the experiment, so it’s valuable for learners/facilitators too.

> AND - @lzim & @jamesmrollins --
Why did we apply this to all models? Only PSY and SP have long initialization periods that we don't show to the users. CC, MM, and AGG all start in equilibrium, so we're only cutting the file size by ~10% there.

@jamesmrollins My understanding at the time was that we had to make this change.
@TomRust is raising Scientific (e.g., SD scientific reviewers) and Pragmatic (i.e., file size) points for CC, MM, AGG to recover the view of the quarter before the experiment. 

Is there anyway to do that when file sizes are smaller?

**Comment by TomRust** [comment] 2019-09-27 15:04
@jamesmrollins -- I thought that this Report Offset function was going to cut out all the time before week -13 from the file, not all the time before week zero.  Is that not possible, or does this feature only work at time zero?

**Comment by jamesmrollins** [comment] 2019-09-27 23:21
@TomRust I am little frustrated by this - I gave this almost two weeks for review before implementing over a month ago.  With that said, here are some options:

1.  We remove the report_offset function from the TEST environment.  We would have to change the chart code to add the "Today" line.  @TomRust can then do runs and screen captures that show the equilibrium values. When you are complete, then change it back.
2.  I can take a look at seeing if I can go a certain number of weeks back in the report offset (-13).  However, I can't guarantee this, as it is a Forio level change.  If possible, we would then add in the appropriate chart code, test and deploy.
3.  Finally, I don't think it a good idea to have one model one way, and the other models the other way.  The team has been very careful to maintain consistency.
4.  Why can't we just use the Vensim charts for the paper?  While the equilibrium part of the run is convention for SD pros, is it important to the clinicians and clinic management teams?

In any case, I am committed to finding the answer that will work for you.  ~James

**Comment by lzim** [comment] 2019-09-30 15:20
@TomRust 

@jamesmrollins and @lzim discussed on Workgroup Leads:
1. _Background_: @TomRust thought we would be trimming anything before -13 weeks, not everything before today.
- Thought that PSY and SP would have the long initialization to equilibrium be trimmed.
- CC, MM, AGG would still show the quarter before coming to equilibrium.

2. Context: Trying to make MTL guides, videos and scientific manuscripts 100% consistent for our scientific, highly educated, professional learner audience, who will read peer-review manuscripts.
- We will send Vensim models in with the manuscripts.
- We’d like to show the Sim UI models and output in the manuscripts.

**Comment by lzim** [comment] 2019-09-30 15:41
@jamesmrollins is going to double-check on the technical possibilities one more time with Forio.

@lzim is going to double-check with @TomRust about how important he feels this is for the learners.

**Comment by lzim** [comment] 2019-09-30 20:30
### Here are the purposes for showing -13 weeks before today:**

#### Clarity of Initial Conditions for the Team
1.**_One purpose for showing -13 weeks before today, is to show whatever the trend is before the experiment starts, so that you don't accidentally conflate the exogenous trend with the results of your experiment._**
- In our case, all our models are in equilibrium between week -13 and today (time 0).
- However, if our models were not in equilibrium, then you show the trend before your experiment, e.g., obesity is on the rise, how can this be addressed?
- Our models begin in equilibrium, a standard in system dynamics modeling, because we don't know enough about any given local team, to know whether they have a sustained long-term trend or not in their local setting. 
- We are more likely to be correct about what is happening locally to assume that there is no long term trend.
- **We are more likely to be correct to assume that there are a lot of balancing feedbacks in a clinical team, which means that there a lot of inertia in the team and any short-term trends would be dampened out in the long run.** [This is a key insight for quality improvement and implementation science.]
- Even if we did see a long term trend in the historical team data, we wouldn't know why it was happening. In other words, we wouldn't be able to see the reason from the data alone.
- If we saw a team that had a trend, we would need to talk with the team int he field, e.g., why were they still getting more new referrals, when wait-times were increasing?

- Since we don't know why, we can't be sure that any trend would continue into the future. Why assume that a trend would continue?
- The safer assumption for _an average team_ is to assume that a team has to return to a given set-point given their local resources and constraints.
- **This is a reasonable assumption of the clinics we are working who by definition are underperforming and struggling to achieve improvements.**

_Detail that can be added in models...._
- Historical trend
- Timing of experiments

#### Clarity of the Impact of the Experiment
2. _**A second purpose for showing -13 weeks before today, is to show how much the outputs change immediately following the experiment._**
- When you review a chart and see a jump from -13 weeks to time 0, and then a drop back down to equilibrium from today in the future (of the experiment timeline). 
- This type of system behavior is indicative of a strong _balancing feedback,_ which can produce oscillating system behaviors around a goal or set-point.

- It is easier to tell a causal system story (i.e., the system behavior produced by the causal feedback), when you see the impact of your decisions take effect at time 0 (or today).
- For example, if in the experiment we ran, we added new providers, we might see the new patient start rate jump, but then decline. It would be harder to explain the decline on its own, if we didn't see the jump first, in which **the "jump" is the impact of the experiment and the decline is the impact of the causal feedback on the system behavior over time.**

**Comment by jamesmrollins** [comment] 2019-09-30 22:39
@TomRust @lzim I spoke with Forio today.  They indicated that we can adjust the report offset function to give us our 13 weeks.  I will have to put the "today" lines back into the charts. This will take a day or two (including text).  I will let you know when it is done. ~James

**Comment by lzim** [comment] 2019-10-01 01:18
> @TomRust @lzim I spoke with Forio today. They indicated that we can adjust the report offset function to give us our 13 weeks. I will have to put the "today" lines back into the charts. This will take a day or two (including test). I will let you know when it is done. ~James

@jamesmrollins Thank you for figuring that out with Forio.

As you can see above, @TomRust and I worked on this a bit today, and the conclusion was that this serves important functions for all _MTL Audiences_ (learners, facilitators, scientists, etc.)

**Comment by lzim** [comment] 2019-10-03 14:37
@jamesmrollins 

Please ping me when this is available in TEST. 

Thanks!

**Comment by staceypark** [comment] 2019-10-03 15:26
@jamesmrollins will update us by end of day latest

**Comment by jamesmrollins** [comment] 2019-10-03 17:31
@staceypark @saveth @lzim @TomRust 

We have figured out the report_offset calculation and I have implemented it in TEST CC.  So now the charts show the -13 week value.  We will have to add the "Today" line back in.  I will see if we can get this done by Friday.

@saveth I don't think this will affect any of your reports, because the output file exports at time zero (see attached). Let me know if you have any concerns. ~James

[cc test export.xlsx](https://github.com/lzim/teampsd/files/3687325/cc.test.export.xlsx)

**Comment by jamesmrollins** [comment] 2019-10-03 17:52
@hirenp-waferwire please add the "Today" line back into the charts for all models.  I have adjusted the report_offset to the correct values in TEST.

**Comment by saveth** [comment] 2019-10-03 18:32
Good to know. Thanks @jamesmrollins!

**Comment by jamesmrollins** [comment] 2019-10-04 20:28
@lzim @TomRust the charts are now showing  -13 weeks, with a "Today" line indicated.  Let me know if you have questions.  BTW, I know that upon load, the charts look scrambled in the upper left around the units of measure.  It does correct itself, but I am looking into it.  Cheers, James

**Comment by staceypark** [comment] 2019-10-07 15:29
@lzim please take a look at this and if we decide to move to PROD, we need to address this issue in group supervision as well.

**Comment by lzim** [comment] 2019-10-07 16:42
@TomRust Are you able to review this today in TEST before we move to PROD?

**Comment by TomRust** [comment] 2019-10-07 17:07
I just looked through the TEST in CC.  It looks better than great!  I thought we were just getting our "today line" back.  I didn't think we'd get to see any results at all before running a sim, so showing what happened to the virtual team before week zero is a bonus (see circled output data, before hitting run in screen shot below)
![image](https://user-images.githubusercontent.com/32961420/66332567-0932ab00-e903-11e9-8e0b-089b7d3ecf7a.png)

**Comment by jamesmrollins** [comment] 2019-10-07 17:35
@TomRust Great!  I'm glad we could figure this out. @lzim unless there is an objection, I would like to promote this to PROD by Tuesday 10/8.

**Comment by jamesmrollins** [comment] 2019-10-08 14:12
@lzim @TomRust This is in PROD.

**Comment by lzim** [comment] 2019-10-09 01:48
Yes! I was working with this today.

Thanks @jamesmrollins and @hirenp-waferwire!

**Comment by staceypark** [comment] 2019-12-27 23:11
Checked and works in all models 👍

**Closed by staceypark** 2019-12-27 23:11 UTC
Labels: outputs_section
