### ISSUE TITLE
FEATURE: There are Instances Where a Team Data in not in the Dropdown 

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#2148] opened 2021-07-28 23:11 UTC
Hi @hirenp-waferwire .  See the image below.  In this individual world, the Team Data on the maintenance menu was not shown on the dropdown:

![image.png](https://images.zenhubusercontent.com/5e4eac12455ade27f3584cea/19d03fe8-a294-4eef-9646-7ecf59b6270e)

**Comment by jamesmrollins** [comment] 2021-07-29 15:04
Hi @lzim, @lijenn @staceypark - The problem is actually quite simple.  When the person put in the name, they didn't type in the proper file extension.  They put in ".xlsm" instead of ".xlsx" so the list doesn't read it.  This failure mode should be drastically reduced when we automatically upload team data to this menu.

**Comment by lijenn** [comment] 2021-07-29 15:53
Thanks @jamesmrollins! You're right, they added the data ui file (.xlsm) and not the team data table (.xlsx), which the automatic team data upload feature will also prevent :)

@staceypark and I will try to complete the QA tests in #2121 so it can roll out!

**Comment by lijenn** [comment] 2021-08-03 17:09
@jamesmrollins Did we already roll out a feature for this into PROD?

I uploaded and added the new team data table file for this team into Lindsey's indiv. world to address the original issue of the bug in this card.

However, I also saw it auto-upload the team data table file into all the other indiv. worlds for this team too. 
When I deleted the file from Lindsey's indiv. world, it also did the same for the others' indiv. worlds.

**Comment by jamesmrollins** [comment] 2021-08-03 17:13
Hi @lijenn  - I didn't think so.  I thought it was still in test. I will have to check it out. Did you upload the team data file through the dashboard, or just update the name in the team data maintenance dialogue on her _ind home page?

**Comment by lijenn** [comment] 2021-08-03 17:15
@jamesmrollins Yeah it should still be in test, this might be a bug or something accidently got moved over into Prod from test.

I uploaded the team data file through the dashboard since the file was not there originally. Then added the name in the maintenance dialogue of her home page.

**Comment by jamesmrollins** [comment] 2021-08-03 18:49
@lijenn I reviewed SmartLook and will discuss these tonight with DEV.

**Comment by jamesmrollins** [comment] 2021-08-04 03:26
@hirenp-waferwire **can you confirm the status of this feature?**  I suspect we haven't completed this, as I tested this today in Test-slow and it didn't work.  Did we use Break-fix and pass it directly to PROD?  @lijenn is reporting team data malfunctions in PROD, where she deletes a file from an individual's Team Data Maintenance Menu and it deletes it from other accounts.  I wasn't able to confirm this on SmartLook, but Jenn is a careful tester.  

- [ ] Just as a reminder, we are supposed to automatically update the Team Data Dropdown in the home page whenever a new Team Data file is uploaded from the Dashboard.  
- [ ] The Team Data would also be listed in the Team Data Maintenance Menu.  
- [ ] All _team and _ind accounts associated with the Team Root would receive the update.

**Comment by jamesmrollins** [comment] 2021-08-04 04:55
Hi @lijenn and @staceypark .  I discussed this with @hirenp-waferwire and we have some issues.

## Findings
- Currently, the coding must have the full team name in the team data file in order to be properly placed into dropdowns.
- Problem is that we add many details to the Team Data name, and save multiple Team Data files to the same team.
- The team roots are loosely standardized, which isn't enough to support code logic.

## Alternatives
1. The team root must be standardized to three positions number_geolocation_clinic (i.e., 123_stlouis_cboc). Code could then read this team data and automatically upload it - or
2. We create a pop-up that appears after the facilitator clicks "Add" on the Team Data dialogue in Team Setup.  The popup would present a list of active teams that the user would select. The code would read that and update the appropriate dropdowns.

## Recommendation
- Go with the Pop Up.  It gives complete latitude to name the team data file any way you want. 
- Reduces the burden of standardizing and having to deal with legacy non-standard team data files.

**Comment by lijenn** [comment] 2021-08-04 19:19
Thanks @jamesmrollins! 
We confirmed that the geolocation part cannot be split as such "123_st_louis_cboc" since not all geolocations will require an additional position. So the team root must be standard with only 3 positions as opposed to 4 positions. 
However, this does not meet our current standards and will require us to use a new convention just for this.

**Rate limiting factor is the underscore for standardization.
Because of this, I also vote for the Pop-up recommendation.** 

So it sounds like we'll be selecting the teams we want to add the team data table file to first after clicking "Add", and then uploading the team data table file. This sounds fine to me!
@staceypark Anything we're missing?
![image](https://user-images.githubusercontent.com/59668647/128241479-4f1d8c06-d869-4e8c-8789-ee16e39f21c7.png)

**Comment by staceypark** [comment] 2021-08-04 22:21
> Thanks @jamesmrollins! You're right, they added the data ui file (.xlsm) and not the team data table (.xlsx), which the automatic team data upload feature will also prevent :)
> 
> @staceypark and I will try to complete the QA tests in #2121 so it can roll out!
This is definitely a feature and not a bug as we cannot have anything other than the deidentified aggregated team data table outside of the VA domain.

I agree with @lijenn that given the team naming convention constraints, it makes more sense to have this be two steps: upload the file, then assign it to a team's world. This I imagine will also allow folks to easily assign to individual or facilitator worlds as well.

**Comment by jamesmrollins** [comment] 2021-08-04 22:24
@staceypark and @lijenn .  With the popup, you will only need to select the _team and the sim will update all _team and _ind instances under that root.  An interesting flexibility though, is that you could assign it to more than one group, such as to yourself if you wanted to play around with it.

**Closed** 2021-08-16 15:20 UTC
Labels: sim_ui, dev
