### ISSUE TITLE
2024: mtl.how/team - Need to include the Growth award

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#3100] opened 2024-03-05 02:03 UTC
@jamesmrollins @matthewtomo 

- [x] Need the Growth award listed in the two section with the other two award descriptions

![image](https://github.com/lzim/teampsd/assets/7454688/c1301657-2c7a-4c57-9cbe-58057746967d)

**Comment by lijenn** [comment] 2024-07-19 20:23
Discussed 7/19 Team Praxis Meeting:
@jamesmrollins confirmed that this is in Prod and live.

**Comment by ljmoody** [comment] 2024-10-17 00:19
- Reopening issue because the Growth Award is not included in awards listed:
![image](https://github.com/user-attachments/assets/f2a268d6-35ad-4652-82ac-ed541b3bb74d)

- @matthewtomo. this card was closed in July but the changes aren't observed in PROD. _Do you know the history of this or where to change it in the back end?_ I don't see it within the Team PSD admin site.

- @lzim would like to know why that is not a modifiable section of the site (from what she and I can tell).

**Comment by ljmoody** [comment] 2024-11-20 17:06
@matthewtomo, thanks for the mockup. 
I notice something unique about the Growth award when compared to the other two--see the highlighted portion below. I'm unsure if that is purposeful or if the design evolved to not include that on the others. Hopefully @lzim can shed some light. I believe it's good to go otherwise.
![image](https://github.com/user-attachments/assets/bdb75d4f-ae1e-4a6d-a861-4d66e188c154)

**Comment by matthewtomo** [comment] 2024-11-20 18:51
> @matthewtomo, thanks for the mockup. I notice something unique about the Growth award when compared to the other two--see the highlighted portion below. I'm unsure if that is purposeful or if the design evolved to not include that on the others. Hopefully @lzim can shed some light. I believe it's good to go otherwise. ![image](https://private-user-images.githubusercontent.com/124643236/388194218-bdb75d4f-ae1e-4a6d-a861-4d66e188c154.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMjg4MDksIm5iZiI6MTczMjEyODUwOSwicGF0aCI6Ii8xMjQ2NDMyMzYvMzg4MTk0MjE4LWJkYjc1ZDRmLWFlMWUtNGE2ZC1hODYxLTRkNjZlMTg4YzE1NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMFQxODQ4MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZjU3ZmJhNWJkNzlmMjlmMWYyZDYyYzNiMjZiYjM0NzYxYzU1ODdmNjRiMmM5MTdlZTFjZDU3YmUwMmRkNDAwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oi4X23WzpeTThGXxilCg--2aDHmd-vMy_guoLxszerY)

- @ljmoody the mockup I made was only including the image and text description in the section that I circled.
- The image for the growth award had already been created and has been in use on the site (just not in the section describing the awards).
- The image was approved by @lzim in [https://github.com/lzim/teampsd/issues/2790#issuecomment-1379330781](https://github.com/lzim/teampsd/issues/2790#issuecomment-1379330781)

**Comment by lzim** [comment] 2024-11-21 14:53
Thanks for the discussion of this yesterday @ljmoody & @matthewtomo 
@ljmoody's post above includes weird language for the badge?

Just want to confirm it will be the "mutual growth" language shown here and in Matthew's mockup.
Thanks!

![image](https://github.com/user-attachments/assets/3ed23ca4-4c48-4512-ac70-eb530b9cc3b5)

**Comment by ljmoody** [comment] 2024-11-21 16:18
Apologies for the confusion because of the incorrect image shown above. @matthewtomo won't use the weird language badge--promise!

**Comment by matthewtomo** [comment] 2024-12-04 18:30
# Tested for PROD Team PSD website on Non-VA machine, in Chrome, on 12/4/2024
- Growth award is confirmed live
- marking card as closed
![image](https://github.com/user-attachments/assets/23bdd01b-2222-4541-9c69-4b4ad88821d4)

**Closed by matthewtomo** 2024-12-04 18:30 UTC
Labels: sim_ui, Operations
