### ISSUE TITLE
Additional Site Selection Issues

### ISSUE THREAD

**Issue by ritahitching** [lzim/teampsd#798] opened 2019-11-04 22:14 UTC
Crossref #464 
**1. Add description:** 
Additional site selection issues following manuscript_monday meeting
Site Selection List

**Possible Selection Concerns**
- Matt identified a site that doesn't have any staff at the CBOC.
- So, the "floor" staff algorithm may not be catching the absence of any on-site "team" when the care at the site is completely telehalth.

**Decision:**
**Random Site Selection and Random Assignment Level:** 
- If all the workload is 644 or 690 should be predominantly TMH, and these clinics should not be included if we are sure they do not actually have onsite staff/team, and again unless there is a TMH "team" (defined by multidisciplinary offering offer of a mix of services).

<< Paste screenshots here>>
 
**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_

**Edit the due date (if necessary)**

**Comment by lzim** [comment] 2019-11-05 02:38
Edited by LZ Above.

@saveh @staceyoark @ritahitching let’s follow up on this tomorrow.

**Comment by saveth** [comment] 2019-11-06 16:30
@ritahitching Decisions made in HQ Huddle yesterday evening:

1) remove 2 more VAMC per ORH;
2) remove CBOC below mode
3) examine impact of decision rule 1 & 2.

FYI: @saveth @staceypark @ritahitching

**Comment by staceypark** [comment] 2019-11-06 17:18
@saveth as discussed on our call, please also remove Spanish-speaking HCS

**Comment by staceypark** [comment] 2019-11-06 18:04
@saveth Based on recommendations from the QIIC's...
We will NOT remove sites that may be geographically located in an area where Spanish--speaking common. We expect that since proficiency in English is a requirement for VA providers that in a national randomly selected clinic sample the role of potential Spanish-speakers should occur at random and could be described/addressed if/when it occurs.

> @saveth as discussed on our call, please also remove Spanish-speaking HCS.
> Multilingual MTL will be something to consider for future releases.

**Comment by saveth** [comment] 2019-11-06 20:51
@lzim @ritahitching @staceypark I've updated the changes and ready for a pass from all of you on our new list. Should we call this final_v2? 😄 Email is on its way.

FYI: @saveth

**Comment by saveth** [comment] 2019-11-06 23:52
@lzim I've updated the slide deck to remove only one additional VAMC (instead of two) per ORH email request today.

@ritahitching @staceypark Please review.

**Comment by saveth** [comment] 2019-11-13 23:51
@lzim I've emailed the updates on condition 3 of our provider issue as well as the slide deck I've updated today.

@ritahitching @staceypark please review and foward to @lzim.

**Comment by ritahitching** [comment] 2019-11-14 16:15
@lzim @staceypark @ritahitching @saveth 

-Savet working on the latest consideration

**Comment by ritahitching** [comment] 2019-11-18 16:16
@lzim @saveth 
- Redo slid deck for sites 
- Sites without onsite teams - need to ensure that arms are balanced
- Design where intervention in a site without a onsite team
- No tertile or tree design - clarity on which scripts to rerun - requires about 1 week 
- Association between covariates and correlation matrix - tree, random forest and others to decide the most important covariates and EBP reach 
- Covariate matrix - 
- Start with simplest analysis - Ccorrelation matrix EBP reach to our apriori discussions
- Eligible clinics and EBP reach

**Comment by ritahitching** [comment] 2019-11-18 16:27
**David** 
-**companion data table** - perhaps **Excel** - able to filter and search to update the consort table

**Comment by ritahitching** [comment] 2019-11-18 16:32
- **Common consort** tables - requires regular update
- **Deign code** with least amount of re-work

**Comment by ritahitching** [comment] 2019-11-18 16:37
**To Do**
- Correlation matrix  - EBP reach to our apriori discussions
- Do not remove any covariates
- e.g. Relationship between greater than 3 and the LIPs 
- eligibility criteria requires clinics with onsite team 
Demand ratio / CBOC / rurality

**Comment by saveth** [comment] 2019-11-18 17:53
@lzim @ritahitching I've included the correlation matrix into the current deck of 197 clinics and updated the heatmap. All vars in the heatmap are in the correlation matrix. 

- Psychologist, Psychiatrist, and SW are variables that indicates the average monthly number of providers.
- total_lip is the sum of LIP providers (Psychologist + Psychologist +SW)
- Npatients is our size

Good luck with the meeting!

**Comment by saveth** [comment] 2019-11-18 22:15
@lzim @ritahitching There simply aren't enough clinics from each HCS in each of the 4 strata proposed during the manuscript meeting to apply the sampling strategy. We either need to change the sampling procedure or the strata.

@saveth @staceypark

**Comment by lzim** [comment] 2019-11-18 22:49
Hi @saveth 

Should we discuss this tomorrow, or on the procedures OSF or on the email thread with the slide deck?

Thanks,

Lindsey
FYI: @ritahitching

**Comment by saveth** [comment] 2019-11-19 23:35
@lzim @ritahitching @staceypark I'm done with the slide deck  of our final FINAL sample clinics for the QIICS to review tomorrow.

@ritahitching Let me know if you're able to do a pass through the deck before sharing.

Thanks! @saveth

**Comment by saveth** [comment] 2019-11-20 00:29
@lzim @ritahitching Map is now included in the slide deck.  I'll email the file so you can upload into the Lucid meeting for tomorrow. Enjoy!

FYI: @saveth @staceypark

**Comment by saveth** [comment] 2019-11-20 22:19
@lzim Any updates from the meeting this morning? Are we  done or did QIICs raise any other issues that would affect the sampling?

FYI: @ritahitching @staceypark @saveth

**Comment by staceypark** [comment] 2019-11-21 17:28
In addition to the sampling_final_clinic_list_v2, update & add these from **Eligibility_pres_2019Nov_initiate** slidedeck

1. Put Descriptive statistics tables before the related graphs
2. Add red median line and black mean line with descriptive stats to every histogram (i.e. how it looks in slide 82)
3. Slide 3-8 keep. but update Slide 4 to include new criteria and merge slide 5 into Slide 4 
4. Slide 10 and 15 put next to each other, change slide 15 title to say "Variables Names and VA Terms"; update Slide 10 with newest variables
5. Keep slide 11 with AUD included
6. Slide 25 and 26 (combined ebpsy and ebpharm heatmaps and omnibus), update to new list of eligible clinics with only the covariates of interest
7. Slide 27, 29 rerun for new set of eligible clinics
8. Slide 31, 32
9. Slide 45-64, for histograms update for new set of eligible clinics, take out tertile and keep regression tree
10. Move slide 66 to after slide 9
11. Move Slide 29 from the **sampling_final_clinic_list_v2** deck up to the front where other HCS maps are

**Comment by lzim** [comment] 2019-11-25 20:51
@saveth Just following up on our phone call.

- [ ] Provide average LIPs and average unique patients for each of the 48 sites, so that we can adjust the timeline to be more feasible.

@lzim Will use this to do a feasibility adjustment of the timeline.

Thanks!

FYI: @ritahitching @staceypark

**Comment by saveth** [comment] 2019-11-25 21:27
@lzim I've added slide number 26 with information on the number of patients and LIP to the sampling_final_clinic_listv2 slide deck.

FYI: @ritahitching @staceypark @saveth

**Comment by lzim** [comment] 2019-11-25 22:12
Great, thanks @saveth taking a look now!

**Comment by saveth** [comment] 2019-12-03 19:45
@staceypark @lzim  I finished rerunning the analysis and compiling the "Big Deck" based on the changes discussed before the holiday. @ritahitching also just finished reviewing the deck, so it looks like it's good to go.

 I've created a stand alone folder so that @lzim can make changes for the various presentation without affecting workflow or other code. @saveth will email the info.

**Comment by saveth** [comment] 2019-12-09 23:19
@lzim @staceypark @ritahitching I've updated the "Big" slide deck to include the new 6 waves. It is still the same path that I sent last time. I think this issue can now be close since we're done with site selection. 🤞

**Comment by lzim** [comment] 2019-12-12 19:03
Cross-ref #464 - Handle at Quant Workgroup next week.

**Comment by saveth** [comment] 2019-12-19 20:44
Add code annotation in final sample slidedeck.

Rules for code annotation:

- Add comments for each chunk, explaining what the chunk is doing or producing, use annotation mentioned below

- i.e. include comment that says "table" "figure" "map"

- This will also help for Ctrl + F finding specific items in the code.

FYI: @saveth @ritahitching @staceypark @lzim

**Comment by saveth** [comment] 2019-12-23 20:22
@lzim @staceypark @ritahitching I've updated the R01 & IIR slidedeck with comments in each chunck of the markdown file and renamed the file to r01_iir_master_sampling_deck.Rmd. The file is still in the same location/folder. I think we can close this issue now.

**Comment by staceypark** [comment] 2020-02-11 23:47
@ritahitching I'm reopening this issue as I'm not sure that it's done.
Even if you are the "originator" for this issue by definition of who created this issue, you are not the "originator" in the sense that you are responsible for knowing and checking if the requirements/tasks for this item are finished to satisfaction.

@lzim I think something we need to still track:
- [ ] double check how sites were defined as CBOC or VAMC
- [ ] check Marcia's site that was categorized as a VAMC but the numbers don't seem to match

**Comment by lzim** [comment] 2020-02-19 22:50
@anthonycpichardo 

- One of the QIICs & I realized that there was a site listed as a CBOC in our site list that is actually an extension of the VAMC, which got us crosswalking data.
- As part of that process, @lijenn and I discovered a duplicate HCS in the site selection last week. 
I need to determine what to do about this for the **r01_protocol_manuscript** #559  🎢

**Comment by anthonycpichardo** [comment] 2020-03-03 19:13
@lzim Combing through issues to ensure we're on track. Is this something needed for go-live?

**Comment by lzim** [comment] 2020-03-10 04:48
@anthonycpichardo I just closed this issue as well as #615 and #571 

(Note: GitHub is seeing this as a jessfroe mention, because it's in a manuscript card. But, it's really my edit). 

I'll need to turn to #559 shortly for final review/edits/submission.
I'll keep track of this as a cross-reference there.
And, we can open a new issue (or re-open) if we need to.

FYI: @staceypark

**Closed by lzim** 2020-03-10 04:48 UTC
Labels: quant
