### ISSUE TITLE
wk4 jul_epic task: PBI MVP for Data UI ClinicSelection and SPReferral  

### ISSUE THREAD

**Issue by anazariz** [lzim/teampsd#2140] opened 2021-07-22 21:29 UTC
**PBI MVP for Data UI ClinicSelection and SPReferral**  

To minimize rework of documentation, create an MVP in PBI that resembles (as closely as possible) the current look and functionality of the ClinicSelection and SPReferral tabs.

**Comment by lzim** [comment] 2021-07-26 23:27
Note @anazariz 

It appears this task card is a duplicate of #2112 focused on the review of the _Modeling to Learn_ videos to develop an MVP of the "ClinicSelection" and "SPReferrals" functionality in Power BI.

Cross-ref #1961

**Comment by lzim** [comment] 2021-08-03 20:38
Closed because it's a duplicate of #2112.

**Closed by lzim** 2021-08-03 20:38 UTC
Labels: quant
