### ISSUE TITLE
wk2 jan_epic  Data Export from PBI into SimUI - TEST Card

### ISSUE THREAD

**Issue by mnallajerla** [lzim/teampsd#2413] opened 2021-12-09 19:27 UTC

**Comment by mnallajerla** [comment] 2022-01-24 18:19
We might be good to close this?

@lijenn

**Comment by lijenn** [comment] 2022-01-24 18:22
This might be a duplicate of #2453 with a checklist by James.
I'll close this card and follow up any remaining tasks on testing in that card.
@mnallajerla

**Closed by lijenn** 2022-01-24 18:22 UTC
Labels: facilitate, power_bi, Development, Operations
