### ISSUE TITLE
Week of 1/6 #hqhuddle

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#840] opened 2019-12-23 17:28 UTC
Cross ref #839 

@lzim 
- [ ] R01 Annual report
- [ ] Ci2i/HSRD Annual report
- [ ] Updated analyses for NIDA talk in Jan at NIH #674 

### PAVIR 
- [x] Send Luanne invoice for Adobe CC once it goes through

### LZ Misc.
- [ ] Email Dan O'Brien Mazza to update on MTL Launch before retirement 
- [ ] Set up local VAPOR meetings with Jill Hudson and Ben Marks, etc.
- [ ] LGBT SIG email

@staceypark 
### MTL Launch
- [ ] CRM Instance and User Request forms
- [ ] Setup Skype links for Co-Planning calls in January
- [ ] Co-facilitator request for Microsoft CRM & Microsoft Teams

### PAVIR
- [x] Follow-up with Luanne for Rebrandly to remind on W8

### 1. Scheduling 
- [x] Finish setting up reference calls for quant hire candidates
- [x] Confirm meeting time w/Kate Steffen
- [ ] Lucid Dial-in Bug with 805 number 
- [x] tt_report send out + add the images over the year 2019 + new email for David
- [x] Back up Adobe and send follow up email + update email QIICS group with David's new email
- [x] Update meeting series with David's new email 
- [x] Update own calendar with meetings that should / should not attend
- [ ] Schedule meetings for teamPSD
- 4th Tuesday / 9 am all hands (HQ, Quant, QIICS, Co-Is - virtual) (check with Stacey)
- 4th Friday all HQ working afternoon 12pm - inventory/work updates for the following month - onsite
- [x] Send cancellation manuscript meeting Jan 14 and 26 2019 - use previous email message
- [x] Send email to Ruth with list interviewed logs for all candidates across the 3 PDs
- [x] Escalation of Microsoft Teams and IT request

### MTL Launch
- [ ] Send any updated learning objective in the SEE and SAY guides (as compared to the Master Brochures) to Elizabeth (Elizabeth back 1/15)
- [ ] VAPOR videos in pre/post emails
- [x] Align Done/Do review in SEE & SAY session guides with pre/post emails aligns
- [x] Follow up with James with file upload on Community of Practice issue and update QIICS.

###  Manuscripts 
- [ ] OSF Registration for each project

### VAPOR Scheduling 
- [ ] There are 3 Veteran-engagement groups Interested in setting up "lesson learned" or "best practices" meetings with VAPOR, to discuss challenges (i.e., lack of staffing) and share knowledge.
1. Travis Runnels at VAPAHCS.
2. Nathaniel Moffet form the Ascend Project in Colorado.
3. Leah Wendleton does Veteran-engagement groups for VA researchers.
- [ ] Confirmatory Factor Analysis for MTL fidelity meeting w/David, Lindsey, Jessilyn, & Stacey

### PAVIR
- [ ]  Create an internal TeamPSD schedule for each vendor that will need manual requisition submissions each year and with due dates for the subscriptions. Perhaps we could create a yearly Outlook reminder that will ping us a few weeks before the deadline as well.

### General
- [ ] Work with Steve Woodward for the inventory of possible missing folders

### 1. Manuscripts
- [ ]  Review R01 consort tables on OSF (https://osf.io/8pzxu/wiki/consort_checklist)
- [ ]  Work with Stacey to re-submit VAPOR
- [ ]  Work with Swap to submit Mentor
- [ ]  Work to edit/finalize the graphics for GMB w/Stacey & David
- [ ]  R21 preliminary findings

### 2. MTL National Launch
- [ ]  Review SAY guides & close documentation cards
- [ ]  Bookdown format for the Manual

### 3. Manuscripts 
- [ ]  Review IIR consort tables on OSF for IIR (https://osf.io/p7g8f/wiki/consort_checklist/)
- [ ]  CC Intro & Discussion
- [ ]  MM Intro & Discussion
- [ ]  Psy Intro & Discussion
- [ ]  SP Intro & Discussion

### 4. Other Upcoming
- [ ] 1. CFIR slides to Lauren
- [ ] 2. NCPTSD website update - who handles this at NCPTSD

**Comment by staceypark** [comment] 2020-01-06 23:35
# 2020_01_06 hqhuddle Decisions
1. Pre-plan month out across all workgroups
- Need to plan out dependencies & cycles of Dev/Test to review decision-making 
- Need to schedule out time specifically in calendars to do these tasks where everyone knows when it will happen
- Have in mind what the open slots are going into the monthly planning meetings
2. Shift HQ tour from **7:30am - 4pm** (remove HQ meeting that runs from 4-4:30pm each day)
3. We will be more disciplined about time during our meetings (especially HQ meetings)
4. Jennifer will be starting at 12Noon Lunch tomorrow 🎉 
5. Delegation train - Each person needs to have options of other folks to delegate to with continued and increased training to increase delegation tasks
6. New team members will have 1 on 1 meetings w/@lzim 1x month for 30 min for their first 3 months
7. Existing on-site (full time) team members will meet quarterly w/@lzim for 1 hour each time
8. HR Meetings: Lindsey & Stacey will meet @11:30pm every Monday (instead of 12Noon)
9. Calendar will tell us what is coming up / needs to be done. The #hqhuddle will shift to "Done" lists or updating to how missed items will be rescheduled. 
10. Lunch at 12Noon with HQ midday check-in at @12:30pm every day
11. Annual reviews are coming up in March. We will need to schedule pre-review time in February as well. 
12. Need to inventory HQ cross-coverage of meetings.
13. 12:30pm 4th Friday of each month: We will inventory all the issues and fill out calendar for next month, in preparation for 1st Monday workgroup leads meeting in the next month.
14. 9am 4th Tuesday of each month: All hands meeting to call out completed milestones.
15. @lzim time division: w/ 60% at manuscripts & grants; w/ <10% on management.
16. No same week scheduling.

# EOD tasks
@lzim 
- [ ] 1. Schedule slots for tasks & review to Outlook Calendar
- [ ] 2. Finish Budget Justification for IIR

@staceypark 
- [ ] 1. Schedule slots for tasks & review to Outlook Calendar
- [ ] 2. Remove 4pm HQ meeting
- [ ] 3. Start December Splashpage update

@ritahitching 
- [ ] 1. Schedule slots for tasks & review to Outlook Calendar
- [ ] 2. tt report
- [ ] 3. Backup Adobe recording
- [ ] 4. Create last Friday HQ meetings from 12:30-4pm for inventory review

**Comment by staceypark** [comment] 2020-01-07 18:04
✔️ December Splashpage update started. Instructions updated according to issues ran into with server name yesterday.
✔️ Nazarizadeh RDIS submitted

**Comment by staceypark** [comment] 2020-01-07 18:58
✔️ additional FAQ added to #747. Let's use the 3:15pm meeting with James to review.

**Comment by staceypark** [comment] 2020-01-07 19:59
@ritahitching @lzim 
✅ In line with our discussion yesterday, I've started changing some of our "list items" into Issue cards.
@ritahitching please do the same for your items as well.
@lzim, if/when you're done updating your Outlook with the Jan schedule, I can add dates to the relevant cards based on your Outlook and make sure we have cards for everything on your plate listed in the HQ thread.

**Comment by staceypark** [comment] 2020-01-08 16:35
✅ December Splashpage update done.

**Comment by ritahitching** [comment] 2020-01-09 19:39
@lzim @staceypark 
I submitted a request to expedite the IT helpdesk tickets for Microsoft CRM Teams for you both.

**Comment by ritahitching** [comment] 2020-01-10 21:15
To do list afternoon 1/10 
1. Calendar updates and invitations
- cancellations
- invitations for HQ Monthly Planner and all onsite members (every 4th Friday) and All Hands (every  4th Tuesday)
2. tt_report and calendar updates to be included to be sent by 8am Eastern Monday 13 
3. Follow up email from today MTL Launch meeting (waiting for audio to finish backing up)
4. IT escalation requests for David (received details) and Jane (awaiting details).
5. Emails: 
- James for availability Wednesday Jan 15 meeting
-  Respond to Jay request for help on IT ticket
5. Close out issues #793 (andrea headshot) and #853 (John's title) and #867 (LucidMeeting dial in bug)
6. Wifi hotspot guidance from  Jiyong Song in Shannon's team
7. VAPOR videos in pre/post emails (issue #870) (due Jan 27 2020)
8. Graphics for GMB / David's paper manuscript (#866)

**Comment by lijenn** [comment] 2020-01-10 21:25
To-Do List as of 1-10-2020

- [ ] Finish & get a copy of SOP (OSF Account for online copy)
- [ ] Ensure all transfers from Lucid (Oct 2019 -Nov 2019) to Basecamp are completed
- [ ] Ensure all Lucid Meeting audios starting from Aug. 2019 are transferred into TeamPSD Meeting Audio folder
- [ ] Get info./account for mtl.how/test to participate in giving James feedback for any UI related issues

**Comment by ritahitching** [comment] 2020-01-10 23:38
@staceypark 

Interim update from Amy at **LucidMeeting** on
- the disappearance of the **Publish to BaseCamp** button, and 
- overnight **resetting of integration settings** for 'teampsd_workgroup publishes to' BaseCamp.

Amy: "We have an automated process that checks for "inactive" Basecamp projects, and it has been incorrectly identifying yours as inactive. It then removes the room association so we don't keep looking for updates from Basecamp. This job runs every two hours, which is why you're finding the room is disconnected from Basecamp every time you try to publish. 

It looks like the immediate cause of the problem is some stale data we've stored for your organization. I want to explore this a bit more to verify before cleaning that up, probably later this afternoon" 

**Action** - I will re-update the team once I hear more.

**Comment by ritahitching** [comment] 2020-01-11 01:16
@staceypark @lzim 
Update on WiFi hotspot used by Shannon's team:

1. Use the ATT 2TE model (https://www.att.com/buy/connected-devices-and-more/att-unite-express-2-black.html).
2. Purchased through ReqLogic an unlimited data plan with ATT - estimated cost of $100 monthly which included the WiFi hardware.
3. Data plan offers a main and guest plan.  Main plans has a fixed password login that can support 8 devices simultaneously. The guest plan has a daily changing password and can support 3 devices concurrently.  

**Benefits:** Hotspot does not block websites the VA typical does, can be moved to improve bandwidth and is relatively reliable for general web access.
**Drawbacks:** Hotspot coverage poor when downloading and uploading files.

**Closed** 2020-01-13 16:34 UTC
Labels: hq
