### ISSUE TITLE
Creating data file for sim UI

### ISSUE THREAD

**Issue by branscombj** [lzim/teampsd#392] opened 2019-06-13 21:54 UTC
---
Step 1: Click raw to copy the code text below. 
Step 2: Click the link to create a new issue for the data splashpage and data user interface https://github.com/lzim/teampsd/issues/new.
Step 3: Edit the details to create a report that will help us improve mtl.how/data and the data UI.
labels: bug
assignees: holbrooa
---

**Describe the bug**

**To Reproduce**
1. Go to '...' data UI
2. Click on '....' get data for sim ui; click run (name it etc)

**Expected behavior**

it should begin to  pull the data

**Screenshots**

I've closed it so I don't have a screen shot but it just gave an error message I can't remember.
![image](https://user-images.githubusercontent.com/29778290/59470108-9483b000-8deb-11e9-866a-fdf6a0d20380.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Explorer

**Smartphone (please complete the following information):**

**Additional context**

**Comment by holbrooa** [comment] 2019-06-17 18:02
Okay, this error message happens because our user group of providers have some built-in permissions in the CDW. I'm using those permissions for the data UI, so that we don't need our users to jump through permissions hoops. As non-providers, facilitators like Jane and Debbie will need to jump through hoops to get access to the patient-level data, if we want them to be able to run the data UI. This makes sense - we're talking about real PHI here, after all.

This is a duplicate of another issue, so I'm going to close the other one and @ the people here on this one.

For myself, I am adding this my polish list, to trap this error and explain it in the front end.

For others, we'll need a decision on whether or not to pursue getting permission to PHI for facilitators in this position.

@dlkibbe @branscombj @lzim @dlounsbu

**Comment by lzim** [comment] 2019-06-18 13:19
> For others, we'll need a decision on whether or not to pursue getting permission to PHI for facilitators in this position.

Yes, @holbrooa I need to request permissions for David, Jane, Debbie and the TAS.

@dlkibbe @branscombj @dlounsbu

@staceypark Where in this workflow are HQ tasks in progress?

**Comment by lzim** [comment] 2019-08-30 00:25
It looks like this is sitting in **done** because I need to determine the permissions for our non-VA facilitators.

@jessfroe We can close this when it is linked to the DART card in the **document_tracker** 

@staceypark can answer any questions if you have them. ❓ 

Thanks!

**Comment by staceypark** [comment] 2019-08-31 01:10
I just linked it to the DART card #610

**Closed by staceypark** 2019-08-31 01:10 UTC
Labels: document, facilitate, pi, quant, urgent
