### ISSUE TITLE
2024_feb_roadmap #story_b: FEATURE: Data UI: Facility Selection and Clinic Selection Improvement

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#2989] opened 2023-06-08 02:18 UTC
FYI: @epearman @lijenn 

NOTE:  As of 6/7 this is an unprogrammed feature and awaits a Power BI dude. 

## Benefits Hypothesis

There are least 10 issues in the repository where users struggled with clinic selections in the Data UI, the ability to "group" select, or at least remember previous clinic selections between logins. With the advent of the quick consult model, the ability of the consultant to make facility-wide connections to draw a sufficient aggregate in the Data UI is not possible. By resolving these issues, the user would be given a more robust set of tools to draw the data they need to properly characterize a facility, group of clinics or other selections in an easily repeatable way. Finally, there is a need to transparently portray a population consistently between graphical and numerical representations across the Data_UI and Sim_UI platforms. 

## Requirements

- [ ] Standardization of scales from the Data UI through the Sim UI.
- [ ] A easy to interpret moniker that indicates the denominator with respect to population sizes and adequacy of representation.
- [ ] The user should be able to select and customize a list of clinics, save that listing, and reuse it as necessary for a query.
- [ ] The user should be able to select at all management - hierarchical levels within the data (i.e., select a facility).
- [ ] The user should be able to easily export this information to the Sim_UI via .csv or other means of transfer.

**Comment by lzim** [comment] 2023-07-14 01:56
### Discussed wk2 2023_jul_epic in a meeting with Jeff H
@lijenn 
@dlounsbu
@lzim
@dlkibbe

### Agenda
#### Questions about reducing the user steps related to Clinic Selections have surfaced again:
https://github.com/lzim/teampsd/issues/2390 (your previous response about this)
https://github.com/lzim/teampsd/issues/2989 (or more recent summary)

#### We are probably going to request some additional help from OMHSP to further develop how Clinic Selections work and based on Jeff's response on #2390. 
- Lindsey wants to make sure I understand what’s happening “under the hood” thinking it would be in terms of the queries underlying the report.
- Jeff says Power BI doesn’t offer (or at least it didn’t offer) any way to do custom programmability, which is what we would have needed to improve clinic selection.

#### The tension of this User Pain Point: "There are over 1200 Clinics to Select! This takes up to 30-minutes to select."
with the key use case: Clinic Selections and Team Flow Selections update daily to zoom in on Veteran details (data) and update monthly to zoom out to review of team trends (viz). Careful review of the Clinic Selections and Team Flow Selections helps understand how to best make use of the strengths or weaknesses of the Data UI or Simulation UI report in relation to a local learning priority.

**Primary feature requested:** 
Would like to be able to generate reports on all of the Clinics associated with have the st3n facility or sta6a division/CBOC.
 
**Separate features identified:**
1. Grouping CPT codes together differently than the current definitions.
2. Including non-500 Mental Health series stop codes clinics in Data UI. 
 
### CONCLUSIONS
#### No Select All that works validly because was is displayed in Power BI Report may not match what is happening under the hood.

_Current State Workflow_
The Blue boxes always filter to the narrowest set.
So, the example below would only return 508 data.

#### Confirmed that we have a binary choice to update Facility or Clinic Selection OR keep the current detailed review.

**DECISION:** 
1. Keep the current Clinic Selection and Team Flow Selection.
2. If we update in the future, we would manage it as separate dashboards a) facility (sta3n), b) Clinic/Division (sta6a).

**DEPENDENCY on function requirements above**

**Comment by lzim** [comment] 2023-07-14 01:59
Given the conclusions above - May need to close this card @jamesmrollins 
See the issue of ongoing variable range on the denominators.

**Comment by lzim** [comment] 2024-03-20 19:25
I don't see where this still needs development. 
the **#consult_workflow** is working as intended as is using the Data UI.

Please advise if this needs to be re-opened. Thx!

**Closed by lzim** 2024-03-20 19:25 UTC
Labels: pi, sim_ui, quant, feature, power_bi, Development, systems_sme
