### ISSUE TITLE
WAVE1_Teams Data UI: Propagation subroutine and folders on mtl.how

### ISSUE THREAD

**Issue by holbrooa** [lzim/teampsd#594] opened 2019-08-29 14:03 UTC
**1. Add description:** 
Need to add code and sharepoint infrastructure for propagating the data ui. The copy of the file that gets dropped into each facility's folder needs to have been run to get their clinics, but be blank in terms of patient data and model parameters.

<< Paste screenshots here>>
 
**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_
22
**Edit the due date (if necessary)**

**Comment by staceypark** [comment] 2019-09-26 15:46
We will turn to this once the data UI is ready for rolling out to all sites. Pulled off the due date in the interim until we re-scope work and timeline.

**Comment by staceypark** [comment] 2019-10-18 22:24
@holbrooa I stuck the data UI cheatsheet into the final_datafiles folder. 
It'll likely get updated again soon, but it is there for you to test code for propagating another file in that folder.

**Comment by ritahitching** [comment] 2019-10-29 19:57
@holbrooa Were you able to test the code for propagating other files in the final_datafiles folder?

**Comment by holbrooa** [comment] 2019-10-29 20:01
Yep. The cheatsheet can easily be propagated along with the data UI. Just using the local file, though. I didn't have time to look in to getting it from the web or anything. Should be doable - just ran out of time. You can see how it works in the code for nevermore, in module 2 like when I talked you and @staceypark through it.

**Comment by staceypark** [comment] 2019-12-20 22:58
@ritahitching and @staceypark confirmed process with @holbrooa.
keeping open to review with @lzim

**Comment by anthonycpichardo** [comment] 2020-02-11 20:52
Looks like this is done and can be closed. Please confirm @holbrooa @staceypark

**Comment by anthonycpichardo** [comment] 2020-02-19 18:08
@staceypark @lzim @holbrooa Following up to ensure this can be closed. This seems to be referring to the some completed modifications of mtl.how/data?

**Comment by lzim** [comment] 2020-02-19 23:05
@staceypark 

@anthonycpichardo doesn't think this will block the guides described in #995  "for internal stakeholders." 

- But, I felt it was blocked by #429 & added the dependency just now.
- I also wasn't sure whether the folders used in the Red and Blue condition were fully thought through regarding internal team set up (for **document_team**; also may mean .gif dependency for **detail_say** ❓ 

Thoughts?

**Comment by lzim** [comment] 2020-02-19 23:06
one more thing...is this **go_live** if we don't solve permissions it may be **teams_data**

FYI: @staceypark @anazariz @anthonycpichardo

**Comment by lzim** [comment] 2020-02-21 20:58
@staceypark and @lzim 
Discussed this at #hqhuddle & Stacey will identify the chunks for documentation that need to stay in **go_live,** separate those that are for **teams_data,** & she will adjust the estimates for each issue tasks accordingly.

**Comment by anthonycpichardo** [comment] 2020-03-03 19:16
Where are we on this @staceypark ? Should this issue be moved to teams_data?

**Comment by staceypark** [comment] 2020-03-04 22:34
cross-ref'ed to #1062 to track documentation needs. Moving to teams_data for actual propagation

**Comment by anthonycpichardo** [comment] 2020-09-23 09:28
@staceypark can this be closed?

**Comment by lzim** [comment] 2020-10-14 17:03
I think it can be closed @anthonycpichardo 🚀
Seem right @staceypark?

**Closed** 2020-10-17 01:27 UTC
Labels: quant
