### ISSUE TITLE
 #story_a3: #aim_3 Data Sharing, storage, and de-identification and merging of aim3 data

### ISSUE THREAD

**Issue by ghost** [lzim/teampsd#2880] opened 2023-03-01 00:45 UTC
Discussion During wk4 **feb_epic team_time** 

**Requirements:**
- [ ] Data needs to be de-identified per new NIH data sharing management plan
    - [ ] Furthermore, only certain authorized TeamPSD users can have access to de-identified salary data
- [ ] Libby can work on the data outside of the VINVI environment but within a VA computer environment
data while also de-identifying the final data set. 
- [ ] **Minimum of two separate coding files (programs)**
    - [ ] Program 1: to de-identify and merge the data - This code and input data will not be shared with NIH
        - [ ] Need a key that links names, with GitHub user names, and with unidentifiable IDs for merging GitHub data with salary 
    - [ ] Program 2: to run analysis on the de-identified data - This code and input data will be shared with NIH
_______________________________________________________________________

#**Data Description:**
- [ ] Annual salaries by each person by name (for contractors and employees). 
    - [ ] contractors salary data will be provided as monthly invoices. (Praxis analytics is our only contract). 
        - [ ] 3 lines in this data: Product management, Design, Development (each category has a different hourly rate). 
            - [ ] Does not include equipment or any other cost categories.
       - [ ] Github/Zenhub Assignees under Praxis analytics are James (GitHub username: jamesrollins) and Hiren (GitHub username: hirenp-waferwire)
- [ ] As long as Libby is understanding the salary per time per person she can create the datasets from any filetype. 

__________________________________________________________________________________________

**Next Steps:** 
- [ ] Where will we store the identifiable salary data and Program 1 (specified above)? 
    - [ ] Who will create and run the program to de-identify and link the salary data? 
    - [ ] Is this set up as a reproducible yet confidential workflow?
- [ ] Where will we store unidentified salary data and Program 2 (specified above)?
    - [ ] GitHub or TeamPSD?
- [ ] How will Emily P wrangle the Zenhub/GitHub data for Libby

**Comment by lzim** [comment] 2023-05-10 03:42
@lzim found another card on this 

Bringing us to 4 cards: 
lzim/research#432
lzim/research#570
lzim/research#632
https://github.com/lzim/teampsd/issues/2880

**#mgmt_trio**
@hthrmarsh 
@epearman 
@emilymetcalf114

**Comment by epearman** [comment] 2023-05-10 15:34
#ajudicate memo- this is a duplicate of lzim/research#540

**Comment by hthrmarsh** [comment] 2023-05-15 17:32
Discuss wk4_may_epic

**Comment by lzim** [comment] 2024-09-30 12:10
See note from @lzim above - this work was completed on another card.

Bringing us to 7 cards:
https://github.com/lzim/research/issues/462
https://github.com/lzim/research/issues/538
https://github.com/lzim/research/issues/539
https://github.com/lzim/research/issues/540
https://github.com/lzim/research/issues/570
https://github.com/lzim/research/issues/632
https://github.com/lzim/teampsd/issues/2880

#mgmt_trio
@hthrmarsh
@epearman
@emilymetcalf114

**Closed by lzim** 2024-09-30 12:10 UTC
Labels: Research
