### ISSUE TITLE
Team PSD Webpage: Create a Single Platform User Maintainable Administration Page

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1246] opened 2020-03-26 22:07 UTC
1. Add description:
This issue is referenced to #620, which is quoted below. Items 1 and 2 are complete. Complete item 3, install upload photo utility for the Team PSD admin web page.

Estimate: 20 Hrs for Items 1 and 2. Item 3 estimate 15 hrs
Design Objectives:

Install a button or link in the header of the Sim UI page header that will enable users to upload a picture.
Install a utility that guides users through uploading a photo, centering the photo in a frame and then putting photo in the Sim Ui page header.
Install same upload utility in the Team PSD website admin page. (let me know if this was not a part of original estimate – I don’t recall if we discussed this or not).

![image](https://user-images.githubusercontent.com/60201706/77701596-ef018d80-6f73-11ea-81bf-d052eff9975f.png)

image
![image](https://user-images.githubusercontent.com/60201706/77701630-fd4fa980-6f73-11ea-9f34-92d41050c5ba.png)

image
![image](https://user-images.githubusercontent.com/60201706/77701639-017bc700-6f74-11ea-8c51-a13378711183.png)

2. Click on the right:
a. Projects - assign to issue_tracker.
b. Assignee - assign relevant team members.
c. Labels- review and select all potential MTL dependencies.
d. Milestones - select the dependent milestone.

**Comment by anthonycpichardo** [comment] 2020-03-26 22:12
This used to be issue #782

**Comment by jamesmrollins** [comment] 2020-07-17 22:53
### Hypothesis:
1.  The Team PSD Web Page is inflexible and its sections and sub-sections cannot be dynamically changed or reordered by the user.  As needs change, the web page becomes increasingly out-of-date. For example, the biographies section needs to have a new sub-section called "Team PSD Alumni" to put retired teammates.
2.  A Web Master must navigate four platforms to upload a simple photo.  GitHub to get the user-supplied photo, Illustrator or Photoshop to crop and center the photo, Epicenter to upload the photo and the Sim UI to name the photo in the biographies admin section. 
3.  The Map Slider that indicates the area of the country and the organization affiliation of teammates is also platform intensive using the 4 platform described in item 2. 
4.  Because there are so many platforms, special training is required for a user to be successful at editing the Team PSD website. 

### Assumptions
1.  We would like a user, supplied with a URL and an appropriate login, to be able to update the Team PSD website.
2.  The admin page would be so simple to use, that no training is required.

**Comment by lzim** [comment] 2020-10-06 19:59
@jamesmrollins  

I believe at **workgroup_leads** last Monday you mentioned this being read for review in TEST.

Is it ready for review from someone else on the Team?

FYI: @staceypark @lijenn

**Comment by lzim** [comment] 2020-10-14 16:51
> @jamesmrollins  
> 
> 
> 
> I believe at **workgroup_leads** last Monday you mentioned this being read for review in TEST.
> 
> 
> 
> Is it ready for review from someone else on the Team?
> 
> 
> 
> FYI: @staceypark @lijenn 

Just a re-ping checking in on which week of **oct_epic** this will be done? Since I thought it had been in TEST for some time?

It should _not_ be prioritized over getting ready to pick back up w/facilitators next week, however. 

Thanks!

**Comment by jamesmrollins** [comment] 2020-10-14 17:30
Hi @lzim  - This has not been in Test.  We won't begin working on this until we clear the Facilitator Dashboard and Chat redesign completed the end of this week (this is taking 100% capacity right now).  We intend to then turn our attention next week to finish #1246 up and get it into Test.

**Comment by jamesmrollins** [comment] 2020-10-22 00:06
Updated wireframe for webpage available here:

[TeamPSD User Maintainable Admin Page Wireframe](https://app.lucidchart.com/invitations/accept/b3666f7f-5c64-4e6d-b7aa-708a4031ce81)

**Comment by staceypark** [comment] 2020-10-22 02:00
wireframe looks good.
will the city/state automatically be separated into a new line or will the admin instructions for this section include how to do that.

> Updated wireframe for webpage available here:
> 
> [TeamPSD User Maintainable Admin Page Wireframe](https://app.lucidchart.com/invitations/accept/b3666f7f-5c64-4e6d-b7aa-708a4031ce81)

**Comment by jamesmrollins** [comment] 2020-10-22 05:06
Hi @staceypark 
The format will be consistent with what we developed, however, the text will not wrap as closely as it does now.  Likely, we will put left, center and right justify controls on the text block so it can be placed in different positions around the photo.

**Comment by lzim** [comment] 2020-10-23 03:34
Yes @jamesmrollins the wireframe looks good.

Question: Are we including an "add a section" functionality?

For example, I know that we want to add the "Alumni Network" category for team members that have moved on to other opportunities, but made substantial contributions to Team PSD.

**Comment by jamesmrollins** [comment] 2020-10-23 05:10
Hi @lzim.  Yes indeed, we are adding that functionality for the teams section so we can add additional team sections such as "Alumni Network."

**Comment by jamesmrollins** [comment] 2020-11-02 19:34
Hi @hirenp-waferwire 
Please find my edits below:

### 1.  Team PSD-Slider section.  

- Is it possible to use .svg files?  .svg works better for dynamic resolution than .png, and is a smaller file size.  If this is no problem, then we should specify it in the instructions for compatible file types in the "Map Slider Template" instructions.
- See below for more ideas.

![image](https://user-images.githubusercontent.com/30132017/97910347-77ac8d00-1cfe-11eb-9b25-3f3f8721fef0.png)

### 2.  Team PSD Map Slider Edit Function.

- Add instructions and "Save" button. 
- If possible, execute "how_to_place_image.gif" (attached) when use clicks "Help."  I will likely provide an updated .gif when the edits are completed. Consider a default presentation of the pop up with GIF playing, with option "Do not show again," when the user navigates to this page for the first time.

![image](https://user-images.githubusercontent.com/30132017/97909187-ab86b300-1cfc-11eb-90ff-0603b175a986.png)

**Example .gif**
![how to place image](https://user-images.githubusercontent.com/30132017/97905608-2056ee80-1cf7-11eb-9955-8b88b8b23678.gif)

### 3. Biographies and Photos

 - Can we scroll to the new member at the bottom of the list?  If not, we should add "Scroll to the bottom of the list to find the new member." to the instructions.
 - When a group member is transferred to another group, their picture and text box does not populate the new map.

![image](https://user-images.githubusercontent.com/30132017/97909388-f99bb680-1cfc-11eb-86f6-8939d750199f.png)


### 4.  Header Menu

 - Please remove "Team PSD" from header ID.

![image](https://user-images.githubusercontent.com/30132017/97910713-f99cb600-1cfe-11eb-85b6-6e874b89333f.png)

**Comment by jamesmrollins** [comment] 2020-11-04 20:52
Hi @lzim and @staceypark .  I moved this to PROD last night, because all the portraits and maps have to be reloaded and cannot be moved at the database level (unfortunately).  Everything appears to be working as designed.  

I created a new map on the slider called "Alumni Network."  I also used the re-assign feature to move Andrew, Rita, Savet and Swap to the new slider.  However, what I don't know is what organization I should affiliate them with, since they are no longer with the VA, right?  Let me know your guidance, and I  will make requisite changes.  ~James

**Comment by lzim** [comment] 2020-11-04 23:09
Thanks @jamesmrollins 

Actually, Swap is still with Team PSD, but from the VA in Georgia. Andrew & Rita are still with VA, just not Team PSD. Savet is not with VA.

Basically tho, we can gather the details for their current affiliations. It will be great to catch up with everyone too.

**Comment by jamesmrollins** [comment] 2020-11-25 16:12
Hi @lzim 
I reached out to Rita, Andrew and Savet.  Only Rita responded.  However, she has not provided me with an updated bio. Their information doesn't affect the function of the site, would like to close this issue.

**Comment by lzim** [comment] 2020-11-25 18:14
@jamesmrollins 

Let’s close this larger issue, but Lee track of a smaller issue (1-3 Pts) on updating bios for Savet, Andrew & Rita.

**Comment by jamesmrollins** [comment] 2020-11-30 20:47
Hi @lzim , please reference issue #1597  for update bios.  Closing this issue.

**Closed by jamesmrollins** 2020-11-30 20:47 UTC
Labels: sim_ui
