### ISSUE TITLE
wk4 nov_epic: PI Emergent Issues

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#2378] opened 2021-11-22 15:40 UTC
wk4

- [ ] Jim Budget check
- [ ] Natalia Recruiting (2 pts)
- [ ] Health equity funding
- [ ] Mailing _MTL_ materials to sites
- [ ] Get Badges Gracelyn & Danielle & Carrie O

- [ ] OASC provider survey completion help
- [ ] Facilitators Co-planning
- [ ] RPDS format & schedule

- [ ] Feedback Acceptance
- [ ] FCOI

**Comment by lijenn** [comment] 2022-01-28 01:47
closing, duplicate of #2388

**Closed by lijenn** 2022-01-28 01:47 UTC
Labels: pi
