### ISSUE TITLE
ASAP Bug Team Data UI: Not repopulating the ClinicSelection Tab Selections (Cell C3 & C4)

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#1867] opened 2021-04-08 19:53 UTC
@MattMoore2  @lzim  @lijenn discovered this prepping **today at 12noon** (see mtl.help@va.gov calendar).
**ClinicSelection** Tab of Data UI

**Discovered that getting the clinic selection from prior pull of Patient-level Data and Team Data Table were not functioning for C3 or C4.**

@anazariz Can you look at why this isn't functiong?
Jenn and I can talk about this with you at **hq_workgroup today** 😸 

![image](https://user-images.githubusercontent.com/7454688/114087894-4154da00-9869-11eb-8de9-1ae6023f6c17.png)

- [ ] C3: Get   previous clinic list from last click of Get Patient-level Data
- [ ] C4: Get   previous clinic list from Create Team Data Table file named [none]

**Comment by anazariz** [comment] 2021-04-08 20:34
@lzim @staceypark @lijenn 

Please see #1825 when I'd provided an update on this.

**Comment by anazariz** [comment] 2021-04-09 16:50
@lzim @staceypark @lijenn 

### Progress Update 

I have compared **DataToolFRE14_nevermore.xlsm (current version of the Data UI workbook)** and **640a0_mpd_team2_data_ui_2019_07_17.xlsm (Andrew's last version of the Workbook that had a working "Get Previous..." button)**. 

Excel can be loosely thought of as freeform database. Each tab (worksheet) is a table, each column in that tab is a table field and each row in that tab is table record. VBA uses this structure to store things. Our workbook use the Hidden tab to store values for various functionality. The problem with Excel is that you can inadvertently repurpose columns and rows and disrupt functionality. 

Looking at the code I see changes between the current version and Andrew's version. The issue is that I cannot just plug in what Andrew had because it might break new functionality that has been introduced since. There are also quite a few number of  sequential dependencies that I must work through to make sure that by adding the old functionality no chains of actions get interrupted. 

I'm currently working on this issue (bug) and will have an estimate fairly soon.

**Comment by anazariz** [comment] 2021-04-09 23:55
@lzim @staceypark @lijenn 

Workbook had multiple issues with the two "Get previous clinic..." buttons. I have fixed them. Will schedule testing before propagation.

**Comment by lzim** [comment] 2021-04-14 00:09
@anazariz 
@staceypark 

Shouldn't this bug have moved forward through the kanban?

❔ Thanks!

**Comment by lzim** [comment] 2021-04-15 00:30
@anazariz
@staceypark

Shouldn't this bug have moved forward through the kanban?

❔ Thanks!

**Comment by lzim** [comment] 2021-04-19 14:38
@anazariz
@staceypark

Shouldn't this bug have moved forward through the kanban?

❔ Thanks!

**Comment by anazariz** [comment] 2021-04-19 14:59
@lzim @staceypark 

Should have. I have already resolved this issue. @dkngenda and @staceypark did the Test QA and @Lzim did the Prod QA (in Prod). Closing the ticket.

**Closed by anazariz** 2021-04-19 14:59 UTC
Labels: quant

**Comment by hnorthcraft** [comment] 2025-05-12 21:10
#adjudicate_memo efforts tracked to other card #1825, assigning dup
