### ISSUE TITLE
wk4 aug_epic: UAT BUG - 6.21 Session Notes - Browser window does not dynamically update

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2206] opened 2021-08-27 22:04 UTC
1. **Who encountered the bug:** Jenn

2. **Which instance are you testing in?:** QA

3. **Date/Time of the bug:** Fri. 8/27 at 3:00pm Pacific

3. **Role:** Admin

4. **Detailed description of the bug:** Same issue as #2205.

@hsnyder2  @apisano0920  
I reached max number of character in the notes field and the window box would not dynamically update in length for long session notes (I used Session 06).

![image](https://user-images.githubusercontent.com/59668647/131193102-94b28bc5-f16f-4d8c-bff4-64f09f12d294.png)

**Comment by hsnyder2** [comment] 2021-08-30 15:05
Tried to reproduce in QA by adding ALL Session Notes on a separate Notes entry on the same session (S01: Team vision for jenn_mtl_team_email) and didn't get the error.  @lijenn - Will need to do a screenshare so you can show us exactly what you tried to add that caused the error.

**Comment by hsnyder2** [comment] 2021-08-30 16:31
Can't reproduce.  Moving to Testing for @lijenn to see if she gets the error next time she tries this.

**Comment by lijenn** [comment] 2021-09-07 12:40
@hsnyder2 Not getting the max number of charac. issue anymore, but the window still seems to get stuck the moment I paste in Session 6 notes and I can't scroll to view everything I copied, even using the extra scroll bar and scrolling all the way down:
![image](https://user-images.githubusercontent.com/59668647/132346032-17dfdbb6-65a3-47f3-8b47-4d958255681a.png)

**Comment by hsnyder2** [comment] 2021-09-08 14:47
Went to that session to open your Note to see if I could open/edit but doesn't look like you saved it (?) so I added a new one to try to reproduce but didn't get what you're getting.  Can we do a screen share to reproduce on your machine?

**Closed** 2021-09-16 20:27 UTC
Labels: d365
