### ISSUE TITLE
2024_08 Sim UI PROD - MTL 3.7 #consult_workflow - Require Administrator OR Team Lead (not Team Lead only)

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#3182] opened 2024-06-13 16:15 UTC
**wk2 2024_06 #sim_ui_workflow**
@ljmoody 
@tejaspesquare 

@lzim was working on setting up [#572](https://github.com/lzim/research/issues/572) for our 06/25/2024 consult and noticed these issues.

- [ ] 01. Should not force Team Lead, should force Administrator or Team Lead during Team Set Up.
    - _Rationale:_ While a team may set themselves up in the future, the current **#consult_workflow** is for _MTL 3.7_ administrators to pre-package the site use case. So, all the Sites will be set up by administrators.

**Comment by jamesmrollins** [comment] 2024-06-17 15:23
@lzim 

- A Team Lead or Player is **required** because Epicenter requires at least one member of a team besides an Epicenter-facilitator role. 
- Administrators should be added automatically.

**Comment by ljmoody** [comment] 2024-06-18 15:32
Given the rationale above, can we close this card @jamesmrollins?

**Comment by lzim** [comment] 2024-06-19 22:50
@jamesmrollins 
@ljmoody

Probably shouldn't close yet.
Cross-ref odd behavior of https://github.com/lzim/teampsd/issues/3189
In which I could not discern what world I was in.
Received a message that I was not an Admin.
But, then was listed as Admin in all worlds for that site.  

The Epicenter backend logic isn't too hard to understand. It's just not compatible with the frontend **#consult_workflow** for study sites in which the Administrators set up all the teams and prep their consults before Team Leads are identified. 

FYI: **#systems_sme_workflow** 
@dlkibbe
@dlounsbu 
Present state of #consult_workflow with the _MTL 3.7 Blue_ Sim UI in PROD requires non-intuitive need for all Administrators set themselves up as Team Leads instead of administrators to avoid

**Comment by jamesmrollins** [comment] 2024-07-01 02:52
@ljmoody let's discuss this use case.  I think we should go through the team setup together.  I think I know what the issue is, and I think we may have resolved it.  But we should step through it and confirm. Let's target 8 AM Workflow for the walkthrough.

**Comment by ljmoody** [comment] 2024-07-03 18:49
When discussing use case with @jamesmrollins today, anomalies were noted; submitted bug via #3203.

**Comment by jamesmrollins** [comment] 2024-07-08 17:09
@tejaspesquare @ljmoody @lijenn @matomasz 

## Update 7/8

- [ ] When an Admin creates a group for the first time, we will use a default user account to establish the _ind group automatically.
- [ ] The user account will be default_user@mail.com
- [ ] @jamesmrollins will create the default user account.

**Comment by jamesmrollins** [comment] 2024-07-11 21:50
@tejaspesquare

- [ ] I created a user account as shown above.
- [ ] Please provide a weekending update. 

Thank you

**Comment by tejaspesquare** [comment] 2024-07-12 13:57
HI @jamesmrollins 
 
> * [ ]  I created a user account as shown above.

I would like to have a conversation regarding this arrangement. If possible, could we setup a meeting.

**Comment by tejaspesquare** [comment] 2024-07-16 13:32
Hello @jamesmrollins, @ljmoody, @lijenn,

Default user account "default_team_lead@mail.com" is included automatically when Administrator perform Test Setup.
This can be verified on TEST.

1. _team world
![image](https://github.com/user-attachments/assets/ec584b5c-015c-4e4e-a197-92cd6610c100)
![image](https://github.com/user-attachments/assets/0ae034cb-a1d9-4d05-a3d5-f61056945f69)

Note: If you noticed, Laura Moody's got both accounts with different roles. One got updated through default list (as Administrator) & another got pushed through Team setup (as a Lead)

2. _shared world  (Default Members + Default Lead Member + Logged in User)
![image](https://github.com/user-attachments/assets/b81f8fdd-cff8-40d2-823e-5ed159ff1d0d)
![image](https://github.com/user-attachments/assets/21df4b91-d1fb-44b2-8180-d35a27130f3a)

**Comment by jamesmrollins** [comment] 2024-07-17 04:59
@tejaspesquare 

Please add these default team leads to all groups in the PROD project.

**Comment by ljmoody** [comment] 2024-07-17 16:08
@jamesmrollins @lijenn & @tejaspesquare, 
Testing for Default Team Lead add in TEST: I created new teams today in Edge and Chrome. It only displays _ind and _team worlds. And I don't see the default team lead added to teams - do you?

### EDGE:
![image](https://github.com/user-attachments/assets/a2bdfc6a-c869-46ae-ae77-cf1a4104e9a8)
![image](https://github.com/user-attachments/assets/e8bd677a-997b-4409-88e7-20588fc7a72f)

### CHROME:
![image](https://github.com/user-attachments/assets/8253006f-0fe7-416e-8225-5d1cacc60798)
![image](https://github.com/user-attachments/assets/7b546ab1-08b2-4a11-ae5f-97f4d73c1c78)

I tried a browser refresh, hard reset, and cleared cookies, cashed info, autofill data, etc. - no change in results.

**Comment by lzim** [comment] 2024-07-17 21:00
**Discussed wk3 2024_07 #sim_ui_workflow**
@jamesmrollins 
@matomasz 
@lijenn 
@ljmoody 

- A default team lead enables model initialization at Go in the DDD.
- No communication occurs with the default team lead email. 
- You can assign multiple team leads to a group.
- You can change team lead assignments at any time.

**Comment by tejaspesquare** [comment] 2024-07-18 05:14
Hello @ljmoody
 
> @jamesmrollins @lijenn & @tejaspesquare, Testing for Default Team Lead add in TEST: I created new teams today in Edge and Chrome. It only displays _ind and _team worlds. And I don't see the default team lead added to teams - do you?

In my testing on TEST I don't see any issue. All 3 worlds got created with default team lead.

![image](https://github.com/user-attachments/assets/5d49a3ab-2075-43c8-be67-94e2ef3ef498)

Today's created Team
_team world
![image](https://github.com/user-attachments/assets/2e23cd3c-1306-4bd3-b49b-628175cfbb07)
_shared world
![image](https://github.com/user-attachments/assets/2591a577-cd79-4bb3-b9ad-f3ec9774d4e2)

Team setup on 16th July
_team world
![image](https://github.com/user-attachments/assets/9c91820b-ad8e-4fe7-bf14-185fcf668827)
_shared world
![image](https://github.com/user-attachments/assets/72b69ce2-3b57-4d86-be69-b89b4bc35432)

**Comment by ljmoody** [comment] 2024-07-18 22:55
@tejaspesquare, I tested this in TEST today and these were the teams the Sim created with no added (by me) users. 

## Test 1 - Edge browser
- missing auto-added list of 6
- default dev user account (default_team_lead@email.com) is also missing
![image](https://github.com/user-attachments/assets/a9cd0811-0414-4723-9b5b-24c41c8d47f7)

## Test 2 - Chrome browser
- _shared team is missing/was not created/is not showing
![image](https://github.com/user-attachments/assets/f6e712ab-50b8-43af-ac39-bf257cc924e6)
- default dev user account is missing
![image](https://github.com/user-attachments/assets/18dece1a-e9af-4046-a0fe-6291e907319a)

**Comment by matthewtomo** [comment] 2024-07-22 17:25
**Discussed in  support, systems_sme, & sim_ui workflows sync meeting**
@lijenn 

Ran into issue during live demo in PROD environment where default team lead account (default_team_lead@email.com) is missing.

@matomasz will check TEST environment to see if default team lead account is successfully being added with team creation

**Comment by lzim** [comment] 2024-07-23 01:41
Please update @lzim on this one. I'll be reviewing preps and scheduling consults using PROD. Thanks so much!

**Comment by matthewtomo** [comment] 2024-07-29 12:44
**Discussed DEV Standup 7/29/2024**
@matthewtomo @tejaspesquare 

- The default team lead functionality is not fully in PROD yet.
- @matthewtomo will work on testing the behavior in DEV/TEST to move this update forward.

fyi: @jamesmrollins @lijenn @ljmoody

**Comment by lzim** [comment] 2024-08-01 21:54
@jamesmrollins @lijenn @ljmoody @matthewtomo 

_Will you please include in the update how **#systems_sme_workflow ** users would be setting up now, if this is not in PROD yet?_ Thanks!

**Comment by matthewtomo** [comment] 2024-08-05 16:23
@tejaspesquare It appears that the default team lead behavior is working correctly in TEST, **except for** an additionally admin user (Roshan) being added. After that account is no longer included in the default team list, the behavior will be correct and ready for PROD.

![image](https://github.com/user-attachments/assets/6c3e2b84-5cf2-4ac5-b295-956070bc07c5)

**Comment by matthewtomo** [comment] 2024-08-08 16:19
**Tested 8/8/2024**

- Feature is now working correctly in TEST on edge and chrome
- Ready for PROD

## Chrome
![image](https://github.com/user-attachments/assets/b04e3c90-d93d-432c-b9e2-9aeebfefbbc3)

## Edge
![image](https://github.com/user-attachments/assets/28df22f8-d421-4900-a34d-35ea072dffc5)

**Comment by matthewtomo** [comment] 2024-08-20 14:21
Closing this issue as the behavior has been corrected and the update has been pushed into PROD.

**Closed by matthewtomo** 2024-08-20 14:21 UTC
Labels: sim_ui, sim ui dev
