### ISSUE TITLE
2023_wk2_jun_#story_b: As a facility self-registering user, I need to login to Sim UI

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#2964] opened 2023-05-02 19:29 UTC
## Definition of Done

- [ ] Update code to read user selection of group type, then navigate to appropriate starting homepage.

**Comment by jamesmrollins** [comment] 2023-06-07 01:37
Cross Reference: #2960

**Comment by lijenn** [comment] 2023-06-12 14:47
@jamesmrollins @lzim I wonder if it's because we tried to have redundancy from Dynamics? That's the only other place that I think of where we have to manually input the research arm.

I also don't recall this field having any impacts on generating TT reports for blue or red teams? Might need to double check on this.

**Comment by jamesmrollins** [comment] 2023-06-12 23:14
#2978 contains the wireframe for the above.  Updated dependency to indicated "blocked" by QA DEV.

**Comment by jamesmrollins** [comment] 2023-06-14 20:20
Updated Wireframe based on feedback from QA DEV:

[Sim UI Release 3.7 - Self Registration and Fac Dash Update.pdf](https://github.com/lzim/teampsd/files/11750208/Sim.UI.Release.3.7.-.Self.Registration.and.Fac.Dash.Update.pdf)

**Comment by jamesmrollins** [comment] 2023-06-15 01:35
@hirenp-esquare - this is released for Development.

Updated Wireframe based on feedback from PI review:

[Sim UI Release 3.7 - Self Registration and Fac Dash Update.pdf](https://github.com/lzim/teampsd/files/11751833/Sim.UI.Release.3.7.-.Self.Registration.and.Fac.Dash.Update.pdf)

**Comment by jamesmrollins** [comment] 2023-06-15 23:26
@hirenp-esquare - this wireframe updated with the items we discussed regarding team naming convention.

[Sim UI Release 3.7 - Self Registration and Fac Dash Update.pdf](https://github.com/lzim/teampsd/files/11763930/Sim.UI.Release.3.7.-.Self.Registration.and.Fac.Dash.Update.pdf)

**Comment by jamesmrollins** [comment] 2023-07-07 17:43
Hi @hirenp-esquare see below for edits to self registration

## Change link name on login 

![image](https://github.com/lzim/teampsd/assets/30132017/9892d42f-7d2b-4581-9e4f-4a0a500826cf)

**Comment by lijenn** [comment] 2023-07-10 21:19
Hi @jamesmrollins @hirenp-waferwire! Please review the feedback below from my user test session w/ @ljmoody:

- [ ] 1. Self-Registration may not be clear for first-time users (i.e. don't know where to click).
Consider changing the language to "Register for First Time".
![image](https://github.com/lzim/teampsd/assets/59668647/971f5f6e-b332-4803-87f1-3d44ca6e0576)

- [ ] 2. Jenn couldn't see the dropdown menus when Laura was making dropdown menu selections when screen-share.
(Note: This may only be an issue for Citrix users, worked fine when screen-sharing on GFE).
![image](https://github.com/lzim/teampsd/assets/59668647/f81d4707-80d9-40e3-a4a1-d7e697f73ea6)

- [ ] 3. Add missing VHA Role: Data Subject Matter Expert
![image](https://github.com/lzim/teampsd/assets/59668647/85d00b56-8651-4840-9dd0-2f3e9e8b116b)

- [ ] 4. Ask Hiren to remove double-digit/letter Facility list dropdown - @jamesmrollins said those represent cemeteries (?)
![image](https://github.com/lzim/teampsd/assets/59668647/4352040c-0436-420c-8a50-ec63d5598bc1)

- [ ] 5. When selecting/drilling down a VISN, the Facility list is not narrowed down (still shows entire list of Facilities across all VISNs, e.g. 640 is not in V10).
![image](https://github.com/lzim/teampsd/assets/59668647/ee1a69a9-4e91-423d-9753-21307356222e)

- [ ] 6. Consider making all the yellow marked fields in screenshot required fields.
![image](https://github.com/lzim/teampsd/assets/59668647/88627864-5e0f-49b1-a2ae-0eec1c255483)

- [ ] 7. Follow-up question: _Why isn't the user required to select a clinic?_ Is it represent users who might represent/be a part of a whole Facility/sta3n and doesn't need to specify a specific Clinic/sta6a?
![image](https://github.com/lzim/teampsd/assets/59668647/a67a76bd-2fbc-4f9b-ba56-2f93b91ef729)

- [ ] 8. Laura was unable to enter a name for Facility Name. Laura was using Citrix via her Mac. _Can @jamesmrollins recreate the issue on Citrix?_
![image](https://github.com/lzim/teampsd/assets/59668647/0a5eb49e-3446-4236-b257-ed0ca8a091d2)

- [ ] 9. All letters in Facility Name should be lower-case.
![image](https://github.com/lzim/teampsd/assets/59668647/525c5ed6-7a7c-4ffd-b3f1-b3aef65d4501)

- [ ] 10. Can we alphabetize/organize the Clinic list dropdown?
![image](https://github.com/lzim/teampsd/assets/59668647/1f896c71-63db-4ab5-8120-e443a94322c7)

- [ ] 11. Consider editing "Registration" at the top of the form to "Register an Account as a First-Time User"
![image](https://github.com/lzim/teampsd/assets/59668647/0937eba8-3a4d-434c-9d13-0c2ec136eb25)

- [ ] 12. Consider editing "Password" to "New Password"
![image](https://github.com/lzim/teampsd/assets/59668647/d7110a0c-65d1-4ae6-97a2-7cb06e5d1c3a)

**Comment by lijenn** [comment] 2023-07-11 13:58
Adding some additional feedback for the email sent out after a user registers @jamesmrollins @hirenp-esquare.
- [ ] 13. Would this email go to MTL Help for someone to approve? It also will need to remove facilitator language.
<img width="718" alt="image" src="https://github.com/lzim/teampsd/assets/59668647/a21948b9-f214-45f3-9f22-1b70200f8143">

- [ ] 14. Remove facilitator language. Is there a way to force users to enter a lower-case Facility name?
<img width="609" alt="image" src="https://github.com/lzim/teampsd/assets/59668647/3c1efdb0-2f6e-47e3-9f29-77e27ecab98e">

**Comment by jamesmrollins** [comment] 2023-07-13 23:22
Hi @lijenn and @ljmoody - Thank you very much for the thorough testing of the self-registration flow.  

1.  @hirenp-esquare - please implement the suggestions above.
2. @lijenn  regarding #7 above, yes, we may be working at the Sta3n level only, so a Sta6a code is not mandatory.
3. @lijenn  regarding #13 above, yes, the approval email would go to mtl.how@va.gov.
4. @hirenp-esquare feel free to reach out to any of us for clarification.

Thank you

**Comment by lijenn** [comment] 2023-07-14 20:50
- [ ] Laura and Jenn will make sure they test new user and existing user perspectives for Facilitator Dashboard user testing after first set of user testing feedback is incorporated.

**Comment by lijenn** [comment] 2023-07-26 17:17
To discuss with @jamesmrollins @ljmoody at 7/26 sim_ui_workflow meeting, if possible:

- [ ] Still not seeing dropdown menus during screenshare via Mac > Citrix > Chrome
![image](https://github.com/lzim/teampsd/assets/59668647/1caba305-13c5-4ecc-a746-5108ada16cac)

- [ ] Prevent user from using upper case letters and spaces when entering facility team name:
![image](https://github.com/lzim/teampsd/assets/59668647/80e287d0-c8db-4035-b0ba-270ecf6423f9)

- [] Consider greying the buttons and include additional text that the registrant is approved, the green pop-up box disappears too quickly.
![image](https://github.com/lzim/teampsd/assets/59668647/2063b453-5978-458b-a296-0988155acb2b)

- [ ] Consider changing "Approve" hyperlink text to "here"
![image](https://github.com/lzim/teampsd/assets/59668647/04882309-16ac-44e2-99ec-bd671fec08bb)

- [ ] Consider changing "Login" hyperlink text to "the Sim UI"
![image](https://github.com/lzim/teampsd/assets/59668647/071a20a9-1593-43ec-bb95-310f80ecc316)

- [ ] After approving, Laura is still unable to login
![image](https://github.com/lzim/teampsd/assets/59668647/5502412a-e2a0-45f9-bad2-58a44dc587ad)

- [ ] Jenn registered with her praxis email and was able to login, but her approved team did not show up and she showed up as an administrator
![image](https://github.com/lzim/teampsd/assets/59668647/7da1f488-29fa-4b0e-a742-5be8b234170c)

- [ ] Neither Laura or Jenn's emails nor approved facility teams show up in the Test - Slow instance
![image](https://github.com/lzim/teampsd/assets/59668647/cd9d0f9a-ff0c-43fb-bfcf-c5d7aa79d58c)

- [ ] Assumption: _An existing registered user can go to the self registration page to create a new team?_

**Comment by lijenn** [comment] 2023-07-26 20:29
DECISION: We are unable to address the screensharing issue for menu dropdowns using Mac Citrix. Likely due to a MS Teams screensharing issue.

**Comment by lijenn** [comment] 2023-07-26 20:44
Identified at sim_ui_workflow 7/26
@hirenp-esquare @jamesmrollins need to discuss:

- [ ] We tried resetting @ljmoody's VA email account password on the Sim UI, but came across this issue:
![image](https://github.com/lzim/teampsd/assets/59668647/1a68765f-f451-43fa-a71c-58bb66ff16c1)

We confirmed Laura is an end-user in the Test instance too.
![image](https://github.com/lzim/teampsd/assets/59668647/a808dcb0-6a69-4ce5-9fe7-bd7a7d7903ea)

**Comment by lijenn** [comment] 2023-08-10 16:51
Hi @hirenp-esquare, please review @ljmoody and my feedback below. 

1. - [ ] Remove the space after the second underscore (blue circle)
2. - [ ] Prevent users from entering uppercase, only lower case (yellow highlights)
3. - [ ] Prevent users adding spaces, spaces should be underscores (red underlines)
![image](https://github.com/lzim/teampsd/assets/59668647/501dbd4f-ba01-4068-a5ac-6efd3c5a4d16)
------
4. - [ ] Can we make this pop-up automatically close after the user clicks submit OR grey out the button after the user clicks submit?
![image](https://github.com/lzim/teampsd/assets/59668647/1fb431c2-4d10-4eb0-b7da-85951b44e500)

-------
5. - [ ] Why is Laura automatically assigned the Facilitator role once she approves her registration?
_Did we want to assign first time users with the Member role_ @jamesmrollins?
6. - [ ] After being approved and signing in, Laura does not see the team she registered for. 
![image](https://github.com/lzim/teampsd/assets/59668647/2c8705ee-d07c-4014-bf41-dd5e835287a8)

**Comment by ljmoody** [comment] 2023-09-05 22:30
Hi @hirenp-esquare, I have some feedback to incorporate into the Sim UI based on meetings with @lijenn and @jamesmrollins today:

## in the Facilitator Dashboard:

- [ ] 1. Change dropdown menu initial text to "Select Module"  &  
- [ ] 2. Update Tutor menu/messages

<img width="1086" alt="image" src="https://github.com/lzim/teampsd/assets/124643236/1c665090-f653-4ef3-8454-cc735dea2e0d">

- [ ] 3. Create a main dashboard Tutor prompt

<img width="1417" alt="image" src="https://github.com/lzim/teampsd/assets/124643236/1e70e606-e067-430a-8b57-c801afc45637">

## _everywhere_ in the Sim UI:

- [ ] 4. Remove video icon from prompts

<img width="620" alt="image" src="https://github.com/lzim/teampsd/assets/124643236/339067d2-1cc5-4b5b-836c-b227136b4405">

- [ ] 5. Remove the Video Link column

<img width="1111" alt="image" src="https://github.com/lzim/teampsd/assets/124643236/a5b33b42-bd8b-4a9e-908e-66ab1c67aed6">

**Comment by ljmoody** [comment] 2023-09-08 21:12
Hi @hirenp-esquare, two more things I noticed when in the Sim UI (I tried different browsers to see if that mattered, and it didn't.):

## in the Facilitator Dashboard:

- [ ] 1. The "click here to collapse or expand" popup is not pointing to the right location on the page:
![image](https://github.com/lzim/teampsd/assets/124643236/a294d1b2-6321-446f-b308-b6d88352dbfd)

- [ ] 2. The "click here to close the dashboard" popup is not pointing to the right location on the page: 
![image](https://github.com/lzim/teampsd/assets/124643236/e5cead46-1922-41aa-bbb4-a527b731084b)

FYI: @jamesmrollins @lijenn

**Comment by lijenn** [comment] 2024-02-09 21:56
Jenn and Laura have been completing the rest of QA in #3026 for Self-Registration. We can close this card since the work with Hiren has been completed.

**Closed by lijenn** 2024-02-09 21:56 UTC
Labels: sim_ui, sim ui dev, feature, Development
