### ISSUE TITLE
ANDON 9/28 Sim UI AGG Reverting to Balance Mode not Team Data Default - 9/29 Update working w/Forio on Vensim <> Epicenter Interface

### ISSUE THREAD

**Issue by dlkibbe** [lzim/teampsd#2276] opened 2021-09-28 13:17 UTC
**1. Add description:** 
Session 8 - @dlkibbe and @hmarcia, 8:00 am team
Base case run showed all flat lines in 2 individual worlds of team members initially.
In the team world, Marcia re-ran the base case and it showed oscillation (in team world TD_bc_psy_2021_9_28) and then re-ran it and the bc was flat (in team world TD_bc_2021_9_28). When we ran engagement duration experiment, bc showed flat. 
@hmarcia re-ran the engagement duration experiment - comparison to BC and oscillation is not working. @lijenn see team prep chat for note and screenshot on that run.

<img width="544" alt="Laurens screen - Altoona bc" src="https://user-images.githubusercontent.com/31182258/135092417-2f24a6f9-a03c-4cd7-8cac-2b1b47882f8f.PNG">

 
<img width="687" alt="Marcias screen - bc 1 bc 2" src="https://user-images.githubusercontent.com/31182258/135094306-04593b86-b39e-44cc-9c1a-5e2ad74585e3.PNG">

**2. Click on the right:**  
<img width="544" alt="Laurens screen - Altoona bc" src="https://user-images.githubusercontent.com/31182258/135092355-107dac49-a8e0-4d03-9163-df4be49d0000.PNG">
<img width="544" alt="Laurens screen - Altoona bc" src="https://user-images.githubusercontent.com/31182258/135092317-521ae7bd-91f5-45c3-aa03-3f4c1faaf1a0.PNG">
i. **Pipelines** - prioritize in a TeamPSD (& Workgroup) pipeline  
ii. **Assignee** - assign to an individual team member producing work for the issue  
iii. **Label**- assign workgroup (lead) responsible for tracking the task  
iv. **Projects** - assign to domain-specific TeamPSD tracker (issues, features, document, manuscript, team)  
v. **Milestones** - select monthly sprint milestone within the workgroup   
vi. **Estimate** - Estimate task in complexity points   
vii. **Epics** - assign to team-wide epic and TeamPSD master plan project  
iix. **Releases** - assign to key team release grouped with other relevant issues  

**3. If you anticipate that your **issue card** or **bug card** will have **dependencies** these can be added once the issue has been submitted.   
ix. **Add dependencies** - assess for and add dependencies *blocking* & *blocked by* this issue

**Comment by dlkibbe** [comment] 2021-09-28 15:36
Discussed at Facilitate work group 9/28/2021 - updated title of bug. Realized that the simulation results may be due to us expecting the default to be team data mode vs. balanced mode. @jamesmrollins

**Comment by lzim** [comment] 2021-09-28 17:41
@jamesmrollins Not sure if this is clear that the facilitators and team would like **team data mode** to be the default mode for AGG? But, do not believe it was operating that way today, which led to confusion. Thanks!

**Comment by jamesmrollins** [comment] 2021-09-28 19:31
Hi @lzim -  Its clear - Team Data has always been the default mode.  Still trying to get to the bottom of what exactly happened.  The client model returns the appropriate curve for base case, so does the PROD server model using same TD.  So I am not sure why the _ind session was switched to balanced mode.  

We are checking it out.

**Comment by jamesmrollins** [comment] 2021-09-29 02:16
Hi @dlkibbe and @hmarcia and @lijenn I have reviewed 4 hours of film, looked high and low to find the origin of the reported error and I cannot locate it.  I cannot replicate it, nor can I trace it back through sessions dating back to 7 September.  I will likely need to interview to help retrace steps.  The only thing I can think of is the 9_14 TD bc save was just before the reported bug that was changing the TD to Bal when the user clicked run.  Perhaps the 9_14 was run in what was thought to be TD mode, but really ran in Bal mode (which explains the flat lines).  Interestingly, the 9_14 then later 9_21 experiment is not available anymore - did someone delete it?

**Comment by lijenn** [comment] 2021-09-29 19:27
@dlkibbe Debbie ran a td_bc_2021_9_28 experiment yesterday for her team that meets on Wed. from 10-noon Pacific in her team's ind world and noticed Psych - Patients Waiting to Start should be showing an oscillation but it's a flat line.
![image](https://user-images.githubusercontent.com/59668647/135335211-00f4a67d-349b-4eb8-86e9-7490121acba1.png)

She compared it to team's worlds td_bc_2021_7_28, it's showing the oscillation.
![image](https://user-images.githubusercontent.com/59668647/135335262-0526b80d-3bef-4e92-abe8-14ba9dfffbf5.png)

@jamesmrollins Noticed that the model didn't run right on the server and will need to get in touch with Forio.
He downloaded the model (vmfx) from PROD and ran the same TD file and see the oscillation.  For some reason the server based model didn't do that in this case.

![image](https://user-images.githubusercontent.com/59668647/135335148-cad6afde-b6f6-4851-9d3e-772ecf083fb1.png)

@dlkibbe Please hold off on running any experiments in your team's individual world for the moment while @jamesmrollins looks into this issue.

**Comment by jamesmrollins** [comment] 2021-09-29 23:30
Hi @lzim, @dlkibbe @lijenn @hcpark 

## Analysis of the Problem

- The flat line that @dlkibbe experienced, while it seems to emulate a balanced mode setting in the "Psych Patients Waiting to Start a Service," the actual values returned are also incorrect (-.34 in Sim versus 1.33722 in client) see screen capture below.
- I reviewed 4 hours of user videos dating back to 7 September to discount a potential user error of some kind (such as using a previous experiment that has a balanced mode setting).
- I escalated to Forio and found that model information was logged into the server correctly and the data returned was represented properly in the UI.  
- I reset the @dlkibbe 's experiment and reran the experiment 30 times successively.  The Sim UI returned correct results each time.

![image](https://user-images.githubusercontent.com/30132017/135361774-a0b0fc77-ebb4-4310-befa-b30bd07a89d9.png)

## Conclusion

- A rare anomaly has occurred.
- The anomaly may occur again, but would be low probability event.
- The anomaly could be an internet API timing issue, meaning an API made a call, but didn't wait for a complete answer.

## Recommendation

- Forio and Praxis will set up an automatic interrogation routine that will send the model to the server with associated model parameters to see if we can get it to log a failure over the course of 1000's of cycles.  If we find a problem with the model, then we will escalate to Vensim.
- Forio is going to upgrade, soon, to Vensim 9.0.0.  We tested the Ver 9.0 created model in ver 8.1 and it worked fine in the client.
- Since we anticipate this problem to be a rare occurrence, we recommend clearing the ANDON.  Then let the users know that if they encounter the problem, they should report immediately.  Then, they can reset the sim and try again.  It will likely run just fine.

**Comment by jamesmrollins** [comment] 2021-09-29 23:58
Hi @lijenn - Here is the outgoing message.  I tried to limit tech-speak.  

"Recently, the Sim UI returned incorrect results during an Aggregate Module experiment run for one of our teams. These numbers resulted in flat lines on graphs that previously showed oscillations. We think this problem is a rare occurrence; however, if this happens to you, **please report it immediately** to jrollins@praxisanalytix.com, or your facilitator.  The problem is easily corrected by resetting your experiment and running it again."

**Comment by lijenn** [comment] 2021-09-30 00:32
Thank you @jamesmrollins :) Tweaked it slightly since I'm worried the last sentence might imply some folks to not save the experiment.

How about this?
> "Recently, the Sim UI returned incorrect results during an Aggregate Module experiment run for one of our teams. These numbers resulted in flat lines on graphs that previously showed oscillations. We think this problem is a rare occurrence; however, if this happens to you, **please save the experiment and report it immediately to jrollins@praxisanalytix.com, or your facilitator.** In the mean time, the problem is easily corrected by re-running the experiment in a new session."

I'll also need to message for the Facilitators as well, what about this slightly modified version for them?

> Hi Facilitators,
> Recently, the Sim UI returned incorrect results during an Aggregate Module experiment run for (team 1 here) & (team 2 here). These numbers resulted in flat lines on graphs that previously showed oscillations. 
>
> **BLUF:** We think this problem is a rare occurrence; however, if this happens to you, **please save the experiment and report it immediately to jrollins@praxisanalytix.com and report it at mtl.how/bugs.** In the mean time, the problem is easily corrected by re-running the experiment in a new session."
>
> **Before running a new experiment, please:**
> 1. Double-check that you are not in a previous experiment's session (If you are, please save and reset or discard the experiment).
> 2. Check that you are in Team Data Mode.

Any thoughts?

**Comment by lijenn** [comment] 2021-09-30 00:37
EDIT: Instead of Facilitator, I think we should direct Learners to the Report Bug icon in the Sim?

> "Recently, the Sim UI returned incorrect results during an Aggregate Module experiment run for one of our teams. These numbers resulted in flat lines on graphs that previously showed oscillations. We think this problem is a rare occurrence; however, if this happens to you, **please save the experiment and report it immediately to jrollins@praxisanalytix.com, or click on the Report Bug icon at the top of the page.** In the mean time, the problem is easily corrected by re-running the experiment in a new session."

**Comment by jamesmrollins** [comment] 2021-09-30 03:27
@lijenn   Looks good to me!!  Are you going to post?

**Comment by lijenn** [comment] 2021-09-30 14:00
@jamesmrollins I see. In that case, since we don't want exact names and facilities on GitHub, I'm going to switch the Bug icon to MTL.Help@va.gov since Learner are familiar with this email already. That way all of us can see it and know who is specifically experiencing the problem, and what world.

"Recently, the Sim UI returned incorrect results during an Aggregate Module experiment run for one of our teams. These numbers resulted in flat lines on graphs that previously showed oscillations. We think this problem is a rare occurrence; however, if this happens to you, please save the experiment and report it immediately to jrollins@praxisanalytix.com and MTL.Help@va.gov and identify the world where the error occurred. In the mean time, the problem is easily corrected by re-running the experiment in a new session."

Otherwise, I think this is ready and I'll add it to the Sim.

**Comment by jamesmrollins** [comment] 2021-09-30 22:01
@lijenn @lzim @dlkibbe @hmarcia - Forio ran a test of 200 model runs with no errors.  That backs the potential error point up to the client-server interaction.  So it will be very important to notify me right away if it happens again, so we can capture the interaction logs from the client leading up to the error.   Thanks, James

**Comment by lijenn** [comment] 2021-09-30 23:49
Thanks @jamesmrollins! I'm closing this bug.

**Closed** 2021-10-01 00:39 UTC
Labels: bug

**Comment by dlkibbe** [comment] 2021-10-01 11:59
And once again "user error" ... I'll get it some day @jamesmrollins and @lijenn

**Comment by jamesmrollins** [comment] 2021-10-01 16:58
Hi @dlkibbe -  That's not what we are saying at all - this isn't user error.  This is on the computer, not you.  We just can't seem to figure out what happened.  If it happens again, call me right away.  😊 Keep smiling!
